### ISSUE TITLE
Repeated meta-annotations of @ArgumentsSource requires the @ArgumentsSource at test location

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#1112]
## Overview

I was writing up an example for https://github.com/junit-team/junit5/issues/1101 which contains an example like this:

```java
    @ParameterizedTest // still required?
    @Parameter(10, "10000")
    @Parameter(20, "20000")
    @Parameter(30, "30000")
    void calculate(int input, String expected) {
        assertThat(Integer.toString(input*1000)).isEqualTo(expected);
    }
```

Where `@Parameter` contains something like `@ArgumentsSource(ParameterSource.class)`. Running this yields an exception with `org.junit.platform.commons.util.PreconditionViolationException: Configuration error: You must provide at least one argument for this @ParameterizedTest`.

Here is an example that reproduces the issue:

* Annotation
    ```java
    import org.junit.jupiter.params.provider.ArgumentsSource;
    
    import java.lang.annotation.Repeatable;
    import java.lang.annotation.Retention;
    import java.lang.annotation.RetentionPolicy;
    
    @Retention(RetentionPolicy.RUNTIME)
    @ArgumentsSource(MetaCustomSource.class)
    @Repeatable(ExampleMetaCustomSources.class)
    public @interface ExampleMetaCustomSource {
      int value();
    }
    ```
* Repeatable annotation
    ```java
    import java.lang.annotation.Retention;
    import java.lang.annotation.RetentionPolicy;

    @Retention(RetentionPolicy.RUNTIME)
    public @interface ExampleMetaCustomSources {
      ExampleMetaCustomSource[] value();
    }
    ```
* `ArgumentsProvider` Extension implementation
    ```java
    import org.junit.jupiter.api.extension.ExtensionContext;
    import org.junit.jupiter.params.provider.Arguments;
    import org.junit.jupiter.params.provider.ArgumentsProvider;
    import org.junit.platform.commons.support.AnnotationSupport;
    
    import java.util.List;
    import java.util.stream.Stream;
    
    public class MetaCustomSource implements ArgumentsProvider {
      @Override
      public Stream<? extends Arguments> provideArguments(final ExtensionContext context) throws Exception {
        return context.getElement()
                      .map(annotatedElement -> AnnotationSupport.findRepeatableAnnotations(annotatedElement, ExampleMetaCustomSource.class)).map(
            List::stream)
          .map(stream -> stream.map(annotation -> Arguments.of(annotation.value())))
          .orElse(Stream.empty());
      }
    }
    ```
* Test class
    ```java
    import org.junit.jupiter.params.ParameterizedTest;
    import org.junit.jupiter.params.provider.ArgumentsSource;
    
    class MetaCustomSourceParameterizedTestExample {
      @ParameterizedTest
      @ExampleMetaCustomSource(1)
      void singleMetaTest(int value) {
      }
    
      @ParameterizedTest
      @ExampleMetaCustomSource(1)
      @ExampleMetaCustomSource(2)
      @ExampleMetaCustomSource(3)
      void multipleMetaTestNoArgumentsSource(int value) {
      }
    
      @ParameterizedTest
      @ArgumentsSource(MetaCustomSource.class)
      @ExampleMetaCustomSource(1)
      @ExampleMetaCustomSource(2)
      @ExampleMetaCustomSource(3)
      void multipleMetaTestWithArgumentsSource(int value) {
      }
    }
    ```

_Results_

![Test results output](https://user-images.githubusercontent.com/1447148/31622975-95e27fc2-b263-11e7-9d20-1847a634ed82.png)

Stacktrace from IntelliJ:

```

org.junit.platform.commons.util.PreconditionViolationException: Configuration error: You must provide at least one argument for this @ParameterizedTest

	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:285)
	at org.junit.jupiter.params.ParameterizedTestExtension.lambda$provideTestTemplateInvocationContexts$6(ParameterizedTestExtension.java:58)
	at java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:86)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:36)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:83)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:62)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Also, in addition, IntelliJ doesn't detect meta `@ArgumentSource` implementations

## Deliverables

- [ ] `@Repeatable` annotations containing meta-annotation of `@ArgumentsSource` should work without annotating `@ParameterizedTest` with  `@ArgumentsSource(ImplementingClass.class`

**Comment by mkobit** [comment]
Also sort of related, IntelliJ does not recognize the meta `@ArgumentsSource` and shows intentions that says _"No sources are provided, the suite would be empty"_.

![IntelliJ Junit 5 test source code showing invalid inspection](https://user-images.githubusercontent.com/1447148/31623247-775e33ec-b264-11e7-918e-90fbd01b6e08.png)

**Comment by sormuras** [comment]
Neat work @mkobit -- but is it really worth the effort? Using single annotations to pass arguments into a parameterized test limits the type of parameters that are allowed as [return types in annotation](https://docs.oracle.com/javase/specs/jls/se9/html/jls-9.html#jls-9.6.1) members. Which are not many at all: 

- A primitive type
- `String`
- `Class` or an invocation of Class (§4.5)
- An enum type
- An annotation type
- An array type whose component type is one of the preceding types (§10.1).

**Comment by sormuras** [comment]
> Also sort of related, IntelliJ does not recognize the meta @ArgumentsSource and shows intentions that says "No sources are provided, the suite would be empty".

That smells like an IntelliJ IDEA bug...

**Comment by mkobit** [comment]
> but is it really worth the effort?

I don't know if it is worth the effort (I'm leaning towards no), but I did find the behavior to be a bit surprising. I think in most cases you are going to want to use a `@MethodSource` or a custom `ArgumentsSource`.

> That smells like an IntelliJ IDEA bug...

Agreed, I will probably follow up at some point to file an issue. Just dropping it here in the mean time so I don't forget about it.

**Comment by marcphilipp** [comment]
@mkobit Have you tried annotating your container annotation with `@ArgumentsSource`, too?

```java
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@ArgumentsSource(MetaCustomSource.class)
@Retention(RetentionPolicy.RUNTIME)
public @interface ExampleMetaCustomSources {
  ExampleMetaCustomSource[] value();
}
```

**Comment by mkobit** [comment]
Updated issue with full stacktrace.

@marcphilipp yes, that seems to fix it.

![IntelliJ test results after adding ArgumentsSource to container annotation](https://user-images.githubusercontent.com/1447148/32506858-4c0448f0-c3ab-11e7-9526-8c9f905c5167.png)

**Comment by marcphilipp** [comment]
@mkobit Do you think that's a reasonable workaround and we can close this issue?

**Comment by mkobit** [comment]
Yes, I think that is reasonable. I felt like I was also seeing something similar to this with `@TestTemplate` but do not have a reproducible case for it. Going to close as this issue documents the behavior and the workaround is easy.
