### ISSUE TITLE
surefire provider should accept empty string for includeTags and excludeTags

### ISSUE THREAD

**Issue by tmurakam** [junit-team/junit5#1126]
## Overview

The junit-platform-surefire-provider does not accept empty string for includeTags and excludeTags properties.

It is inconvenient, because I can't  use default value in pom.xml and overwrite it with -D option. 

## Detail

When I pass empty string to includeTags/excludeTags, following exception occurs:

```
Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] org.apache.maven.surefire.util.SurefireReflectionException: org.junit.platform.commons.util.PreconditionViolationException: Tag name [] must be syntactically valid
[ERROR] 	at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:135)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.createProviderInCurrentClassloader(ForkedBooter.java:321)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: org.junit.platform.commons.util.PreconditionViolationException: Tag name [] must be syntactically valid
[ERROR] 	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:285)
[ERROR] 	at org.junit.platform.engine.TestTag.<init>(TestTag.java:120)
[ERROR] 	at org.junit.platform.engine.TestTag.create(TestTag.java:116)
[ERROR] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[ERROR] 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[ERROR] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[ERROR] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[ERROR] 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[ERROR] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR] 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[ERROR] 	at org.junit.platform.launcher.TagFilter.toTestTags(TagFilter.java:125)
[ERROR] 	at org.junit.platform.launcher.TagFilter.includeTags(TagFilter.java:79)
[ERROR] 	at java.util.Optional.map(Optional.java:215)
[ERROR] 	at org.junit.platform.surefire.provider.JUnitPlatformProvider.getIncludeAndExcludeFilters(JUnitPlatformProvider.java:154)
[ERROR] 	at org.junit.platform.surefire.provider.JUnitPlatformProvider.<init>(JUnitPlatformProvider.java:85)
[ERROR] 	at org.junit.platform.surefire.provider.JUnitPlatformProvider.<init>(JUnitPlatformProvider.java:79)
[ERROR] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] 	at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:131)
[ERROR] 	... 4 more
```

## Deliverables

- [ ] JUnitPlatformProvider.getPropertiesList() should accept empty string and convert it to null.

**Comment by marcphilipp** [comment]
@tmurakam Do you have time to work on a pull request?

**Comment by VikasSherawat** [comment]
@tmurakam may i work on this one?

**Comment by marcphilipp** [comment]
@VikasSherawat Absolutely!
