### ISSUE TITLE
Maven surefire provider NPE w/ the Spek TestEngine

### ISSUE THREAD

**Issue by raniejade** [junit-team/junit5#1130]
## Overview

For some reason running tests in maven: `mvn -e test`, causes an NPE when using Spek. It works for JUnit 5 (Jupiter), are we doing something wrong when implementing the Spek `TestEngine`?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project spek-with-maven-sample: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project spek-with-maven-sample: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at org.apache.maven.plugin.surefire.report.DefaultReporterFactory.printTestFailures(DefaultReporterFactory.java:346)
        at org.apache.maven.plugin.surefire.report.DefaultReporterFactory.runCompleted(DefaultReporterFactory.java:137)
        at org.apache.maven.plugin.surefire.report.DefaultReporterFactory.close(DefaultReporterFactory.java:106)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:208)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

Full detail of the issue can be found here:  https://github.com/spekframework/spek/issues/303

Also a demo project can be found here: https://github.com/devonhumes/spek-kotlin-maven-error-output-null.

**Comment by marcphilipp** [comment]
Looks like `stackTraceWriter` is `null` here:
https://github.com/apache/maven-surefire/blob/surefire-2.19.1/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactory.java#L346

Apparently (there's no documentation on this), a Surefire `ReportEntry` that is passed to `testFailed()` must have a `stackTraceWriter`. However, our Surefire provider is only setting one, when the `TestIdentifier` has a source of type `ClassSource` or `MethodSource`:
https://github.com/junit-team/junit5/blob/3909a2ad699b57ec960d7e12d316182717720685/junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/RunListenerAdapter.java#L95-L104

So, to fix this, we should always set a `stackTraceWriter`. The can follow the look at the ancestors of the `TestIdentifier` until we find a `ClassSource` or `MethodSource`. If we still don't find one, we can fallback to the `Class` that is currently being executed:
https://github.com/junit-team/junit5/blob/65701b9bb36709fffc938a819add7a51aae63185/junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java#L136-L137

---

@raniejade Do you have time to look into fixing it?

**Comment by raniejade** [comment]
@marcphilipp Gladly :+1:

**Comment by raniejade** [comment]
@marcphilipp any way to install artifacts locally? Want to test it out w/ Spek.

**Comment by marcphilipp** [comment]
`./gradlew install` should work.
