### ISSUE TITLE
ConsoleLauncher option is not supported

### ISSUE THREAD

**Issue by evser** [junit-team/junit5#1262]
When I use `--details summary` option, the following exception occurred. 
But it's mentioned in documentation
http://junit.org/junit5/docs/snapshot/user-guide/#running-tests-console-launcher-options. 

Exception in thread "main" org.junit.platform.commons.JUnitException: Error parsing command-line arguments
        at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:44)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:68)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
Caused by: org.junit.platform.console.shadow.joptsimple.OptionArgumentConversionException: Cannot parse argument 'summary' of option details
        at org.junit.platform.console.shadow.joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:92)
        at org.junit.platform.console.shadow.joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:277)
        at org.junit.platform.console.shadow.joptsimple.OptionSet.valuesOf(OptionSet.java:223)
        at org.junit.platform.console.shadow.joptsimple.OptionSet.valueOf(OptionSet.java:172)
        at org.junit.platform.console.options.AvailableOptions.toCommandLineOptions(AvailableOptions.java:207)
        at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:41)
        ... 3 more
Caused by: org.junit.platform.console.shadow.joptsimple.ValueConversionException: Value [summary] is not one of [[none,flat,tree,verbose]]
        at org.junit.platform.console.shadow.joptsimple.util.EnumConverter.convert(EnumConverter.java:63)
        at org.junit.platform.console.shadow.joptsimple.util.EnumConverter.convert(EnumConverter.java:41)
        at org.junit.platform.console.shadow.joptsimple.internal.Reflection.convertWith(Reflection.java:124)
        at org.junit.platform.console.shadow.joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:90)
        ... 8 more

**Comment by evser** [comment]
Fixed in 1.0.3

**Comment by sormuras** [comment]
`--details summary` is taken from "1.1-SNAPSHOT" or "1.0.3".
