### ISSUE TITLE
Bug: AfterAllCallback extension hides container failure

### ISSUE THREAD

**Issue by jorn86** [junit-team/junit5#1305]
Consider this test code:

```
@ExtendWith(ThrowingExtension.class)
class ReproTest {
    ReproTest() { this(""); }
    ReproTest(String s) { }

    @Test void test() { }
}
class ThrowingExtension implements AfterAllCallback {
    @Override
    public void afterAll(ExtensionContext context) {
        throw new IllegalStateException("Callback fails");
    }
}
```

This test is invalid, because it has two constructors. And JUnit will usually tell you exactly that. Unfortunately, the `AfterAllCallback` will still be executed in this case, and will hide the actual informative message.

If I have the thrown exception in an `@AfterAll` method in the test class itself, this will work correctly and give the `PreconditionViolationException` I'd expect.

**Comment by marcphilipp** [comment]
It's not hidden: The test method fails with the `PreconditionViolationException`. The test class fails with the `IllegalStateException`.

@jorn86 How do you execute your tests?

**Comment by jorn86** [comment]
I've tried running the test
* Directly from IntelliJ
* In IntelliJ, using Gradle
* From the command line, using Gradle

In all three cases, I'm only seeing the callback error:
```
Feb 23, 2018 4:25:17 PM org.junit.platform.launcher.core.LauncherConfigurationParameters fromClasspathResource
INFO: Loading JUnit Platform configuration parameters from classpath resource [jar:file:/home/jornh/repositories/solar/worcade/backend/test-util/build/libs/test-util.jar!/junit-platform.properties].
Feb 23, 2018 4:25:17 PM org.junit.jupiter.engine.descriptor.TestInstanceLifecycleUtils getDefaultTestInstanceLifecycle
INFO: Using default test instance lifecycle mode 'PER_CLASS' set via the 'junit.jupiter.testinstance.lifecycle.default' configuration parameter.
Feb 23, 2018 4:25:17 PM org.junit.jupiter.engine.descriptor.TestInstanceLifecycleUtils getDefaultTestInstanceLifecycle
INFO: Using default test instance lifecycle mode 'PER_CLASS' set via the 'junit.jupiter.testinstance.lifecycle.default' configuration parameter.
:selenium-tests:runJUnitPlatformTest
Test execution started. Number of static tests: 1
Started:     JUnit Jupiter ([engine:junit-jupiter])
Started:     ReproTest ([engine:junit-jupiter]/[class:net.worcade.ReproTest])
Finished:    ReproTest ([engine:junit-jupiter]/[class:net.worcade.ReproTest])
             => Exception: java.lang.IllegalStateException: Callback fails
             	at net.worcade.ThrowingExtension.afterAll(ReproTest.java:19)
             	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$null$9(ClassTestDescriptor.java:253)
             	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
             	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllCallbacks$10(ClassTestDescriptor.java:253)
             	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
             	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeAfterAllCallbacks(ClassTestDescriptor.java:253)
             	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:173)
             	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:62)
             	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:96)
             	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
             	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
             	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
             	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
             	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
             	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
             	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
             	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
             	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
             	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
             	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
             	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
             	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430)
             	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
             	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
             	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
             	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
             	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
             	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
             	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
             	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
             	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
             	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
             	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
             	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
             	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
             	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
             	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
             	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
Finished:    JUnit Jupiter ([engine:junit-jupiter])
Started:     JUnit Vintage ([engine:junit-vintage])
Finished:    JUnit Vintage ([engine:junit-vintage])
Test execution finished.
Test run finished after 88 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         1 containers failed     ]
[         1 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
```

**Comment by marcphilipp** [comment]
Ok, I'll double-check tonight.

**Comment by marcphilipp** [comment]
I could reproduce the bug, it only happens when `@TestInstance(PER_CLASS)` is used (as can be seen from the logging output).

**Comment by geo-m** [comment]
Under default licefycle the precondition single constructor exception is thrown during the preparation phase of the child nodes of the TestClassDescriptor (methods etc), where control immediately returns.

Using PER_CLASS, the exception is thrown during node.before in the try - catch block of HierarchicalTestExecutor#execute(line 80), enters finally block, where the callback exception masks the original exception as the fail cause. This is my first involvement with the project and if you decide on a plan for this i would like to try my luck, if this would be ok with you.

**Comment by marcphilipp** [comment]
@geo-m Thanks for the analysis and offering help. I already have a fix locally, though. You could review if you want. 🙂

**Comment by geo-m** [comment]
No problem, 145 more issues to choose from

**Comment by marcphilipp** [comment]
Indeed. 😁

**Comment by jorn86** [comment]
Thanks @marcphilipp for the quick response and fix!
