### ISSUE TITLE
Bug: duplicate --config key reported but value shown

### ISSUE THREAD

**Issue by robstoll** [junit-team/junit5#1308]
## Overview
I am using the platform-version 1.0.2. The bug happens when I use the ConsoleLauncher (from a gradle JavaExec Task, but I doubt that matters). 
I accidentally provided twice the same key for `--config` as follows:
'--config', 'forgive=".*spec:ch.tutteli.atrium.api.cc.en_UK.Iterable.*error cases.*"',
'--config', 'forgive=".*spec:ch.tutteli.atrium.api.cc.en_UK.Iterable.*failing cases.*"',

The following Exception was thrown
```
Exception in thread "main" java.lang.IllegalStateException: Duplicate key .*spec:ch.tutteli.atrium.api.cc.en_UK.Iterable.*error
	at java.util.stream.Collectors.lambda$throwingMerger$114(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1245)
	at java.util.stream.Collectors.lambda$toMap$172(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.junit.platform.console.options.AvailableOptions.toCommandLineOptions(AvailableOptions.java:237)
	at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:41)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:68)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
```

The error as such is fine, but I would have expected it reports that `forgive` was duplicated. I am not entirely sure if this a junit5 bug or a JDK8 bug but I guess you will find out quickly.

**Comment by sormuras** [comment]
Can you please try version **1.1.0** please?

Tried it locally with `"--config foo=bar --config foo=baz"` and results in the expected exception message:
```
java.lang.IllegalStateException: Duplicate key foo (attempted merging values bar and baz)

	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:131)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1494)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:511)
	at org.junit.platform.console.options.AvailableOptions.toCommandLineOptions(AvailableOptions.java:257)
	at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:41)
[...]
```

**Comment by sormuras** [comment]
Nevertheless, it should be an instance of `JUnitException` with a message of `Error parsing command-line arguments` and an atttached cause: `java.lang.IllegalStateException: Duplicate key foo (attempted merging values bar and baz)`.

Addressing this in master.

**Comment by robstoll** [comment]
Nope, looks still the same. You can reproduce it as follows:
1. git clone https://github.com/robstoll/atrium.git
2. open misc/atrium-bc-test/build.gradle
3. add '--config', 'forgive=test', to line 69
4. gr :atrium-bc-test:build

Following the Exception message I got:
```
Exception in thread "main" java.lang.IllegalStateException: Duplicate key .*spec:ch.tutteli.atrium.api.cc.de_CH.Iterable.*(error cases|failing cases|context empty collection).*
```

**Comment by sormuras** [comment]
Will try later. But reading the initial error message carefully, I guess the command line configuration you use in the Gradle script is not correct. Your value is interpreted as a key -- see the "missing" tail of your value after the first space character: `.*spec:ch.tutteli.atrium.api.cc.de_CH.Iterable.*(error`

Perhaps, you have wrap the value string into an extra `"`?

**Comment by robstoll** [comment]
That's actually what I figured at the beginning. In the first output in the description of this task I wrapped it in `"` and that was actually the reason why my argument got chopped into two parts (see also https://github.com/gradle/gradle/issues/4510). 
See the output in my last comment https://github.com/junit-team/junit5/issues/1308#issuecomment-368344004, the argument is not split up. The error message is wrong nonetheless.

**Comment by sormuras** [comment]
It's a bug in Java 8. See https://bugs.openjdk.java.net/browse/JDK-8040892 for details. It was fixed in Java 9.

@junit-team/junit-lambda shall we roll our own `toMap` helper and always emit the a helpful error message?

```
	private Map<String, String> map(List<KeyValuePair> pairs) {
		Map<String, String> map = new HashMap<>();
		for (KeyValuePair pair : pairs) {
			String key = pair.key;
			if (map.containsKey(key)) {
				Exception cause = new IllegalStateException("Duplicate key " + key + " in: " + pairs);
				throw new JUnitException("Error parsing command-line arguments", cause);
			}
			map.put(key, pair.value);
		}
		return map;
	}
```

**Comment by robstoll** [comment]
Fair enough, I had a quick glance a the source code of junit5 before I reported the issue and thought it could be a bug in JDK8. I keep the issue open as it seems you want to discuss a few things. Close the issue whenever you want, for me it is done.

**Comment by sbrannen** [comment]
> @junit-team/junit-lambda shall we roll our own toMap helper and always emit the a helpful error message?

SGTM
