### ISSUE TITLE
ParameterizedTests: no conversion is possible for primitive types 

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#1337]
For example,
```
class MyTest {
    @ParameterizedTest
    @ValueSource(bytes = 1)
    void name(int i) {
    }
}
```
fails with
```
Caused by: org.junit.jupiter.params.converter.ArgumentConversionException: No implicit conversion to convert object of type java.lang.Byte to type java.lang.Integer
	at org.junit.jupiter.params.converter.DefaultArgumentConverter.convertToTargetType(DefaultArgumentConverter.java:124)
	at org.junit.jupiter.params.converter.DefaultArgumentConverter.convert(DefaultArgumentConverter.java:93)
	at org.junit.jupiter.params.converter.SimpleArgumentConverter.convert(SimpleArgumentConverter.java:30)
```

though the following code is totally fine 
```
        byte b = 0;
        int i = b;
```

**Comment by marcphilipp** [comment]
@akozlova Thanks for reporting this issue! Adding support for widening conversions is already in progress in #1092. Thus, I'm closing this issue as duplicate.

**Comment by akozlova** [comment]
Sorry, failed to find a duplicate myself :/
