### ISSUE TITLE
ParameterizedTest not playing nice with Collections

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#1452]
@ParameterizedTest
    @ArgumentsSource( PluginProvider.class )
    void codeQuality( Collection<Class<?>> toApply ) {
        Project project = ProjectBuilder.builder().build();
        toApply.forEach( project.getPluginManager()::apply );
        PluginContainer plugins = project.getPlugins();

        assertAll( "plugins",
                () -> assertTrue( plugins.hasPlugin( IdeaPlugin.class ), "idea" ),
                () -> assertTrue( plugins.hasPlugin( SpotBugsPlugin.class ), "spotbugs" ),
                () -> assertTrue( plugins.hasPlugin( ErrorPronePlugin.class ), "errorprone" ),
                () -> assertTrue( plugins.hasPlugin( CheckstylePlugin.class ), "checkstyle" ),
                () -> assertTrue( plugins.hasPlugin( JavaLibraryPlugin.class ), "java" )
        );

        Collection<SourceSet> sourceSets
                = project.getExtensions().getByType( SpotBugsExtension.class ).getSourceSets();

        assertThat( sourceSets ).isNotEmpty();
    }

    class PluginProvider implements ArgumentsProvider {

        @Override
        public Stream<? extends Arguments> provideArguments( ExtensionContext context ) {
            return Stream.of(
                    Collections.singletonList( XenoJavaLibPlugin.class ),
                    Arrays.asList( JavaLibraryPlugin.class, XenoCodeQualityPlugin.class )
            ).map( Arguments::of );
        }
    }

the exception I get is 

```
java.lang.NoSuchMethodException: com.xenoterracide.gradle.plugin.XenoPluginTest$PluginProvider.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:404)
	at org.junit.jupiter.params.ParameterizedTestExtension.lambda$provideTestTemplateInvocationContexts$1(ParameterizedTestExtension.java:70)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:101)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:38)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:113)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:121)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:121)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:121)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:121)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: org.junit.platform.commons.util.PreconditionViolationException: Configuration error: You must provide at least one argument for this @ParameterizedTest
		at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:282)
		at org.junit.jupiter.params.ParameterizedTestExtension.lambda$provideTestTemplateInvocationContexts$7(ParameterizedTestExtension.java:78)
		at java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
		at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
		... 52 more
```

**Comment by marcphilipp** [comment]
Although the error message could be better (could you please create a new issue for that?), the nested class needs to be static. Otherwise, it doesn‘t have a no-argument constructor.

**Comment by thecatwhisperer** [comment]
https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-ArgumentsSource says nothing about the class needing to be static?

**Comment by sbrannen** [comment]
Yes, it that "trick" was supposed to make it appear that the class is a top-level class instead of a static nested class.

In other words, the custom implementation is intended to appear to come from a different source file; however, it would seem that the test method and example implementation appear to come from the same source file in the generated HTML.

So I'll revisit those changes.

**Comment by thecatwhisperer** [comment]
@sbrannen: That make sense, Sorry, the way I read it was that it was a non-static inner class :/  Not enough coffee for me I guess.  I was also trying to use it to inject a spring bean, so probably not the best use-case anyway?

**Comment by sbrannen** [comment]
FYI: I updated the User Guide accordingly.

https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-parameterized-tests-sources-ArgumentsSource

Is that better?

- separate code listing for the custom `ArgumentsProvider` -- note the blank space between the code listing blocks.
- additional sentence stating, "Note that an implementation of `ArgumentsProvider` must be declared as either a top-level class or as a `static` nested class."

**Comment by sbrannen** [comment]
> Sorry, the way I read it was that it was ok to be a non-static inner class :/ 

No worries. The fact that the code listings were merged into a single "listing" in the generated HTML could very easily lead one to believe that the code could literally be written like that (i.e., as a non-static nested class (a.k.a., an _inner_ class).

> Not enough coffee for me I guess. 

Well, if that helps, then.... more ☕️ !

**Comment by sbrannen** [comment]
> I was also trying to use it to inject a spring bean, so probably not the best use-case anyway?

Likely not.

What exactly are you trying to achieve? Perhaps it's best to continue this off-topic discussion on [Gitter](https://gitter.im/junit-team/junit5).

But in any case, you can simply declare an `@Autowired` parameter at the end of your formal parameter list for a `@ParameterizedTest`, and if you're using the `SpringExtension`... Spring will inject it for you from the configured `ApplicationContext`. 😉
