### ISSUE TITLE
Inconsistent output from TreePrinter in ConsoleLauncher with parallel test execution

### ISSUE THREAD

**Issue by littleclay** [junit-team/junit5#1524]
When running all the tests in a few simple test classes with the 1.3.0-M1 ConsoleLauncher standalone jar with the parallel test execution, I am seeing inconsistent output. Sometimes there will be a NullPointerException in the TreePrinter, sometimes it will execute but some of the executed tests will not show up in the tree output (though they are in the final summary), sometimes it will display the ConsoleLauncher help output, and sometimes there is a mix of all of those behaviors. One example is:

```
(aaron) $ java -jar junit-platform-console-standalone-1.3.0-M1.jar --cp tests.jar -p com.foo --config junit.jupiter.execution.parallel.enabled=true --details tree

java.lang.NullPointerException
	at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:54)
	at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:65)
	at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:65)
	at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:65)
	at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:49)
	at org.junit.platform.console.tasks.TreePrintingListener.testPlanExecutionFinished(TreePrintingListener.java:56)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionFinished$7(TestExecutionListenerRegistry.java:102)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:59)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:28)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionFinished(TestExecutionListenerRegistry.java:102)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:155)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:166)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:145)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:92)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.replaceThreadContextClassLoaderAndInvoke(CustomContextClassLoaderExecutor.java:41)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:31)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)

╷
├─ JUnit Jupiter ✔
│  ├─ BarTest ✔
│  │     2018-08-05T09:09:25.959 log = `started class  BarTest`
│  │     2018-08-05T09:09:26.980 log = `finished class BarTest`
│  │  ├─ testBar1(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:25.970 log = `started testBar1(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:26.972 log = `finished testBar1(TestReporter, TestInfo)`
│  │  └─ testBar2(TestReporter, TestInfo) ✔
│  │        2018-08-05T09:09:25.970 log = `started testBar2(TestReporter, TestInfo)`
│  │        2018-08-05T09:09:26.972 log = `finished testBar2(TestReporter, TestInfo)`
│  ├─ BazTest ✔
│  │     2018-08-05T09:09:25.959 log = `started class  BazTest`
│  │     2018-08-05T09:09:28.989 log = `finished class BazTest`
│  │  ├─ testBaz03(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:25.970 log = `started testBaz03(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:26.972 log = `finished testBaz03(TestReporter, TestInfo)`
│  │  ├─ testBaz02(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:25.970 log = `started testBaz02(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:26.972 log = `finished testBaz02(TestReporter, TestInfo)`
│  │  ├─ testBaz01(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:25.970 log = `started testBaz01(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:26.972 log = `finished testBaz01(TestReporter, TestInfo)`
│  │  ├─ testBaz20(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:25.970 log = `started testBaz20(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:26.972 log = `finished testBaz20(TestReporter, TestInfo)`
│  │  ├─ testBaz19(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:26.980 log = `started testBaz19(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:27.985 log = `finished testBaz19(TestReporter, TestInfo)`
│  │  ├─ testBaz08(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:26.980 log = `started testBaz08(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:27.985 log = `finished testBaz08(TestReporter, TestInfo)`
│  │  ├─ testBaz07(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:26.980 log = `started testBaz07(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:27.985 log = `finished testBaz07(TestReporter, TestInfo)`
│  │  ├─ testBaz05(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:26.980 log = `started testBaz05(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:27.985 log = `finished testBaz05(TestReporter, TestInfo)`
│  │  ├─ testBaz04(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:26.980 log = `started testBaz04(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:27.985 log = `finished testBaz04(TestReporter, TestInfo)`
│  │  ├─ testBaz06(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:26.980 log = `started testBaz06(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:27.985 log = `finished testBaz06(TestReporter, TestInfo)`
│  │  ├─ testBaz10(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:26.982 log = `started testBaz10(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:27.985 log = `finished testBaz10(TestReporter, TestInfo)`
│  │  ├─ testBaz09(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:26.982 log = `started testBaz09(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:27.985 log = `finished testBaz09(TestReporter, TestInfo)`
│  │  ├─ testBaz12(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:27.987 log = `started testBaz12(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:28.988 log = `finished testBaz12(TestReporter, TestInfo)`
│  │  ├─ testBaz17(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:27.987 log = `started testBaz17(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:28.988 log = `finished testBaz17(TestReporter, TestInfo)`
│  │  ├─ testBaz13(TestReporter, TestInfo) ✔
│  │  │     2018-08-05T09:09:27.987 log = `started testBaz13(TestReporter, TestInfo)`
│  │  │     2018-08-05T09:09:28.988 log = `finished testBaz13(TestReporter, TestInfo)`
Option                                         Description                                
------                                         -----------                                
-h, --help                                     Display help information.                  
--disable-ansi-colors                          Disable ANSI colors in output (not         
                                                 supported by all terminals).             
--details <[none,summary,flat,tree,verbose]    Select an output details mode for when     
  >                                              tests are executed. Use one of: [none,   

... more following this
```

The test classes are very simple, and here is an example of one of them:

```java
final class BarTest {

    @BeforeAll
    static void setup(TestReporter reporter, TestInfo testInfo) {
        reporter.publishEntry("log", "started class  " + testInfo.getDisplayName());
    }

    @AfterAll
    static void tearDown(TestReporter reporter, TestInfo testInfo) {
        reporter.publishEntry("log", "finished class " + testInfo.getDisplayName());
    }

    @Test
    void testBar1(TestReporter reporter, TestInfo testInfo) throws Exception {
        reporter.publishEntry("log", "started " + testInfo.getDisplayName());
        Thread.sleep(1_000);
        reporter.publishEntry("log", "finished " + testInfo.getDisplayName());
    }

    @Test
    void testBar2(TestReporter reporter, TestInfo testInfo) throws Exception {
        reporter.publishEntry("log", "started " + testInfo.getDisplayName());
        Thread.sleep(1_000);
        reporter.publishEntry("log", "finished " + testInfo.getDisplayName());
    }
}
```

**Comment by sormuras** [comment]
Thanks for the report. Can you please provider the complete source of `tests.jar`? That will help us triage the problem you encountered.

**Comment by sormuras** [comment]
Adding 3 copies of your `BarTest` class to our documentation subproject works like expected.

![image](https://user-images.githubusercontent.com/2319838/43688603-24c399c8-98ec-11e8-9a5e-6d701c397833.png)

Perhaps the `java -jar ...` launcher works differently? Which Java version do you use?

**Comment by sormuras** [comment]
Found another minor issue: report entries that are published by a container context, like the `started class ...` and `finished class ...` messages above, are lacking the vertical bars. Will create a new issue for that.

**Comment by littleclay** [comment]
@sormuras I pushed the sample project to a repository along with a README that has the repro steps and version info for my machine. From the output, I expect it is an issue with parallel test execution and the ConsoleLauncher's TreePrinter.

https://github.com/littleclay/junit5-issues-1524

**Comment by littleclay** [comment]
Example of running the same command twice in a row without any changes to the files or jars, etc:
<img width="962" alt="01" src="https://user-images.githubusercontent.com/14144383/43688709-b9ff41da-98a2-11e8-8b7e-109bfc5e4812.png">
<img width="962" alt="02" src="https://user-images.githubusercontent.com/14144383/43688710-bc679378-98a2-11e8-91f2-cd9052917b5d.png">

**Comment by sormuras** [comment]
Thanks. Will look into it soon.

Which Java version do you use ... on your Mac?

**Comment by littleclay** [comment]
@sormuras I was looking at the code in the TreePrintingListener and am pretty sure I spotted the issue. I made the change and built the standalone console launcher locally and tried to reproduce the bug. With the changes in place I was no longer able to reproduce the inconsistent behavior. I created a fork with the changes and pushed a pull request. This is my first code contribution and I think I got everything needed in there, but please let me know if there are any issues with it. Thanks!

**Comment by marcphilipp** [comment]
@littleclay When I try to build the sample project I get the following output. Any idea what's wrong?

```
bazel build tests_deploy.jar
Unable to find any JVMs matching version "1.8".
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
...............
ERROR: /Users/marc/Desktop/junit5-issues-1524/BUILD:2:1: no such package '@opentest4j//jar': Downloaded file at /private/var/tmp/_bazel_marc/989f1f7b6bb6f8eede2c4d31470673b4/external/opentest4j/org/opentest4j/opentest4j/1.1.0/opentest4j-1.1.0.jar has SHA-1 of c8e2a3e3bc7f3e4bb5075306452db5290f9b117a, does not match expected SHA-1 (6f09c598e9ff64bf0ce2fa7e7de49a99ba83c0b4) and referenced by '//:tests'
ERROR: Analysis of target '//:tests_deploy.jar' failed; build aborted: no such package '@opentest4j//jar': Downloaded file at /private/var/tmp/_bazel_marc/989f1f7b6bb6f8eede2c4d31470673b4/external/opentest4j/org/opentest4j/opentest4j/1.1.0/opentest4j-1.1.0.jar has SHA-1 of c8e2a3e3bc7f3e4bb5075306452db5290f9b117a, does not match expected SHA-1 (6f09c598e9ff64bf0ce2fa7e7de49a99ba83c0b4)
INFO: Elapsed time: 7,357s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (7 packages loaded)
```

**Comment by marcphilipp** [comment]
Hmm, looks like the checksum is wrong.

Fix: https://github.com/littleclay/junit5-issues-1524/pull/2
