### ISSUE TITLE
Vintage + JUnit < 4.5 fails

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1560]
## Overview

Vintage fails to run (here `junit:junit:3.8.1` was used). A `ClassNotFoundException: org.junit.runners.model.RunnerBuilder` is thrown.

```
Aug. 24, 2018 4:04:22 VORM. org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.NoClassDefFoundError: org/junit/runners/model/RunnerBuilder
	at org.junit.vintage.engine.discovery.VintageDiscoverer.<init>(VintageDiscoverer.java:35)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:61)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:133)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:120)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:93)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:97)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:87)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:49)
	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:41)
Caused by: java.lang.ClassNotFoundException: org.junit.runners.model.RunnerBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 13 more
```

All JUnit versions below `4.5` should be affected: [`org.junit.runners.model.RunnerBuilder`](https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/model/RunnerBuilder.java#L41) was introduced in `4.5`

## Deliverables

- [x] Detect JUnit version `< 4.5` early and throw an exception with a better error message, suggesting to update to `4.12`.

**Comment by sbrannen** [comment]
We might be better off requiring JUnit >= 4.12 -- right?

**Comment by sbrannen** [comment]
... Since technically we only actively _support_ JUnit 4.12 at the moment.

**Comment by sbrannen** [comment]
Let's keep in mind that `junit-vintage-engine` has a required transitive dependency on `junit:junit:4.12` in its [pom.xml](https://repo1.maven.org/maven2/org/junit/vintage/junit-vintage-engine/5.2.0/junit-vintage-engine-5.2.0.pom).

Thus if a version of JUnit < 4.12 shows up on the classpath (at least in a build), that would typically be caused by some user error.

**Comment by sormuras** [comment]
> Thus if a version of JUnit < 4.12 shows up on the classpath (at least in a build), that would typically be caused by some user error.

True. The exception occured when a `junit:junit` artifact was found on the classpath and I tried to treat that as an indicator to include and enable the JUnit Vintage engine. Will add `:4.12+` to the indicator.

Providing a better error message would still be good.

**Comment by sbrannen** [comment]
> Will add `:4.12+` to the indicator.

Sounds good.

> Providing a better error message would still be good.

Yep, I agree: better diagnostics == better software, and I added the `diagnostics` label to this issue accordingly. 😉

**Comment by marcphilipp** [comment]
_in progress_
