### ISSUE TITLE
@ResourceLock should be usable on test templates

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#1697]
Using `@ResourceLock` on a `@ParameterizedTest` or `@RepeatedTest` currently yields the following exception:

```
org.junit.platform.commons.JUnitException: Dynamic test descriptors must not declare exclusive resources: [ExclusiveResource [key = 'java.lang.System.properties', lockMode = READ_WRITE]]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeDynamicTest(NodeTestTask.java:128)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$3(NodeTestTask.java:106)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:133)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:101)
	...
```

## Deliverables

- [ ] Make `@ResourceLock` usable on a `@TestTemplate`

**Comment by sbrannen** [comment]
Good catch! 👍
