### ISSUE TITLE
Allow extensions to fail tests

### ISSUE THREAD

**Issue by Frontrider** [junit-team/junit5#1813]
The problem that I have, is that I need to fail all of the tests that took too long. I measured the test's execution time in the `beforeEach` and `afterEach` methods (works well), but when I try to throw the `AssertionFailedError` in the `afterEach` callback nothing happens.
Should be solved by not catching this specific exception from the extensions. Correct me but I do not see a good reason throw this error in an extension, unless you want to modify the results. (I know that a test fails, if an exception is thrown in the `@BeforeEach`/`@AfterEach` methods)

## Deliverables

- [ ] do not catch  `AssertionFailedError`s from extensions

**Comment by sbrannen** [comment]
JUnit Jupiter does not swallow exceptions thrown from an `AfterEachCallback`.

Running the following test class...

```java
package org.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.opentest4j.AssertionFailedError;

@ExtendWith(FailingAfterEachCallback.class)
class AfterEachCallbackFailureTests {

	@Test
	void test() {
		// no-op
	}

}

class FailingAfterEachCallback implements AfterEachCallback {

	@Override
	public void afterEach(ExtensionContext context) throws Exception {
		throw new AssertionFailedError("Boom!");
	}

}
```

... results in the following:

```
org.opentest4j.AssertionFailedError: Boom!
	at org.example.FailingAfterEachCallback.afterEach(AfterEachCallbackFailureTests.java:24)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$13(TestMethodTestDescriptor.java:234)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$14(TestMethodTestDescriptor.java:246)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:244)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:233)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:134)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:1)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$4(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$3(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$4(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$3(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$4(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$3(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$7(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

```

I am therefore closing this as "works as designed".

**Comment by Frontrider** [comment]
Realized the problem. I was running it with the testkit, and that one definitely not work like this. Gonna open a separate issue for that, when I learnt a bit more.

**Comment by sbrannen** [comment]
The `EngineTestKitFailedMethodDemo` class in the [User Guide](https://junit.org/junit5/docs/current/user-guide/#testkit) demonstrates how to verify that a test method failed with an exception.

**Comment by Frontrider** [comment]
That is exactly what I copied, and the exception is missing from the events, and the statistics reports that all tests were successful (all should have failed for that case), even tough I confirmed that the code reached the point where the exception should have been thrown.
Gathering more data.

Running the extension outside the testkit worked (It's a lot easier to use that configuring the environment for it)

**Comment by sbrannen** [comment]
> That is exactly what I copied, 

Is it? Exactly? 😉

**Comment by Frontrider** [comment]
That was the problem in the end that I copied it exactly.

**Comment by sbrannen** [comment]
Related to #1815
