### ISSUE TITLE
Executing pretty small number of dynamic tests (with "large" Executable) results in OutOfMemoryError

### ISSUE THREAD

**Issue by Petikoch** [junit-team/junit5#1865]
JUnit 5.4.1 (Jupiter)

## Steps to reproduce

Run the following test:

```java
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;

import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Stream;

@Execution(ExecutionMode.SAME_THREAD)
class FatExecutablesLeadToOutOfMemoryErrorTest {

    private static final int ONE_MB = 1024 * 1024;
    private static final int TEN_MB = 10 * ONE_MB;
    private static final AtomicInteger testCounter = new AtomicInteger(0);

    @TestFactory
    Stream<DynamicTest> demoTest() {
        int desiredArraySize = TEN_MB;
        return Stream.generate(() -> createByteArray(desiredArraySize))
                .map(bytes ->
                        DynamicTest.dynamicTest(
                                "Test " + testCounter.incrementAndGet(),
                                () -> Assertions.assertEquals(bytes.length, desiredArraySize)
                        )
                )
                .limit(10000L);
    }

    private static byte[] createByteArray(int size) {
        byte[] array = new byte[size];
        ThreadLocalRandom.current().nextBytes(array);
        return array;
    }
}
```
with e.g. `-Xmx=256m`

After around 22 "DynamicTest" instances you get

```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid16732.hprof ...
Heap dump file created [235907219 bytes in 0.095 secs]
Apr 16, 2019 4:09:54 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNUNG: TestEngine with ID 'junit-jupiter' failed to execute tests
org.junit.platform.commons.JUnitException: Error executing tests for engine junit-jupiter
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	... 9 more
Caused by: java.lang.OutOfMemoryError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	... 10 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at FatExecutablesLeadToOutOfMemoryErrorTest.createByteArray(FatExecutablesLeadToOutOfMemoryErrorTest.java:32)
	at FatExecutablesLeadToOutOfMemoryErrorTest.lambda$demoTest$0(FatExecutablesLeadToOutOfMemoryErrorTest.java:21)
	at FatExecutablesLeadToOutOfMemoryErrorTest$$Lambda$217/1223463362.get(Unknown Source)
	at java.util.stream.StreamSpliterators$InfiniteSupplyingSpliterator$OfRef.tryAdvance(StreamSpliterators.java:1356)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$197/89358177.getAsBoolean(Unknown Source)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1(TestFactoryTestDescriptor.java:97)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor$$Lambda$215/1220005704.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod(TestFactoryTestDescriptor.java:88)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$158/545351516.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$157/1020432366.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$156/183820972.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:115)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$158/545351516.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
```

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter
 - Build Tool/IDE: IntelliJ 2018.3.6 Community Edition

**Comment by Petikoch** [comment]
![Screenshot](https://user-images.githubusercontent.com/9936866/56217334-5a07cc00-6063-11e9-9160-483aa91b6cdc.PNG)

**Comment by Petikoch** [comment]
![Screenshot2](https://user-images.githubusercontent.com/9936866/56217406-76a40400-6063-11e9-93be-474282228202.PNG)

**Comment by Petikoch** [comment]
I guess this happens because `DynamicTest` keeps a reference to the `Executable`. In our case the  `Executable` is quit large.

**Comment by Petikoch** [comment]
Workaround:

```
    private static class ReleaseingAfterExecuteExecutable implements Executable {

        private final AtomicReference<Executable> delegateRef = new AtomicReference<>();

        public ReleaseingAfterExecuteExecutable(Executable delegate) {
            this.delegateRef.set(delegate);
        }

        @Override
        public void execute() throws Throwable {
            try {
                delegateRef.get().execute();
            } finally {
                delegateRef.set(null);
            }
        }
    }
```

applied:

```
    @TestFactory
    Stream<DynamicTest> demoTest() {
        int desiredArraySize = TEN_MB;
        return Stream.generate(() -> createByteArray(desiredArraySize))
                .map(bytes ->
                        DynamicTest.dynamicTest(
                                "Test " + testCounter.incrementAndGet(),
                                new ReleaseingAfterExecuteExecutable(
                                        () -> Assertions.assertEquals(bytes.length, desiredArraySize)
                                )
                        )
                )
                .limit(10000L);
    }
```

**Comment by sbrannen** [comment]
Thanks for raising the issue.

We'll look into it.

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M2 for _team discussion_

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
I already have a local fix that I'll push to `master` soon...

**Comment by sbrannen** [comment]
This has been fixed in `master` in commit 156cd36c07adfe922fdace238bd81e8ae0c698cc and will be available in the next 5.5 snapshot build.

Feel free to try it out once that build has been published.

**Comment by Petikoch** [comment]
Excellent, thanks a lot @sbrannen !

**Comment by sbrannen** [comment]
You're welcome!
