### ISSUE TITLE
Setting default display name generator throws exception

### ISSUE THREAD

**Issue by gabriel-ntuc** [junit-team/junit5#1928]
## Steps to reproduce

1. Clone or set up JUnit 5 project (I used the official junit5-samples/junit5-jupiter-starter-gradle but I have been able to reliably reproduce this across different projects)
2. Create `src/test/resources/junit-platform.properties` with following setting:
```
junit.jupiter.displayname.generator.default = \
    org.junit.jupiter.api.DisplayNameGenerator.ReplaceUnderscores
```

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.5.0-RC1
 - Build Tool/IDE: Intellij IDEA 2019.1.3 CE
- build.gradle (see below)
```
plugins {
	id 'java'
	id 'eclipse' // optional (to generate Eclipse project files)
	id 'idea' // optional (to generate IntelliJ IDEA project files)
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation('org.junit.jupiter:junit-jupiter:5.5.0-RC1')
}

test {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
	}
}
```

## Output

```
Jun 13, 2019 2:43:16 PM org.junit.jupiter.engine.config.DisplayNameGeneratorParameterConverter logFailureMessage
WARNING: Failed to load default display name generator class 'org.junit.jupiter.api.DisplayNameGenerator.ReplaceUnderscores' set via the 'junit.jupiter.displayname.generator.default' configuration parameter. Falling back to default behavior.
java.lang.ClassNotFoundException: org.junit.jupiter.api.DisplayNameGenerator.ReplaceUnderscores
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:779)
	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
	at org.junit.platform.commons.function.Try.of(Try.java:93)
	at org.junit.platform.commons.function.Try.call(Try.java:57)
	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:742)
	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:698)
	at org.junit.jupiter.engine.config.DisplayNameGeneratorParameterConverter.instantiateGenerator(DisplayNameGeneratorParameterConverter.java:42)
	at org.junit.jupiter.engine.config.DisplayNameGeneratorParameterConverter.lambda$get$1(DisplayNameGeneratorParameterConverter.java:35)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.junit.jupiter.engine.config.DisplayNameGeneratorParameterConverter.get(DisplayNameGeneratorParameterConverter.java:35)
	at org.junit.jupiter.engine.config.DefaultJupiterConfiguration.getDefaultDisplayNameGenerator(DefaultJupiterConfiguration.java:92)
	at org.junit.jupiter.engine.config.CachingJupiterConfiguration.lambda$getDefaultDisplayNameGenerator$6(CachingJupiterConfiguration.java:85)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.junit.jupiter.engine.config.CachingJupiterConfiguration.getDefaultDisplayNameGenerator(CachingJupiterConfiguration.java:84)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.getDisplayNameGenerator(DisplayNameUtils.java:104)
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.lambda$createDisplayNameSupplierForClass$2(DisplayNameUtils.java:81)
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.determineDisplayName(DisplayNameUtils.java:71)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.<init>(JupiterTestDescriptor.java:69)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.<init>(ClassBasedTestDescriptor.java:91)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.<init>(ClassTestDescriptor.java:47)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.newClassTestDescriptor(ClassSelectorResolver.java:110)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$resolve$0(ClassSelectorResolver.java:70)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.createAndAdd(EngineDiscoveryRequestResolution.java:249)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:212)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:70)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:129)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
```

**Comment by sormuras** [comment]
Use `$` to separate a static nested class from a top-level class:

`org.junit.jupiter.api.DisplayNameGenerator$ReplaceUnderscores`

**Comment by gabriel-ntuc** [comment]
@sormuras Thanks that worked. I suggest that the documentation be updated as well because the example that is documented does not use the dollar sign.

**Comment by sormuras** [comment]
Good catch!

Will update https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-display-name-generator-default soon.
