### ISSUE TITLE
NoSuchMethodError when using example setup from junit5-maven-consumer

### ISSUE THREAD

**Issue by UrsMetz** [junit-team/junit5#196]
The current SNAPSHOT version of `surefire-junit5` causes the Maven build of the example project [junit5-maven-consumer](https://github.com/junit-team/junit5-samples/tree/master/junit5-maven-consumer) to fail with a NoSuchMethodError:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project git-svn-remote-updates-checker: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test failed: There was an error in the forked process
[ERROR] java.lang.NoSuchMethodError: org.junit.gen5.commons.util.StringUtils.join(Ljava/util/stream/Stream;Ljava/lang/String;)Ljava/lang/String;
[ERROR] at org.junit.gen5.engine.UniqueIdFormat.format(UniqueIdFormat.java:82)
[ERROR] at org.junit.gen5.engine.UniqueId.getUniqueString(UniqueId.java:69)
[ERROR] at org.junit.gen5.engine.junit4.JUnit4TestEngine.discover(JUnit4TestEngine.java:43)
[ERROR] at org.junit.gen5.launcher.main.DefaultLauncher.discoverRoot(DefaultLauncher.java:88)
[ERROR] at org.junit.gen5.launcher.main.DefaultLauncher.discover(DefaultLauncher.java:65)
[ERROR] at org.junit.gen5.surefire.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:34)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:98)
[ERROR] at org.junit.gen5.surefire.JUnitGen5Provider.scanClasspath(JUnitGen5Provider.java:61)
[ERROR] at org.junit.gen5.surefire.JUnitGen5Provider.invoke(JUnitGen5Provider.java:56)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

When replacing the `surefire-junit5` with the ALPHA release the Maven build passes.

**Comment by UrsMetz** [comment]
I guess the cause of the issue is that the classpath of the surefire run contains a mixture of ALPHA and SNAPSHOT versions of the different junit5 JARs. I couldn't really verify this but running `mvn -X clean verify` gives me the following information concerning the surefire classpath:
```
[DEBUG] boot(compact) classpath:  surefire-booter-2.19.jar  surefire-api-2.19.jar  test-classes  classes  junit5-api-5.0.0-ALPHA.jar  opentest4j-1.0.0-ALPHA.jar  junit-commons-5.0.0-ALPHA.jar  junit-4.12.jar  hamcrest-core-1.3.jar  surefire-junit5-5.0.0-SNAPSHOT.jar  junit-launcher-5.0.0-SNAPSHOT.jar  junit-engine-api-5.0.0-SNAPSHOT.jar  junit-commons-5.0.0-SNAPSHOT.jar  junit4-engine-5.0.0-SNAPSHOT.jar  junit5-engine-5.0.0-SNAPSHOT.jar  junit5-api-5.0.0-SNAPSHOT.jar  common-java5-2.19.jar  maven-reporting-api-3.0.jar
```

**Comment by marcphilipp** [comment]
Thanks for the report! :+1: 

I guess using the Surefire plugin snapshot along with the alpha API was asking for trouble. I changed the sample project to use the latest junit5-api snapshot JAR instead. At least this was finally a trigger I got junit-team/junit5-samples#2 done. :-)

**Comment by UrsMetz** [comment]
@marcphilipp did you mean to change to ALPHA JARs? I ask because in junit-team/junit5-samples@a78a50f this is done or was this by mistake (as the commit message also talks about snapshot)?

**Comment by marcphilipp** [comment]
Oops, no, I meant the opposite. I'll fix it later.

**Comment by marcphilipp** [comment]
Ok, fixed now. Thanks a bunch!

**Comment by sbrannen** [comment]
Thanks, Marc!
