### ISSUE TITLE
TempDir fails when it faces a read-only file in Windows

### ISSUE THREAD

**Issue by vlsi** [junit-team/junit5#2046]
## Steps to reproduce

```java
@Test
public void testWriteToFileIOException(@TempDir Path tempDir) throws Exception {
    Path f = tempDir.resolve("test.txt");
    Files.write(f, new byte[0]);
    Assertions.assertTrue(f.toFile().setWritable(false), () -> f + ".toFile().setWritable(false) should succeed");
}
```

The exception is similar to the following:

```
org.apache.jmeter.functions.TestStringtoFile > testWriteToFileIOException(Path) STANDARD_ERROR
    Oct 06, 2019 3:06:02 PM org.junit.jupiter.engine.execution.JupiterEngineExecutionContext close
    SEVERE: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@23c1d81a
    java.io.IOException: Failed to delete temp directory C:\Users\jenkins\AppData\Local\Temp\2\junit4877224876769494483. The following paths could not be deleted (see suppressed exceptions for details): , output.txt
    	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:211)
    	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:168)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:61)
    	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:73)
    	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
    	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
    	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:57)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:151)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:151)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:83)
    	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
    	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:141)
    	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:121)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
    	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:141)
    	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:121)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
    	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
    	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    	Suppressed: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\AppData\Local\Temp\2\junit4877224876769494483
    		at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266)
    		at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
    		at java.nio.file.Files.delete(Files.java:1126)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:192)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:187)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:178)
    		at java.nio.file.Files.walkFileTree(Files.java:2688)
    		at java.nio.file.Files.walkFileTree(Files.java:2742)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:178)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:166)
    		... 38 more
    	Suppressed: java.nio.file.AccessDeniedException: C:\Users\jenkins\AppData\Local\Temp\2\junit4877224876769494483\output.txt
    		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
    		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
    		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
    		at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
    		at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
    		at java.nio.file.Files.delete(Files.java:1126)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:192)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.visitFile(TempDirectory.java:182)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.visitFile(TempDirectory.java:178)
    		at java.nio.file.Files.walkFileTree(Files.java:2670)
    		at java.nio.file.Files.walkFileTree(Files.java:2742)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:178)
    		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:166)
    		... 38 more
```

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.5.1
 - Build Tool/IDE: Gradle

This might be relevant: https://stackoverflow.com/a/32955993/1261287

**Comment by marcphilipp** [comment]
Good catch! Would you be interested in submitting a PR?

**Comment by sormuras** [comment]
Calling `File#setWritable(true)` on all files before deleting them?

What if [ACL's](https://github.com/sormuras/bach/blob/d891bd5c32be282ff5f259267041f366bdd40c72/deprecated/src-20190228/test/Util.java#L15-L55) are used to prevent access to files within the temporary directory?

A solution could be to just log a warning when a temporary could not be deleted, instead of the entire stack trace.

**Comment by vlsi** [comment]
My immediate thought was `File#setWritable`, however `Path -> File` conversion might take time.

So it should probably be guarded with `Files#isWritable(Path)`.
Then I'm not sure what to do. Either try the new shiny `java.nio.file.Files#getFileAttributeView` (which should probably support ACL) or resort to an old `File.setWritable`.

Frankly speaking, I've no much experience in that area and I just hoped you have much more.

>A solution could be to just log a warning when a temporary could not be deleted, instead of the entire stack trace.

The stacktrace does not really hurt in my opinion.

PS. What do you think of making one more talk for Heisenbug? :)

**Comment by vlsi** [comment]
> Calling File#setWritable(true) on all files before deleting them?

Did you mean to call `setWritable` in case the delete fails?

**Comment by marcphilipp** [comment]
I think it should attempt to delete "undeletable" files if the initial delete fails. If we need to convert `Path` to `File` for that I think that would be ok.

**Comment by jbduncan** [comment]
The implementor would need to remember to catch the potential exception thrown by `Path::toFile` though, in case the user of the extension decided to use e.g. JimFS rather than the on-disk filesystem. :)

**Comment by vlsi** [comment]
> I think it should attempt to delete "undeletable" files if the initial delete fails

I agree. The test might fail in the middle (e.g. after creating a read-only file), so it would be nice if the framework tries to use set writable.

>If we need to convert Path to File for that I think that would be ok.

Performance-wise it would be ok. However, I'm not sure File could handle ACLs. On the other hand, dealing with ACLs should probably be postponed until someone manages to craft that test case.
