### ISSUE TITLE
Revise module declarations

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2063]
Revise module declarations for wrong, unnecessary and superfluous directives and modifiers.

Related issue: #1939 

## Deliverables
- [x] Check if `transitive` is really needed for each `requires` directive that declares it
- [x] All internal packages are hidden, i.e. not exported
- [x] All modules are `required` explicitly when an exported package is used directly

**Comment by sormuras** [comment]
Module `org.junit.platform.engine` does **not** export package `org.junit.platform.engine.support.filter`  - although it contains the published `ClasspathScanningSupport` class. That class, deprecated, is used by 3rd-party engines. Like: https://github.com/testng-team/testng-junit5/blob/master/src/main/java/org/testng/junit5/TestNGine.java#L3

We should export the package in the upcoming 5.6 release.

**Comment by sormuras** [comment]
#### Is `transitive` needed for `requires transitive org.apiguardian.api;`?

Yes. E.g `org.apiguardian.api.API` is part of "all" JUnit 5 API and it is annotated with `@Retention(RUNTIME)` -- so it leaks to all downstream modules.

#### Is `transitive` needed for `requires transitive org.opentest4j;`?

Yes. E.g. `Assertions.assertAll(...) throws org.opentest4j.MultipleFailuresError`

**Comment by sormuras** [comment]
### org.junit.jupiter
```
org.junit.jupiter (junit-jupiter-5.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires transitive org.junit.jupiter.api;
    requires transitive org.junit.jupiter.engine;
    requires transitive org.junit.jupiter.params;
  [Suggested module descriptor for org.junit.jupiter]
    requires mandated java.base;
  [Transitive reduced graph for org.junit.jupiter]
    requires mandated java.base;
    requires org.junit.jupiter.engine;
    requires org.junit.jupiter.params;
```

**Comment by sormuras** [comment]
### org.junit.jupiter.api

```
org.junit.jupiter.api (file:///home/runner/work/JDK-8225773/JDK-8225773/lib/junit-jupiter-api-5.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.junit.platform.commons;
    requires transitive org.opentest4j (@1.2.0);
  [Suggested module descriptor for org.junit.jupiter.api]
    requires mandated java.base;
    requires transitive org.apiguardian.api;
    requires transitive org.junit.platform.commons;
    requires transitive org.opentest4j;
    requires transitive unnamed;
java.lang.NullPointerException
	at jdk.jdeps/com.sun.tools.jdeps.ModuleGraphBuilder.requiresTransitive(ModuleGraphBuilder.java:124)
```
https://github.com/sormuras/JDK-8225773/runs/354396322#step:4:166

**Comment by sormuras** [comment]
### org.junit.jupiter.engine

```
org.junit.jupiter.engine (junit-jupiter-engine-5.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.junit.jupiter.api;
    requires transitive org.junit.platform.engine;
    requires transitive org.opentest4j (@1.2.0);
  [Suggested module descriptor for org.junit.jupiter.engine]
    requires mandated java.base;
    requires org.apiguardian.api;
    requires org.junit.jupiter.api;
    requires org.junit.platform.commons;
    requires org.junit.platform.engine;
    requires org.opentest4j;
  [Transitive reduced graph for org.junit.jupiter.engine]
    requires mandated java.base;
    requires org.junit.jupiter.api;
    requires org.junit.platform.engine;
```

**Comment by sormuras** [comment]
### org.junit.jupiter.params

```
org.junit.jupiter.params (file:///home/runner/work/JDK-8225773/JDK-8225773/lib/junit-jupiter-params-5.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.junit.jupiter.api;
  [Suggested module descriptor for org.junit.jupiter.params]
    requires mandated java.base;
    requires java.sql;
    requires transitive org.apiguardian.api;
    requires transitive org.junit.jupiter.api;
    requires transitive org.junit.platform.commons;
    requires unnamed;
java.lang.NullPointerException
	at jdk.jdeps/com.sun.tools.jdeps.ModuleGraphBuilder.requiresTransitive(ModuleGraphBuilder.java:124)
```
https://github.com/sormuras/JDK-8225773/runs/354396352#step:4:62

**Comment by sormuras** [comment]
### org.junit.platform.commons

```
org.junit.platform.commons (junit-platform-commons-1.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires java.logging;
    requires java.management;
    requires transitive org.apiguardian.api (@1.1.0);
  [Suggested module descriptor for org.junit.platform.commons]
    requires mandated java.base;
    requires java.logging;
    requires transitive org.apiguardian.api;
  [Transitive reduced graph for org.junit.platform.commons]
    requires mandated java.base;
    requires java.logging;
    requires transitive org.apiguardian.api;
  [Unused qualified exports in org.junit.platform.commons]
    exports org.junit.platform.commons.logging to org.junit.jupiter.migrationsupport,org.junit.jupiter.params,org.junit.platform.console,org.junit.platform.reporting,org.junit.platform.runner,org.junit.platform.suite.api
    exports org.junit.platform.commons.util to org.junit.platform.suite.api
```

**Comment by sormuras** [comment]
### org.junit.platform.console
- `1.5.2` **NPE** https://github.com/sormuras/JDK-8225773/runs/354353926#step:4:52
- `1.6.0-M1` works (but why?) -- see result below:
```
org.junit.platform.console (junit-platform-console-1.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.junit.platform.reporting;
  [Suggested module descriptor for org.junit.platform.console]
    requires mandated java.base;
    requires org.apiguardian.api;
    requires org.junit.platform.commons;
    requires org.junit.platform.engine;
    requires org.junit.platform.launcher;
    requires org.junit.platform.reporting;
  [Transitive reduced graph for org.junit.platform.console]
    requires mandated java.base;
    requires org.junit.platform.reporting;
```

**Comment by sormuras** [comment]
### org.junit.platform.engine
```
org.junit.platform.engine (junit-platform-engine-1.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.junit.platform.commons;
    requires transitive org.opentest4j (@1.2.0);
  [Suggested module descriptor for org.junit.platform.engine]
    requires mandated java.base;
    requires transitive org.apiguardian.api;
    requires transitive org.junit.platform.commons;
    requires transitive org.opentest4j;
  [Transitive reduced graph for org.junit.platform.engine]
    requires mandated java.base;
    requires transitive org.apiguardian.api;
    requires transitive org.junit.platform.commons;
    requires transitive org.opentest4j;
```

**Comment by sormuras** [comment]
### org.junit.platform.launcher
```
org.junit.platform.launcher (junit-platform-launcher-1.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires java.logging;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.junit.platform.engine;
  [Suggested module descriptor for org.junit.platform.launcher]
    requires mandated java.base;
    requires transitive java.logging;
    requires transitive org.apiguardian.api;
    requires transitive org.junit.platform.commons;
    requires transitive org.junit.platform.engine;
  [Transitive reduced graph for org.junit.platform.launcher]
    requires mandated java.base;
    requires transitive java.logging;
    requires transitive org.apiguardian.api;
    requires transitive org.junit.platform.commons;
    requires transitive org.junit.platform.engine;
```

**Comment by sormuras** [comment]
### org.junit.platform.reporting
```
org.junit.platform.reporting (junit-platform-reporting-1.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires java.xml;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.junit.platform.launcher;
  [Suggested module descriptor for org.junit.platform.reporting]
    requires mandated java.base;
    requires java.xml;
    requires org.apiguardian.api;
    requires org.junit.platform.commons;
    requires transitive org.junit.platform.engine;
    requires transitive org.junit.platform.launcher;
  [Transitive reduced graph for org.junit.platform.reporting]
    requires mandated java.base;
    requires java.xml;
    requires transitive org.junit.platform.engine;
    requires transitive org.junit.platform.launcher;
```

**Comment by sormuras** [comment]
### org.junit.platform.suite.api
```
org.junit.platform.suite.api (junit-platform-suite-api-1.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires transitive org.apiguardian.api (@1.1.0);
  [Suggested module descriptor for org.junit.platform.suite.api]
    requires mandated java.base;
    requires org.apiguardian.api;
  [Transitive reduced graph for org.junit.platform.suite.api]
    requires mandated java.base;
    requires org.apiguardian.api;
```

**Comment by sormuras** [comment]
### org.junit.platform.testkit
```
org.junit.platform.testkit (junit-platform-testkit-1.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires java.instrument;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.assertj.core;
    requires transitive org.junit.platform.launcher;
    requires transitive org.opentest4j (@1.2.0);
  [Suggested module descriptor for org.junit.platform.testkit]
    requires mandated java.base;
    requires transitive org.apiguardian.api;
    requires transitive org.assertj.core;
    requires org.junit.platform.commons;
    requires transitive org.junit.platform.engine;
    requires org.junit.platform.launcher;
    requires org.opentest4j;
  [Transitive reduced graph for org.junit.platform.testkit]
    requires mandated java.base;
    requires transitive org.apiguardian.api;
    requires transitive org.assertj.core;
    requires transitive org.junit.platform.engine;
    requires org.junit.platform.launcher;
```

**Comment by sormuras** [comment]
_I always forget this one... now, I can't sort into the other Jupiter modules above. 😈_

### org.junit.jupiter.migrationsupport
```
org.junit.jupiter.migrationsupport (file:///home/runner/work/JDK-8225773/JDK-8225773/lib/junit-jupiter-migrationsupport-5.6.0-M1.jar)
  [Module descriptor]
    requires mandated java.base;
    requires transitive junit;
    requires transitive org.apiguardian.api (@1.1.0);
    requires transitive org.junit.jupiter.api;
  [Suggested module descriptor for org.junit.jupiter.migrationsupport]
    requires mandated java.base;
    requires transitive junit;
    requires org.apiguardian.api;
    requires transitive org.junit.jupiter.api;
    requires org.junit.platform.commons;
  [Transitive reduced graph for org.junit.jupiter.migrationsupport]
    requires mandated java.base;
    requires transitive junit;
    requires transitive org.junit.jupiter.api;
```

**Comment by marcphilipp** [comment]
"Suggested module descriptors" LGTM.
