### ISSUE TITLE
JUnit and Surefire are calling JUnit3 static suite() method twice

### ISSUE THREAD

**Issue by k1w1m8** [junit-team/junit5#2091]
I am using JUnit 5.5.1 and Surefire 2.22.2.

I noticed that Surefire is calling my JUnit3 static suite() method twice.

This is an issue for me as my suite() method is creating tests dynamically and it is expensive.

I dumped a stacktrace inside Surefire for each and noticed some differences.

From the two calls, we can see the section of the stack trace in the whitespace (inside surefire) is different.

```java
	at com.clear2pay.jetqarun.junit3.JUnit3Suite.suite(JUnit3Suite.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
	at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
	at org.junit.internal.builders.SuiteMethodBuilder.runnerForClass(SuiteMethodBuilder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder.runnerForClass(DefensiveAllDefaultPossibilitiesBuilder.java:56)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolveTestClass(ClassSelectorResolver.java:66)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:47)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:129)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:174)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:120)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:87)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:80)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:112)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:42)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:62)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:177)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:164)

	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:120)
	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:102)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:143)
	
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

```java
	at com.clear2pay.jetqarun.junit3.JUnit3Suite.suite(JUnit3Suite.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
	at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
	at org.junit.internal.builders.SuiteMethodBuilder.runnerForClass(SuiteMethodBuilder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder.runnerForClass(DefensiveAllDefaultPossibilitiesBuilder.java:56)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolveTestClass(ClassSelectorResolver.java:66)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:47)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:129)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:174)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:120)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:87)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:80)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:112)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:42)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:62)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:177)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:164)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

In JUnitPlatformProvider, we can see

```java
else if ( forkTestSet == null )
            {
                invokeAllTests( scanClasspath(), runListener );
            }
```

This one line of code is calling suite() twice, once from scanClasspath, and once from invokeAllTests.

Is it possible to tell from the stack trace if this is a JUnit issue or Surefire issue?

To me it sounds like a JUnit issue as "discover" should find the suite() method, not call it. But I could easily be wrong...

**Comment by k1w1m8** [comment]
For reference, same thing run without JUnit5 only in the classpath gives:

```java
	at com.clear2pay.jetqarun.junit3.JUnit3Suite.suite(JUnit3Suite.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
	at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
	at org.junit.internal.builders.SuiteMethodBuilder.runnerForClass(SuiteMethodBuilder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:362)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by marcphilipp** [comment]
That's because Surefire first calls `Launcher.discover()` in [`TestPlanScannerFilter`](https://github.com/apache/maven-surefire/blob/c391947070c9514c1d3a5ba45762329d0beb0f39/surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/TestPlanScannerFilter.java#L56) and later calls `Launcher.execute()` with another `LauncherDiscoveryRequest` in [`JUnitPlatformProvider`](https://github.com/apache/maven-surefire/blob/c391947070c9514c1d3a5ba45762329d0beb0f39/surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java#L165).

@Tibor17 Is the `ScannerFilter` absolutely necessary? What would happen if it accepted all test classes and only passed the filters in the `LauncherDiscoveryRequest` passed to `Launcher.execute()`?

**Comment by Tibor17** [comment]
@k1w1m8 
@marcphilipp 
Maximum what we can do now in the short time before the release is to perform some optimizations. 
so that we skip this lookup while no groups/categories are configured.

Till now we have reworked the interprocess communication and we made it extensible with more new commands/events in the future. This will be the base line for the next bug fixes like this one. So my idea is to `filter and run the class in the JVM where it belongs to` and therefore only once. This of course requires flexible communication between proceses and therefore we were working on the changes in the internal code in the version 3.0.0-M4. In the next version we will utilize our work so that it will be visible for our users because we will fix similar issues.

**Comment by sormuras** [comment]
> This is an issue for me as my suite() method is creating tests dynamically and it is expensive.

Is it possible to cache the generated tests within the `suite()` method and guard it against multiple calls?

**Comment by marcphilipp** [comment]
@Tibor17 Thanks for the quick response! Shall @k1w1m8 open an issue in Surefire's Jira to track this?

**Comment by Tibor17** [comment]
@marcphilipp 
@k1w1m8 
That's not necessary because we already have it in our Jira.

**Comment by marcphilipp** [comment]
@Tibor17 Could you add a link here for future reference, please?

**Comment by k1w1m8** [comment]
All, thanks for the express replies. I appreciate the effort you are all putting in.

@sormuras my first thought was to add a static to cache the generated tests but it did not seem to make a difference. I guess there is classloader stuff going on in there?

@Tibor17 I did try and search up any existing tickets for surefire, but I didn't find any. Maybe I could have looked harder ;-). I just now looked in SUREFIRE jira and couldn't find any defect that looked obviously related, but surely I could still have missed something.

To give some background, I am using dynamic containers/tests and have it implemented both with JUnit3 and JUnit5 APIs so we can choose the most appropriate for the situation (for local testing in IDEA using JUnit5 gives some real benefits; for CI in Jenkins we always using JUnit3 as the Surefire / Dynamic Test / JUnit5 reporting is not really usable as yet... I'm hoping with 3.0.0-M4 we can try again). 

So anyway, previously I had implemented both JUnit3 and JUnit5 dynamic test APIs in the same jar with JUnit5 dependencies. Now this defect has encouraged me to split those into separate per version jars so that if users select only the JUnit3 API version then can have only JUnit4 dependencies and therefore do not pick up the JUnit5 vintage API. This is a better setup in any case. Therefore I am not waiting on a fix for this issue.

**Comment by Tibor17** [comment]
@k1w1m8 
I really don't know what you mean in your problem with combining junit3+5, dynamic tests, reports, etc. Don't write explanation in comments, it is not productive. I need to see sample project in GitHub, check your project by my hands, execute the commands, see the details, etc. Then it will be productive.

**Comment by Tibor17** [comment]
@k1w1m8 
Do you have this approach in you code?
```
    public static class Suite
    {

        public static Test suite()
        {
            TestSuite suite = new TestSuite();
            suite.addTestSuite( MyTest.class );
            return suite;
        }
    }
```
I don't see any option how to help you because the JUnit3 calls `test= constructor.newInstance(new Object[0]);` and instantiates the test. I don't think that JUnit5 architecture will reuse given instances from outside. They need classes.
So, can you upgrade from JUnit3?

**Comment by k1w1m8** [comment]
Hey @Tibor17, I am am creating my tests dynamically and I have two implementations, using either new TestCase() for JUnit3 or DynamicTest for JUnit5. When using the JUnit3 implementation, it runs fine using JUnit4 dependencies, I don't need to use Vintage to run them. So I have a workaround. 

So since I have a workaround, this fix for me is not urgent.

I'll leave it up to you to decide whatever priority you see fit.

**Comment by Tibor17** [comment]
Usually, when we are talking about issues in the Apache, we wan to see the executable project.
Can you post some? You can use the [Gist](https://gist.github.com/).

**Comment by marcphilipp** [comment]
@k1w1m8 Please create a reproducer and open an issue on Surefire's Jira.

**Comment by Tibor17** [comment]
@marcphilipp 
As you can see it is not related to Surefire nothing but JUnit3. And serious investigation in a PR requires having a reproducible project and then closing the PR but not opposite.

**Comment by marcphilipp** [comment]
As I explained above, it's caused by Surefire executing test discovery twice:
https://github.com/junit-team/junit5/issues/2091#issuecomment-548737137

Therefore, it's impossible to fix it in this repo, case closed.

**Comment by Tibor17** [comment]
@marcphilipp 
JUnit3 was confirmed https://github.com/junit-team/junit5/issues/2091#issuecomment-549154679 that instantiates the class twice and I said that anything can be optimized or workarounded https://github.com/junit-team/junit5/issues/2091#issuecomment-548742218 but it is not a solution.

But we do not know yet if `launcher.discover()` instanciates dynamic non-JUnit3 test because you was not debuging it. This part should not instantiate the test in JUnit5, it should still operate with sort of class. But again how do you know that JUnit5 instantiates the class in source discovery.

I doubt about such behavior in JUnit5 since I believe the team wrote the Surefire code correctly in Surefire as it was adopted from JUnit5:

```
    @Override
    @SuppressWarnings( "rawtypes" )
    public boolean accept( Class testClass )
    {
        LauncherDiscoveryRequest discoveryRequest = request()
                        .selectors( selectClass( testClass.getName() ) )
                        .filters( includeAndExcludeFilters ).build();

        TestPlan testPlan = launcher.discover( discoveryRequest );

        return testPlan.containsTests();
    }
```

First we have to debug this part of code and optimizations are another topic and another type of JIRA ticket. sice optimizations are a kind of workarounds and don't always remove bad behavior completely.

**Comment by marcphilipp** [comment]
The `suite()` method is called when the JUnit 4 Runner is instantiated. This will be done when you call `Launcher.discover()` or `Launcher.execute(LauncherDiscoveryRequest)`.

If the above filter has to stay in place, those methods will both get called and the `suite()` method will get called twice. If the filter could be removed, i.e. the provider would not filter any classes, and the complete list of classes would be passed to `Launcher.execute(LauncherDiscoveryRequest)` which would then only report events for actual test classes the problem would be solved. However, I'm not sure how Surefire would handle that which is what I asked you [in my comment](https://github.com/junit-team/junit5/issues/2091#issuecomment-548737137) above.
