### ISSUE TITLE
JUnit 5 can't find test units when called from Gradle

### ISSUE THREAD

**Issue by niamster** [junit-team/junit5#2123]
Affected versions:
- Junit version: `5.5.2`
- Gradle  version: `6.0`

Working versions:
- Junit version: `5.3.2`
- Gradle  version: `6.0`

## Steps to reproduce

Run `gradle test`.

Sample `build.gradle`:

```
test {
    useJUnitPlatform {
        includeEngines "junit-jupiter"
        excludeEngines "junit-vintage"
    }
    testLogging {
        events "passed", "skipped", "failed"
    }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.5.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.5.2")
}
```

When executed in `debug` mode following error appears:
```
2019-12-09T00:58:03.573+0100 [DEBUG] [TestEventLogger] Gradle Test Executor 14 STANDARD_ERROR
2019-12-09T00:58:03.573+0100 [DEBUG] [TestEventLogger]     Dec 09, 2019 12:58:03 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
2019-12-09T00:58:03.573+0100 [DEBUG] [TestEventLogger]     WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
2019-12-09T00:58:03.573+0100 [DEBUG] [TestEventLogger]     java.lang.NoClassDefFoundError: org/junit/platform/engine/support/discovery/SelectorResolver
2019-12-09T00:58:03.574+0100 [DEBUG] [TestEventLogger]          at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
```

## Context

 - Used versions (Jupiter/Vintage/Platform): `5.5.2`
 - Build Tool/IDE: `Gradle`

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
What happens if you add the following dependency?

```groovy
testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.5.2")
```

**Comment by niamster** [comment]
Thanks @sbrannen for your prompt reply.
When I add the suggested dependency the test suite fails with the following exception:

```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 1.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoClassDefFoundError: org/junit/platform/commons/PreconditionViolationException
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.createLauncherDiscoveryRequest(JUnitPlatformTestClassProcessor.java:121)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.access$500(JUnitPlatformTestClassProcessor.java:54)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 25 more
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.PreconditionViolationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 31 more
```

Please let me know if I can provide any further information.

**Comment by marcphilipp** [comment]
@niamster That's not the complete project, is it? Are you using Spring Boot's Gradle plugin by any chance? Can you share a [build scan](https://scans.gradle.com/) with us?

**Comment by niamster** [comment]
Hey @marcphilipp 
Yes, it's a new [project](https://github.com/niamster/chezz/tree/master/api) which I use to learn `java` and `spring`.
 Sure, you can find the scan [here](https://scans.gradle.com/s/v2ws2abeyltce) with `5.5.2` version of `junit`.

**Comment by marcphilipp** [comment]
As you can [see in the scan](https://scans.gradle.com/s/v2ws2abeyltce/dependencies?dependencies=org.junit.platform&expandAll&focusedDependency=WzAsNDIsMjk4LFswLDAsWzBdXV0), the JUnit Platform dependency is downgraded by the `io.spring.dependency-management` plugin. You'll need to use the [plugin's mechanism to override the version](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/gradle-plugin/reference/html/#managing-dependencies-customizing):

```gradle
ext['junit-jupiter.version'] = '5.5.2'
```

**Comment by niamster** [comment]
Thanks a lot @marcphilipp. This worked

**Comment by arturmkr** [comment]
@marcphilipp , looks like I am having the similar issue:
https://github.com/arturmkr/myReportProblem

Could you please help, what could be the problem?

When I try to execute code I am having issue:

```
./gradlew clean ui:test 

> Task :ui:test FAILED

com.db.demo.ui.DummyCheck > initializationError FAILED
    java.lang.NoClassDefFoundError at Class.java:-2
        Caused by: java.lang.ClassNotFoundException at BuiltinClassLoader.java:581

1 test completed, 1 failed
```

**Comment by marcphilipp** [comment]
@arturmkr Does the issue persist for you? If so, please create a new issue.

**Comment by arturmkr** [comment]
@marcphilipp , I found a root cause.

Using JUnit 5.7.0 and having following build.gradle:

```
plugins {
    id 'org.springframework.boot' version '2.3.3.RELEASE'
    id 'io.spring.dependency-management' version '1.0.10.RELEASE'
    id 'java'
}

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.7.0'
    aspectjVersion = '1.9.6'
}

dependencies {
   
    implementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    implementation("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
    implementation("org.junit.jupiter:junit-jupiter-params:${junitVersion}")

    implementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.sun.xml.bind:jaxb-osgi:2.3.3'
    implementation 'org.springframework:spring-tx:5.2.8.RELEASE'
    implementation("org.aspectj:aspectjrt:${aspectjVersion}")
    implementation 'org.hibernate.validator:hibernate-validator:6.1.5.Final'
}


test {
   useJUnitPlatform()
}


jar {
    enabled = true
}
```

If I change JUnit 5.7.0 to JUnit 5.6.3 - everything works OK!

**Comment by sbrannen** [comment]
@arturmkr, please refer to https://github.com/junit-team/junit5/issues/2123#issuecomment-566224972 for details on how to properly upgrade a dependency version when using Spring Boot.
