### ISSUE TITLE
Assertions.assertIterableEquals overflows the stack

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2157]
## Steps to reproduce

The following code:
```java
var expected = List.of(Path.of("1"));
var actual = List.of(Path.of("1"));
System.out.println(expected);
System.out.println(actual);
assertIterableEquals(expected, actual);
```

Yields:
```
[1]
[1]
java.lang.StackOverflowError
	at java.base/java.util.ArrayList.grow(ArrayList.java:243)
	at java.base/java.util.ArrayList.add(ArrayList.java:453)
	at java.base/java.util.ArrayList.add(ArrayList.java:466)
	at java.base/sun.nio.fs.WindowsPath.initOffsets(WindowsPath.java:649)
	at java.base/sun.nio.fs.WindowsPath.getNameCount(WindowsPath.java:660)
	at java.base/java.nio.file.Path$1.hasNext(Path.java:923)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableEquals(AssertIterableEquals.java:62)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableElementsEqual(AssertIterableEquals.java:82)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableEquals(AssertIterableEquals.java:72)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableElementsEqual(AssertIterableEquals.java:82)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableEquals(AssertIterableEquals.java:72)
	[...]
```

## Deliverables

- [ ] Provide fix and test for comparing `Iterable<? extends Iterable<?>>` instances.

**Comment by jbduncan** [comment]
Oh wow, that's a really insidious bug! Thank you very much for finding and fixing it @sormuras. 👏

**Comment by jbduncan** [comment]
I wonder if this bug could have been caught with mutation testing. 🤔

**Comment by sormuras** [comment]
> I wonder if this bug could have been caught earlier with mutation testing. 🤔

Interesting thought. Perhaps also a candidate for property-based testing ... @jlink?

**Comment by jlink** [comment]
@sormuras Can you point me to the test? I'll make it a simple property and see if it catches the bug.

**Comment by sormuras** [comment]
https://github.com/junit-team/junit5/blob/0e393926c537541c00c8bc66e99b198d84c89ab0/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertIterableEqualsAssertionsTests.java#L446-L452

**Comment by jlink** [comment]
I could detect the bug with the following rather straightforward property:

@Property
<T> void assertingEqualityOfTwoListsShouldNeverThrowException(@ForAll List<T> expected, @ForAll List<T> actual) {
	try {
		assertIterableEquals(expected, actual);
	} catch (AssertionError ignore) {}
}

I had to register a default arbitrary provider for `java.nio.Path` because there is currently none in jqwik. But that could be fixable, of course. I'm wondering, however, what's so special about `Path`.

There's an additional drawback: Shrinking does not produce something meaningful in this setup. That means that the falsifying sample is very large and hard to identify.

**Comment by marcphilipp** [comment]
The special thing about path is that its iterator returns paths whose iterator will return instances that are equal to themselves. For instance, the following Groovy snippet 

```groovy
import java.nio.file.Paths
def path = Paths.get("bar");
println path.iterator().next().equals(path)
println path.iterator().next().is(path)
```

prints

```
true
false
```

The code did not account for this kind of recursiveness.

**Comment by jlink** [comment]
That's some strange kind of behaviour indeed. Nothing in Iterator's contract that would exclude that, though.
