### ISSUE TITLE
Kotlin test code using backtick test method names has case-insensitive collision

### ISSUE THREAD

**Issue by mattdkerr** [junit-team/junit5#2180]
## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter
 - Build Tool/IDE: Grade 5.6.4 or IntelliJ IDEA 2019.3.3

Junit 5 - 5.5.2
Junit Platform - 1.5.2
Kotlin - 1.3.61
Java 11.0.5 (Zulu)

## Steps to reproduce

```java
import java.util.*
import kotlin.test.*
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.assertThrows

@Tag("unit")
class CasingTest {
    @Test
    fun `when blah, methodA succeeds`() {
      // anything or nothing here
    }
    @Test
    fun `when BLAH, methodA succeeds`() {
      // anything or nothing here
    }
}
```
**Expectation:** 
Since it's valid in Kotlin to have these two as separate methods you would expect both methods to execute appropriately.

**Actual:**
java.lang.NoClassDefFoundError  <package name>/TestClass$when blah, methodA succeeds$result$1 (wrong name: <package name>/TestClass$when BLAH, methodA succeeds$result$1)

**Comment by marcphilipp** [comment]
We tried reproducing this with 5.5.2 and the latest master but couldn't.

@mattdkerr Could you please provide the full stack trace? Moreover, the imports look incomplete/inconsistent.

**Comment by pauldingemans** [comment]
@marcphilipp I have just reproduced this problem with current master.

After pulling and verifying the build, the output is as follows:
```
./gradlew build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 20s
233 actionable tasks: 45 executed, 5 from cache, 183 up-to-date
```

After this I duplicated test "assertThrows and fail" in class "KotlinAssertionsTests" and changed the test name to "AssertThrows and fail".

Next, I ran the build again which indeed failed:
```
$ ./gradlew build

> Configure project :
[versioning] WARNING - the working copy has unstaged or uncommitted changes.

> Task :junit-jupiter-engine:test

KotlinAssertionsTests > assertThrows and fail() FAILED
    java.lang.NoClassDefFoundError: org/junit/jupiter/api/KotlinAssertionsTests$AssertThrows and fail$1 (wrong name: org/junit/jupiter/api/KotlinAssertionsTests$assertThrows and fail$1)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.junit.jupiter.api.KotlinAssertionsTests.assertThrows and fail(KotlinAssertionsTests.kt:55)

1574 tests completed, 1 failed, 72 skipped

> Task :junit-jupiter-engine:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':junit-jupiter-engine:test'.
> There were failing tests. See the report at: file:///Users/pdingemans/git/non-opex/junit5/junit-jupiter-engine/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 24s
230 actionable tasks: 45 executed, 4 from cache, 181 up-to-date
```

**Comment by marcphilipp** [comment]
@mattdkerr @pauldingemans Are you both using macOS? I'm pretty sure this is caused by https://youtrack.jetbrains.com/issue/KT-17822.

**Comment by pauldingemans** [comment]
> @mattdkerr @pauldingemans Are you both using macOS? I'm pretty sure this is caused by https://youtrack.jetbrains.com/issue/KT-17822.

Yes I am using macOS.

**Comment by marcphilipp** [comment]
I'm going to assume @mattdkerr is also using a case-insensitive file system. Thus, this is a general issue with closures/anonymous classes in Kotlin.

**Comment by mattdkerr** [comment]
I’m using Windows 10 NTFS, so yes, it’s case insensitive.
