### ISSUE TITLE
Test failure attributed to the wrong test class with parallel test execution

### ISSUE THREAD

**Issue by dfa1** [junit-team/junit5#2204]
## Steps to reproduce

Run `./mvnw clean package` using JDK11 in the following branch:
https://github.com/dfa1/hosh/tree/bugreport-for-junit5

According to the following message seems that failure is caused by `TerminalModuleTest`, even if the stacktrace shows `CompilerTest`:

```
[INFO] Running hosh.modules.TerminalModuleTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in hosh.runtime.InterpreterTest
[INFO] Running hosh.modules.NetworkModuleTest
[ERROR] Tests run: 53, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.185 s <<< FAILURE! - in hosh.modules.TerminalModuleTest
[ERROR] commandAfterCommentBlock  Time elapsed: 0.047 s  <<< ERROR!
java.lang.NullPointerException
	at hosh@0.1.0-SNAPSHOT/hosh.runtime.Compiler.compileSequence(Compiler.java:77)
	at hosh@0.1.0-SNAPSHOT/hosh.runtime.Compiler.compileStatement(Compiler.java:73)
	at hosh@0.1.0-SNAPSHOT/hosh.runtime.Compiler.compile(Compiler.java:66)
	at hosh@0.1.0-SNAPSHOT/hosh.runtime.CompilerTest.commandAfterCommentBlock(CompilerTest.java:317)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:396)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:721)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.joinConcurrentTasksInReverseOrderToEnableWorkStealing(ForkJoinPoolHierarchicalTestExecutorService.java:148)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

## Context

 - Used versions (Jupiter/Vintage/Platform):5.6.0
 - Build Tool/IDE: maven 3.6.2
- parallel test execution enabled:
```
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = concurrent
junit.jupiter.execution.parallel.mode.classes.default = concurrent
```

**Comment by dfa1** [comment]
It looks like bug is happening only in macOS:
https://github.com/dfa1/hosh/runs/478219750

(windows and linux jobs failed with expected class)

**Comment by sormuras** [comment]
Which version of Maven Surefire is used?

Does sequential test execution prevent the printout of the wrong test class?

> According to the following message seems that failure is caused by `TerminalModuleTest`, even if the stacktrace shows `CompilerTest`:

Btw. `NetworkModuleTest` shows 1 error, `TerminalModuleTest` reports 0 erros.

**Comment by dfa1** [comment]
> Which version of Maven Surefire is used?

I'm using surefire 2.22.2. 

> Does sequential test execution prevent the printout of the wrong test class?

yes, without parallel execution enabled everything is fine.

> Btw. NetworkModuleTest shows 1 error, TerminalModuleTest reports 0 errors.

Well, actually log output is interleaved: some tests are starting, some are terminating. Error is reported really in `TerminalModuleTest`.

**Comment by sormuras** [comment]
Can you please give Surefire `3.0.0-M4` a shot?

**Comment by dfa1** [comment]
same problem (just pushed the relevant commits)

**Comment by dfa1** [comment]
By disabling parallel execution I see:
```
[INFO] Running hosh.runtime.CompilerTest
[INFO] Running hosh.runtime.CompilerTest$Strings
[ERROR] Tests run: 32, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 0.027 s <<< FAILURE! - in hosh.runtime.CompilerTest$Strings
[ERROR] hosh.runtime.CompilerTest.commandAfterCommentBlock  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NullPointerException
	at hosh@0.1.0-SNAPSHOT/hosh.runtime.Compiler.compileSequence(Compiler.java:77)
```
but failing test is inside `CompilerTest`, not `CompilerTest$String` as reported.

Maybe the problem is in `@Nested` classes logic? @sormuras

**Comment by sormuras** [comment]
Ah, found the issue already reported as https://issues.apache.org/jira/browse/SUREFIRE-1643

> Problem to solve: `TestSetRunListener` is built on the philosophy that test-sets are arrived in a sequence and do not overlap. This should be reworked to a full parallelism support.

Thus closing this issue.
