### ISSUE TITLE
Missing test launcher?

### ISSUE THREAD

**Issue by ramang22** [junit-team/junit5#2221]
Hello! i am getting similar error, when i am trying to execute jUnit test from code.
```
ERROR - llij.ide.plugins.PluginManager - Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath 
org.junit.platform.commons.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
	at testController.MainTestController.runAllTests(MainTestController.java:34)
	at pluginCommunicationHandler.RunTestButton.actionPerformed(RunTestButton.java:14)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:283)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:294)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:263)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:107)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:198)
	at java.desktop/java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:396)
	at java.desktop/java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:364)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Can someone help me? 
Here is my gradle file
```
plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '0.4.16'
}

group 'org.example'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-launcher
    compile group: 'org.junit.platform', name: 'junit-platform-launcher', version: '1.6.0'
    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-runner
    compile group: 'org.junit.platform', name: 'junit-platform-runner', version: '1.6.0'
    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-engine
    compile group: 'org.junit.platform', name: 'junit-platform-engine', version: '1.6.0'
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
    compile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.6.0'
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine
    compile group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.6.0'
}
    test {
        useJUnitPlatform()
    }



// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version '2019.3'
}
patchPluginXml {
    changeNotes """
      Add change notes here.<br>
      <em>most HTML tags may be used</em>"""
}
```
Executing code
```
        LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
                .selectors(
                        //selectPackage("test"),
                        //selectClass(FirstUnitTest.class),
                        selectMethod(UnitTests.class,"whenSomething_thenSomething")
                )
                .build();
        Launcher launcher = LauncherFactory.create(); //MainTestController.java:34 her exception occur
        SummaryGeneratingListener listener = new SummaryGeneratingListener();
        launcher.registerTestExecutionListeners(listener);
        launcher.execute(request);
        TestExecutionSummary summary = listener.getSummary();
        long result = summary.getTestsSucceededCount();
        System.out.println(result);
```

**Comment by marcphilipp** [comment]
This should work. Could you please add a `System.out.println(System.getProperty("java.class.path"))` statement before `LauncherFactory.create()`?

**Comment by ramang22** [comment]
Here is requested output

/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/tools.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/idea_rt.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/idea.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/bootstrap.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/extensions.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/util.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/openapi.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/trove4j.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/jdom.jar:/Users/ramang/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2019.3/5a74bbe98a814d61e6069abd0902b46668f1278c/ideaIC-2019.3/lib/log4j.jar

**Comment by marcphilipp** [comment]
I have no experience with IntelliJ plugin development. Apparently, each plugin has [its own class loader](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_class_loaders.html). Since JUnit uses the current thread's context class loader, I suspect that's a different one and thus no engines are found when using `ServiceLoader` to load them.

Could you please try setting `Thread.currentThread().setContextClassLoader(PluginManager.getPlugin(PluginId.getId(...)).getPluginClassLoader())` before calling `LauncherFactory.create`?

**Comment by ramang22** [comment]
Hello, its fixed finally. I added 
```
        JupiterTestEngine testEngine  = new JupiterTestEngine();

        LauncherConfig launcherConfig = LauncherConfig.builder()
                .addTestEngines(testEngine)
                .build();
        Launcher launcher = LauncherFactory.create(launcherConfig);
```
and it works :). 
But i cant access project (not plugin) .class files for running tests. Do you have idea how can i fix it?

**Comment by marcphilipp** [comment]
You'll have to create a custom classloader, e.g. a `URLClassLoader` that uses the projects output dir(s).
