### ISSUE TITLE
Console Launcher does not explicitly set [java.class.path] system property when using the [--classpath] option 

### ISSUE THREAD

**Issue by Vazzilena** [junit-team/junit5#2268]
Hey,

Previously we were using ant junit task and junit4. Many of our tests use `System.getProperty("java.class.path") `to pull classpath entries. We have never explicitly passed `"java.class.path"` in the ant junit task. 
Obviously, the underlying runner is automatically doing it by putting the entries we specify in the `<classpath>` attribute and this seems valid to me.

Now we are migrating to junit5 and we started using directly the console launcher in the ant java task, where we explicitly pass `–-classpath `option to the launcher. All the test that are using `System.getProperty("java.class.path")` are  now failing because the entries we pass in  the `–-classpath `option are not automatically populated in `"java.class.path" `property.

How can we solve this? 

If I additionally add `"java.class.path"` as `sysproperty key` or as `jvmarg value`, the task fails as the command line becomes huge (as I already have the same entries in the `--classpath `option and I cannot remove them as the launcher requires this):

```
 [java] Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
     [java]     at java.lang.ProcessImpl.create(Native Method)
     [java]     at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
     [java]     at java.lang.ProcessImpl.start(ProcessImpl.java:137)
     [java]     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
```

I am using junit-platform-launcher-1.6.0-RC1.jar

And my ant task looks like this:

```
 <macrodef name="console.runner">
    <attribute name="console.arguments" default=""/>
    <attribute name="max.memory" default=""/>
    <attribute name="jvm.args" default=""/>
    <attribute name="test.jvm.classpath" default="${test.jvm.classpath}"/>
    <attribute name="server.jvm.classpath" default="${server.jvm.classpath}"/>
    <attribute name="license.file" default="${server.license.file}"/>
    <attribute name="license.directory" default="${server.license.directory}"/>
    <attribute name="extra.server.classpath" default=""/>
    <attribute name="fail.if.no.tests" default="true"/>
    <attribute name="fail.on.error" default="false"/>
    <attribute name="maxmemory" default="${junit.maxmemory}"/>
    <attribute name="reporting.dir" default="${basedir}"/>
    <attribute name="identifier" default=""/>
    <attribute name="default.arguments"
      default=" --disable-ansi-colors --details-theme=ascii --details=tree --fail-if-no-tests=@{fail.if.no.tests} --reports-dir=@{reporting.dir} --classpath=@{test.jvm.classpath}${path.separator}@{server.jvm.classpath}"/>
    <sequential>

      <echo message="=================================================="/>
      <echo message="Test classpath is: @{test.jvm.classpath}"/>
      <echo message="=================================================="/>
      <echo message="Server classpath is: @{server.jvm.classpath}"/>
      <echo message="=================================================="/>
      <echo message="Extra server classpath is: @{extra.server.classpath}"/>
      <echo message="=================================================="/>
      <echo message="JVM arguments: @{jvm.args}"/>
      <echo message="=================================================="/>
      <echo message="License directory: @{license.directory}"/>
      <echo message="=================================================="/>
      <echo message="License file: @{license.file}"/>
      <echo message="=================================================="/>
      <echo
        message="Junit platform console launcher arguments: @{console.arguments}"/>
      <echo message="=================================================="/>
      <echo
        message="Junit platform console launcher default arguments: @{default.arguments}"/>
      <echo message="=================================================="/>

      <mkdir dir="@{reporting.dir}"/>
      <jacoco:coverage destfile="@{reporting.dir}/@{identifier}.exec"
        append="true">
        <java jar="${console.runner.location}"
          fork="true"
          failonerror="@{fail.on.error}"
          append="true"
          maxmemory="@{max.memory}">

          <sysproperty key="DOCKER_TEST_SERVER" value="${docker.test.server}"/>
          <sysproperty key="DOCKER_IMAGE_VERSION" value="${docker.image.version}"/>
          <sysproperty key="DOCKER_HOST" value="${docker.host}"/>
          <sysproperty key="DOCKER_ADAPTER" value="${docker.adapter}"/>
          <sysproperty key="DOCKER_IMAGE_REPOSITORY_URL" value="${docker.image.repository.url}"/>

          <arg line="@{default.arguments}@{console.arguments}"/>

          <jvmarg line="${jvm.args}"/>
          <jvmarg line="@{jvm.args}"/>
          <jvmarg value="-XX:+HeapDumpOnOutOfMemoryError"/>
          <jvmarg value="-XX:HeapDumpPath=${basedir}"/>
          <!--<jvmarg
           value="-Djava.class.path=@{test.jvm.classpath}${path.separator}@{server.jvm.classpath}"/>-->
          <jvmarg value="-Djava.io.tmpdir=${custom.java.tmp.dir}"/>
          <jvmarg value="-DLOGLEVEL=${log.level}"/>
          <jvmarg value="-DTESTLOGLEVEL=${test.log.level}"/>
          <jvmarg value="-DTESTLOGFILELEVEL=${test.log.file.level}"/>
          <jvmarg value="-DEnableDebug=${debug.flag}"/>
          <jvmarg value="-DLICENSE_DIR=@{license.directory}"/>
          <jvmarg value="-DLICENCE_FILE=@{license.file}"/>
          <jvmarg value="-DPROJECT_ROOT_FOLDER=${project.root}"/>
          <jvmarg value="-DJUnitBasePort=${junit.base.port}"/>
          <jvmarg value="-DFAILON_SESSION_LEAKS=${check.session.leaks}"/>
          <jvmarg
            value="-Dnirvana.test.server.classpath_extra=@{server.jvm.classpath}${path.separator}@{extra.server.classpath}"/>
          <jvmarg value="-Dnirvana.test.server.classpath_nostd=yes"/>
          <jvmarg value="-DGETCOVERAGE=${server.code.coverage.option}"/>
          <jvmarg value="-DJACOCO_PATH=${jacocoagent.location}"/>
          <jvmarg value="-Dcom.softwareag.um.client.GenerateEventUID=${generate.event.uid}"/>

        </java>
      </jacoco:coverage>
    </sequential>
  </macrodef>
```

**Comment by marcphilipp** [comment]
As a workaround you can add the console launcher jar to the classpath and invoke `java -cp` instead of `java -jar` with the full classpath.

**Comment by Vazzilena** [comment]
> As a workaround you can add the console launcher jar to the classpath and invoke `java -cp` instead of `java -jar` with the full classpath.

Indeed, this helped. Thanks! (although I still think that it makes sense that the launcher sets this system property)

Here is the way it worked for me:

```
 <macrodef name="console.runner">
    <attribute name="console.arguments" default=""/>
    <attribute name="max.memory" default=""/>
    <attribute name="jvm.args" default=""/>
    <attribute name="test.jvm.classpath" default="${test.jvm.classpath}"/>
    <attribute name="server.jvm.classpath" default="${server.jvm.classpath}"/>
    <attribute name="license.file" default="${server.license.file}"/>
    <attribute name="license.directory" default="${server.license.directory}"/>
    <attribute name="extra.server.classpath" default=""/>
    <attribute name="fail.if.no.tests" default="true"/>
    <attribute name="fail.on.error" default="false"/>
    <attribute name="maxmemory" default="${junit.maxmemory}"/>
    <attribute name="reporting.dir" default="${basedir}"/>
    <attribute name="identifier" default=""/>
    <sequential>

      <echo message="=================================================="/>
      <echo message="Test classpath is: @{test.jvm.classpath}"/>
      <echo message="=================================================="/>
      <echo message="Server classpath is: @{server.jvm.classpath}"/>
      <echo message="=================================================="/>
      <echo message="Extra server classpath is: @{extra.server.classpath}"/>
      <echo message="=================================================="/>
      <echo message="JVM arguments: @{jvm.args}"/>
      <echo message="=================================================="/>
      <echo message="License directory: @{license.directory}"/>
      <echo message="=================================================="/>
      <echo message="License file: @{license.file}"/>
      <echo message="=================================================="/>
      <echo
        message="Junit platform console launcher arguments: @{console.arguments}"/>
      <echo message="=================================================="/>

      <path id="discovery.path">
        <fileset dir="${project.root}/jars">
          <include name="*.jar"/>
        </fileset>
      </path>
      <local name="test.discovery.classpath"/>
      <pathconvert property="test.discovery.classpath" refid="discovery.path"/>

      <mkdir dir="@{reporting.dir}"/>
      <jacoco:coverage destfile="@{reporting.dir}/@{identifier}.exec"
        append="true">
        <java fork="true"
          failonerror="@{fail.on.error}"
          append="true"
          maxmemory="@{max.memory}"
          classname="org.junit.platform.console.ConsoleLauncher">

          <sysproperty key="DOCKER_TEST_SERVER" value="${docker.test.server}"/>
          <sysproperty key="DOCKER_IMAGE_VERSION" value="${docker.image.version}"/>
          <sysproperty key="DOCKER_HOST" value="${docker.host}"/>
          <sysproperty key="DOCKER_ADAPTER" value="${docker.adapter}"/>
          <sysproperty key="DOCKER_IMAGE_REPOSITORY_URL" value="${docker.image.repository.url}"/>

          <arg
            line=" --disable-ansi-colors --details-theme=ascii --details=tree --fail-if-no-tests=@{fail.if.no.tests} --reports-dir=@{reporting.dir} --classpath=${test.discovery.classpath}@{console.arguments}"/>

          <jvmarg line="${jvm.args}"/>
          <jvmarg line="@{jvm.args}"/>
          <jvmarg value="-XX:+HeapDumpOnOutOfMemoryError"/>
          <jvmarg value="-XX:HeapDumpPath=${basedir}"/>
          <jvmarg value="-Djava.io.tmpdir=${custom.java.tmp.dir}"/>
          <jvmarg value="-DLOGLEVEL=${log.level}"/>
          <jvmarg value="-DTESTLOGLEVEL=${test.log.level}"/>
          <jvmarg value="-DTESTLOGFILELEVEL=${test.log.file.level}"/>
          <jvmarg value="-DEnableDebug=${debug.flag}"/>
          <jvmarg value="-DLICENSE_DIR=@{license.directory}"/>
          <jvmarg value="-DLICENCE_FILE=@{license.file}"/>
          <jvmarg value="-DPROJECT_ROOT_FOLDER=${project.root}"/>
          <jvmarg value="-DJUnitBasePort=${junit.base.port}"/>
          <jvmarg value="-DFAILON_SESSION_LEAKS=${check.session.leaks}"/>
          <jvmarg
            value="-Dnirvana.test.server.classpath_extra=@{server.jvm.classpath}${path.separator}@{extra.server.classpath}"/>
          <jvmarg value="-Dnirvana.test.server.classpath_nostd=yes"/>
          <jvmarg value="-DGETCOVERAGE=${server.code.coverage.option}"/>
          <jvmarg value="-DJACOCO_PATH=${jacocoagent.location}"/>
          <jvmarg value="-Dcom.softwareag.um.client.GenerateEventUID=${generate.event.uid}"/>

          <classpath>
            <pathelement location="${console.runner.location}"/>
            <pathelement path="@{test.jvm.classpath}"/>
            <pathelement path="@{server.jvm.classpath}"/>
          </classpath>

        </java>
      </jacoco:coverage>
    </sequential>
  </macrodef>
```

**Comment by marcphilipp** [comment]
I'm glad it helped! I don't think the console launcher should mess with that system property. We could set an additional one if that helps. If so, please open a new issue for that use case.
