### ISSUE TITLE
NoClassDef in ClassSelectorResolver

### ISSUE THREAD

**Issue by jorgheymans** [junit-team/junit5#2377]
As reported in https://github.com/openzipkin/zipkin/issues/3159 , starting from surefire/failsafe 3.0.0-M5 we have tests crashing. We're unsure if the issue lies in junit or surefire, but since the exception is generated by junit code reporting it first here. 

## Steps to reproduce

* git clone https://github.com/openzipkin/
* cd openzipkin
* mvn --also-make --projects zipkin-tests clean install 

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/linuxbrew/.linuxbrew/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /home/linuxbrew/.linuxbrew/Cellar/openjdk/13.0.2+8_2/libexec
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-42-generic", arch: "amd64", family: "unix"

....

[INFO] Zipkin Interop Tests ............................... FAILURE [  7.828 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.880 s
[INFO] Finished at: 2020-08-10T22:05:06+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (verify) on project zipkin-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/heymjo/src/zipkin/zipkin-tests/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] TestEngine with ID 'junit-jupiter' failed to discover tests
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:733)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
```
Dump file:

```
# Created at 2020-08-10T21:42:45.607
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:189)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:124)
	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)
	at org.apache.maven.surefire.api.util.DefaultScanResult.applyFilter(DefaultScanResult.java:102)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:147)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: org.junit.platform.commons.JUnitException: NestedClassSelector [enclosingClassNames = [zipkin2.storage.ITInMemoryStorage], nestedClassName = 'zipkin2.storage.ITInMemoryStorage$ITDependencies'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:45)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:181)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: zipkin2/storage/StorageComponent$Builder
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3192)
	at java.base/java.lang.Class.getMethods(Class.java:1905)
	at org.junit.platform.commons.util.ReflectionUtils.getDefaultMethods(ReflectionUtils.java:1440)
	at org.junit.platform.commons.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:1413)
	at org.junit.platform.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:1355)
	at org.junit.platform.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:1339)
	at org.junit.platform.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:1325)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$toResolution$12(ClassSelectorResolver.java:136)
	at org.junit.platform.engine.support.discovery.SelectorResolver$Match.expand(SelectorResolver.java:646)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$enqueueAdditionalSelectors$1(EngineDiscoveryRequestResolution.java:109)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.enqueueAdditionalSelectors(EngineDiscoveryRequestResolution.java:108)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:94)
	... 15 more
Caused by: java.lang.ClassNotFoundException: zipkin2.storage.StorageComponent$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 39 more
```

## versions

The junit / junit-vintage / jupiter versions are all declared in the root pom:

https://github.com/openzipkin/zipkin/blob/52a1943581446d3b21759cef65cd471cdc5e6ca3/pom.xml#L77

**Comment by sormuras** [comment]
> [...] starting from surefire/failsafe 3.0.0-M5 we have tests crashing.

I assume, it did it work with 3.0.0-M4. Am I right?

It looks to me like a class-path (module-path?) misconfiguration. Can you please provide a detailed log from the Failsafe plugin execution?

**Comment by jorgheymans** [comment]
This is the -X output log
[output.log.gz](https://github.com/junit-team/junit5/files/5055640/output.log.gz)

here is the output for M4 which indeed works fine
[output4.log.gz](https://github.com/junit-team/junit5/files/5055775/output4.log.gz)

**Comment by sormuras** [comment]
Comparing both logs shows that M5 does indeed place a JAR on the `module-path`. See this snippet:

```text
[DEBUG] Determined Maven Process ID 169321
[DEBUG] Fork Channel [1] connection string 'pipe://1' for the implementation class 
[DEBUG] boot classpath:  /home/heymjo/.m2/repository/org/apache/maven/surefire/sure
[DEBUG] boot(compact) classpath:  surefire-booter-3.0.0-M5.jar  surefire-api-3.0.0-
[DEBUG] Path to args file: /home/heymjo/src/zipkin/zipkin-tests/target/surefire/sur
[DEBUG] args file content:
--module-path
"/home/heymjo/src/zipkin/zipkin-tests/target/zipkin-tests-2.21.7-SNAPSHOT.jar"
--class-path
"/home/heymjo/.m2/repository/org/apache/maven/surefire/surefire-booter/3.0.0-M5/sur
--patch-module
zipkin.tests="/home/heymjo/src/zipkin/zipkin-tests/target/test-classes"
--add-exports
zipkin.tests/zipkin2.storage=ALL-UNNAMED
--add-modules
zipkin.tests
--add-reads
zipkin.tests=ALL-UNNAMED
org.apache.maven.surefire.booter.ForkedBooter
[DEBUG] Forking command line: /bin/sh -c cd /home/heymjo/src/zipkin/zipkin-tests &&
[DEBUG] Fork Channel [1] connected to the client.
[ERROR] TestEngine with ID 'junit-jupiter' failed to discover tests
[DEBUG] Closing the fork 1 after saying GoodBye.
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

IIRC, there's a new "useModulePath" boolean flag to prevent SF/FS putting JAR files on the module path. Can you give this a shot?

**Comment by jorgheymans** [comment]
> IIRC, there's a new "useModulePath" boolean flag to prevent SF/FS putting JAR files on the module path. Can you give this a shot?

Indeed that works, thanks ! Is this a standard workaround or should i still report the exception with the failsafe plugin maintainers?

**Comment by sormuras** [comment]
It's a standard configuration option offered by SF/FS since version `3.0.0-M2`:

https://github.com/apache/maven-surefire/blob/6e895b1e2a66df7225ca333921e869ea704b9ce3/maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java#L357-L366

So, it's not strictly speaking a "workaround". I wonder why Plexus (used to set up the class-path and module-path) thinks that `zipkin-tests-2.21.7-SNAPSHOT.jar` is a Java module. Does it contain a compiled module descriptor?

**Comment by sormuras** [comment]
@rmannibucau analyzed the underlying issue. It's within SF/FS usage of a feature Plexus, namely `org.codehaus.plexus.languages.java.jpms.LocationManager#resolvePath(java.nio.file.Path, org.codehaus.plexus.languages.java.jpms.ModuleNameExtractor)`.

> this impl resolves the jpms name even from automatic name or even jar file name
> then surefire uses the fact there is a name to know if it is a jpms module
> actually you never know upfront if a jar is used as a jpms module or not

Closing this issue -- follow-up to https://issues.apache.org/jira/browse/SUREFIRE-1831
