### ISSUE TITLE
Launcher should fail with a descriptive error message when the same TestPlan is executed twice

### ISSUE THREAD

**Issue by lestephane** [junit-team/junit5#2379]
(version: 5.7.0.M1)

I'm trying to implement a RunUntilFailure class that runs the same TestPlan in an infinite loop until the first failure occurs,
to catch flapping tests.

Running the plan once succeeds, but, on the second run, I get for each @ParametrizedTest

```text
java.lang.NullPointerException
	at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor.populateNewExtensionRegistry(TestTemplateInvocationTestDescriptor.java:68)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:103)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:87)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:53)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:66)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at de.quantummaid.junit.RunTestsFromClasspathUntilFailure.runTestPlanOnce(RunTestsFromClasspathUntilFailure.java:76)
	at de.quantummaid.junit.RunTestsFromClasspathUntilFailure.main(RunTestsFromClasspathUntilFailure.java:50)
```

It is my understanding that `void execute(TestPlan testPlan, TestExecutionListener... listeners);` is there to not pay the overhead of classpath scanning everytime. You discover the tests once, then run the resulting TestPlan one or more times.

But `TestTemplateInvocationTestDescriptor` seems to have been written with the expectation that it is used with only one `JupiterEngineExecutionContext`, ever. It's not clear what will fix this, or whether I'm just abusing the API.

But my expectation from reading the Launcher javadoc is that I should be able to call the execute() method with the same TestPlan two (or more) times in a row.

```
 * @apiNote Calling this method will cause test discovery to be executed for
 * all registered engines. If the same {@link LauncherDiscoveryRequest} was
 * previously passed to {@link #discover(LauncherDiscoveryRequest)}, you
 * should instead call {@link #execute(TestPlan, TestExecutionListener...)}   <<<<<<<<
 * and pass the already acquired {@link TestPlan} to avoid the potential`     <<<<<<<<
 * performance degradation (e.g., classpath scanning) of running test         <<<<<<<<
 * discovery twice.
 *
 * @param launcherDiscoveryRequest the launcher discovery request; never {@code null}
 * @param listeners additional test execution listeners; never {@code null}
 */
void execute(LauncherDiscoveryRequest launcherDiscoveryRequest, TestExecutionListener... listeners); 
```

I'll try doing the same using LauncherDiscoveryRequest and see if it is a workaround for this problem, and report.

**Comment by marcphilipp** [comment]
That `@apiNote` is referring to calling `execute(LauncherDiscoveryRequest)` after having called `discover(LauncherDiscoveryRequest)` with the same request. Executing the same test plan twice is currently not supported since test engines are bound to have some state (like Jupiter does in your case) that is not cleared. However, we should fail with a proper failure message when the same `TestPlan` is executed again.

**Comment by marcphilipp** [comment]
I've submitted #2380 to address this issue.

**Comment by jlink** [comment]
> That `@apiNote` is referring to calling `execute(LauncherDiscoveryRequest)` after having called `discover(LauncherDiscoveryRequest)` with the same request. Executing the same test plan twice is currently not supported since test engines are bound to have some state (like Jupiter does in your case) that is not cleared. However, we should fail with a proper failure message when the same `TestPlan` is executed again and we should document that this is not supported.

The change just fell on my feet after upgrading to 1.7.0. 

Why does the problem of having state in an engine go away when the test plan is recreated for each run? I guess Jupiter does not store the state in the test plan or does it?

**Comment by marcphilipp** [comment]
> The change just fell on my feet after upgrading to 1.7.0.

How so? Did you have code that called `Launcher.execute()` multiple times with the same test plan?

> Why does the problem of having state in an engine go away when the test plan is recreated for each run? I guess Jupiter does not store the state in the test plan or does it?

Jupiter has state in its `TestDescriptor` implementations which are contained in the `TestPlan`. Does that answer your question?

**Comment by jlink** [comment]
> Jupiter has state in its `TestDescriptor` implementations which are contained in the `TestPlan`. Does that answer your question?

As far as I can see it doesn't contain them , it only uses them at creation time. I might miss something, though.

It would be nice to be able to reuse a plan but recreating it is also possible and the performance price is low enough in small projects. So don't worry (too much ;-)

**Comment by marcphilipp** [comment]
`InternalTestPlan` contains `LauncherDiscoveryResult` which contains the engine `TestDescriptors`:
https://github.com/junit-team/junit5/blob/fd6dc3eb82df2ce4317350b5078c48eb891d6a6c/junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/InternalTestPlan.java#L33
https://github.com/junit-team/junit5/blob/fd6dc3eb82df2ce4317350b5078c48eb891d6a6c/junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryResult.java#L34

**Comment by jlink** [comment]
Hm. My reasoning might be wrong but I'm wondering if this dependency does prevent generic de/serialization of a test plan?

Why do I think this is important? Imagine you want to split starting/reporting tests from running tests in two different processes (e.g. over the network or through inter-process communication). I think this was one of the scenarios we had in mind when we decided to make TestIdentifiers immutable. This is not such a fancy scenario, in fact, I was recently contacted about building an external test runner to trigger and observe tests running somewhere else (in this case a Spring boot app).

**Comment by marcphilipp** [comment]
`TestPlan` is not serializable and IIRC never was. If you want to execute tests elsewhere your best bet is to collect all leaf unique ids and discover a new test plan.
