### ISSUE TITLE
TempDir is cleaned before AfterAll is executed

### ISSUE THREAD

**Issue by henryju** [junit-team/junit5#2427]
Hi,

I'm using JUnit 5 (5.7.0). In a test, I need to create some files in a temp dir, and init stuff that will lock some files in the temp dir (on Windows). The issue is that the test can't end correctly, since I get an error when JUnit is trying to clean the directory.

```java
class MyTests {

  static MyCloseableStuff closeable;

  @BeforeAll
  static void init(@TempDir Path temp) {
    closeable = init(temp); // Creates some files in temp, and keep them open (=locked on Windows)
  }

  @AfterAll
  static void stop() {
    closeable.close(); // Close the open files descriptors
  }

}
```

I'm receiving this exception:
```
Sep 28, 2020 8:49:39 AM org.junit.jupiter.engine.execution.JupiterEngineExecutionContext close
SEVERE: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.ClassExtensionContext@5bfc79cb
java.io.IOException: Failed to delete temp directory C:\Users\VSSADM~1\AppData\Local\Temp\junit15147163024233421499. The following paths could not be deleted (see suppressed exceptions for details): , xxx, yyy, ...
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:262)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:182)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:68)
	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:74)
	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:87)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)

```
Seems to me that the TempDir is tried to be cleaned before my AfterAll method is called. Is there a way for me to fix that?

**Comment by henryju** [comment]
Note that this is the pattern that I was using in JUnit 4 and that was working fine:
```java
public class MyTest {

  static MyCloseableStuff closeable;

  @ClassRule
  public static TemporaryFolder temp = new TemporaryFolder();

  @BeforeClass
  public static void init() {
    closeable = init(temp.newFolder()); // Creates some files in temp, and keep them open (=locked on, Windows)
  }

  @AfterClass
  public static void stop() {
    closeable.close(); // Close the open files descriptors
  }

}
```

**Comment by henryju** [comment]
OK, my bad, I'm not sure there is a JUnit issue in the end. I found my test was truly leaking some file descriptors, and the (new?) behavior of JUnit 5 failing when a file can't be deleted was in fact very helpful.
Sorry for the noise.
