### ISSUE TITLE
Stack trace is printed when test is aborted with TestAbortedException

### ISSUE THREAD

**Issue by dmcg** [junit-team/junit5#2524]
Using 5.7.0

```kotlin
class AbortedTests {
    @TestFactory fun test1() = DynamicTest.dynamicTest("skip") {
        throw TestAbortedException("abort in testfactory")
    }

    @Test
    fun test2() {
        throw TestAbortedException("abort in plain test")
    }
}
```

Prints on the console

```
org.opentest4j.TestAbortedException: abort in testfactory
	at dev.minutest.junit.experimental.AbortedTests$test1$1.execute(KotlinTestTests.kt:37)
        ....

org.opentest4j.TestAbortedException: abort in plain test
	at dev.minutest.junit.experimental.AbortedTests.test2(KotlinTestTests.kt:42)
	....
```

The recommended way of skipping a dynamic test is to throw the exception https://github.com/junit-team/junit5/issues/1439
but then the console prints the stack trace, making people think that something is wrong.

**Comment by dmcg** [comment]
Hmm, although on further (extended) debugging, this may be IntelliJ's JUnit5TestExecutionListener

**Comment by dmcg** [comment]
Reported to JetBrains as https://youtrack.jetbrains.com/issue/IDEA-259246
