### ISSUE TITLE
Make @TempDir restore mint permissions before closing context to avoid `AccessDeniedException`

### ISSUE THREAD

**Issue by Philzen** [junit-team/junit5#2609]
Suppose the following test which throws an `AccessDeniedException`:

```java
void givesNullIfFolderNotExecutable(@TempDir Path tempFolder) throws IOException {
	Path testFile = Files.createFile(tempFolder.resolve("test-file.txt"));
	tempFolder.toFile().setExecutable(false);

	String result = new MyObjectUnderTest().analyzeFile(testFile);

	assertThat(result).isEqualTo(null);   // file info could not be retrieved
}
```

To make this test functional i'll have to change the last line to:
``` java
	try {
		assertThat(result).isEqualTo(null);
	} finally {
		tempFolder.toFile().setExecutable(true);
	}
```

But this introduces 4 additional lines of bloat, hence decreasing brevity and readability of an otherwise simple test.

So my basic feature suggestion is to restore initial permissions on the tempFolder before trying to delete it. Bonus feature would be to have that done to any entities *within* it recursively as well, though i see a potential performance overhead concern. However, at the end of the day it would be a real win not having to think about restoring the initial state "manually" like i currently need to do.

Maybe there are reasons why this feature is a really bad idea, but i can't point my finger on it and am thankful for your reviews. 

I am filing this as a feature rather than a bug b/c this was the default behavior in Junit4, as there is currently no standard Java API available that allows deleting a folder with such permissions.

---

One thing to add (unrelated to feature request): Junit5 Doc explicitly encourages to provide feedback for this feature so it can be promoted, so i'd like to support that by saying i really like it b/c it provides a much better encapsulated scope than the old JUnit4-rule. It  made me discover and utilize the whole `nio` package where i enjoy the much leaner API (imho, now that i have wrapped my head around it). Hence i'd love to see it promoted to `MAINTAINED`. And *pleeaase* don't remove it, and i'm not only saying this b/c i just reworked a large test suite from Junit4 to Jupiter, but i guess that'd also be a real bummer. :wink:

**Comment by marcphilipp** [comment]
`TempDirectory` already attempts to make all files writable when deleting them fails. It sounds like we should try to make folders executable as well. Would you be interested in submitting a PR for that?

Regarding the API status: don't worry! We know it's widely used so we won't just delete it without providing a migration path. At this point there are no plans to remove it.

**Comment by Philzen** [comment]
> `TempDirectory` already attempts to make all files writable when deleting them fails. 

Oh that's good to know, maybe worthwhile to add that to the documentation at some point.

> Regarding the API status: don't worry! We know it's widely used so we won't just delete it without providing a migration path. At this point there are no plans to remove it.

I will be sleeping much better tonight :wink:

> It sounds like we should try to make folders executable as well. Would you be interested in submitting a PR for that?

Interested, yes definitely, would be a great honor to contribute here. But at the moment i'm at the limits regarding my energy and time resources. If you could point me at the bit in the code that tries to make everything writable again that may help me (or someone else) a lot in taking this up as i assume that'd be the right spot reset any executable flags as well. If i find some time to look into it, i'll report back when i start working on it.

**Comment by Philzen** [comment]
> TempDirectory already attempts to make all files writable when deleting them fails.

I have done some testing on this and i've found (at least on my linux ext4 filesystem) that this is never necessary – `TempDir` can be deleted no matter what the permissions are on the *files* contained in it. 

> It sounds like we should try to make folders executable as well.

It's also about making folders writable again – including the `TempDir` itself. I will do some testing and come up with a matrix what combinations throw an exception when Junit tries to close it's context. Currently using version 5.5.2 – i guess i should go to latest 5.7.x to get the full picture, correct?

**Comment by marcphilipp** [comment]
> If you could point me at the bit in the code that tries to make everything writable again that may help me (or someone else) a lot in taking this up as i assume that'd be the right spot to make it reset any executable flags as well.

Sure thing:

https://github.com/junit-team/junit5/blob/267ce626491b02a86af7fb94191313adb8959f8e/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L220-L249

> I have done some testing on this and i've found (at least on my linux ext4 filesystem) that this is never necessary

IIRC the change was introduced for filesystems on Windows.

> Currently using version 5.5.2 – i guess i should go to latest 5.7.x to get the full picture, correct?

Yes, the code above was introduced for 5.7.x.

**Comment by Philzen** [comment]
Thanks for the clarification @marcphilipp – i upgraded to 5.7.2 now and can confirm that the above code works like a charm and resets writable permissions of the `@tempDir` itself as well as contained directories (note to self - when picking this up, i should also test for 2nd-level directories). Hence i could already remove cruft code for these tests cases, very nice :wink:

However i can confirm that the issue description holds true, as not only the executable-flag needs to be restored, but also the readable-flag. Otherwise, for instance when a test removes the readable-flag from the `TempDir`, it currently also triggers `AccessDeniedException`.

**Comment by Philzen** [comment]
I have started to write some tests for this and will commit them soon. This is the matrix on the current situation. 

**Test Case Explanation**: First path component denotes the `TempDir` itself, following by either subdirectories (signified by trailing slash and typically an executable flag) and/or files within it.

| Test Case | OK or throws |
| :------- | :------: |
| rx | :heavy_check_mark: |
| rx/rw | `IOException` |
| rx/rwx/ | `IOException` |
| rx/r | `IOException` |
| rx/w | `AccessDeniedException` |
| rx/rx/ | `IOException` |
| rx/wx/ | `AccessDeniedException` |
| rx/rw/ | `IOException` |
| rx/rwx/rw | `IOException` |
| rx/rw/rw | `AccessDeniedException` |

**Comment by Philzen** [comment]
@marcphilipp & others i've written the tests for the above matrix and added them in 5f3ebf86ed. Then i tried to piggyback on to the `makeWritableAndTryToDeleteAgain` (which effectively a `resetPermissionsAndTryToDeleteAgain` method) in 72562301f5.

However, the problem seems to be that for all test cases throwing an `AccessDeniedException` as seen in the test matrix above, they never throw an `IOException` (as a matter of fact, no `Exception` at all) in the `deleteAndContinue`-method of the `SimpleFileVisitor`, so fixing permissions at that point in the flow doesn't do the job. You can debug yourself if you enable the tests i created in 72562301f5, then set a breakpoint where the `IOException` is caught and you'll find that it only gets reached 11 times – these are the 11 successful cases in column one of my test case.

Given the current test framework it's hard to find the underlying cause as that is hidden from the stack trace. When i run those tests from an external project i get the following stack trace (same for any of those `AccessDeniedException`-giving test cases:

```
Mai 24, 2021 2:24:08 AM org.junit.jupiter.engine.execution.JupiterEngineExecutionContext close
SCHWERWIEGEND: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@5db45159
java.nio.file.AccessDeniedException: /tmp/junit5910223365351596228/test-sub-dir/test-file.txt
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.Files.walkFileTree(Files.java:2706)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:192)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:180)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:68)
	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:74)
	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.cleanUp(TestMethodTestDescriptor.java:148)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.cleanUp(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:87)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

Can anybody advise?

**Comment by marcphilipp** [comment]
@Philzen Thanks for the detailed analysis! 👍 I pushed a commit to your PR branch that should fix the issue.

**Comment by Philzen** [comment]
@marcphilipp awesome, thanks for help! I will try to squash my non-functional commit into yours so we merge only working commits into the main history.

Will also make some suggestions in your commit, looking forward to your feedback.

What i was thinking is: Now that the restoring of file & folder permissions will done *before* the `deleteAndContinue` is called, the whole `makeWritableAndTryToDeleteAgain` thing introduced in ee5c45f4 become superfluous, correct? The only change that i'd see worth keeping is catching any exceptions around `Files.delete(path);` and adding them to the failures list.

If you agree i would also craft a cleanup commit on top – technically the tests introduced for #2046 should warn us anyway providing there is also a windows vm running the ci pipelines.
