### ISSUE TITLE
junit-platform-commons missing export

### ISSUE THREAD

**Issue by monkey1993** [junit-team/junit5#2726]
- Used versions (Jupiter/Vintage/Platform): 5.8.0
 - Build Tool/IDE: gradle 7.2

`org.junit.jupiter.engine.config.EnumConfigurationParameterConverter` using `org.junit.platform.commons.logging.LoggerFactory`, but in org.junit.platform.commons 1.8.0 `module-info` is only exports to `org.junit.jupiter.engine`, and not exports `org.junit.jupiter.engine.config`.

Internal Error occurred.
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalAccessError: class org.junit.jupiter.engine.config.EnumConfigurationParameterConverter (in unnamed module @0x101df177) cannot access class org.junit.platform.commons.logging.LoggerFactory (in module org.junit.platform.commons) because module org.junit.platform.commons does not export org.junit.platform.commons.logging to unnamed module @0x101df177
	at org.junit.jupiter.engine.config.EnumConfigurationParameterConverter.<clinit>(EnumConfigurationParameterConverter.java:31)
	at org.junit.jupiter.engine.config.DefaultJupiterConfiguration.<clinit>(DefaultJupiterConfiguration.java:38)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:66)
	at org.junit.platform.launcher@1.8.0/org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 11 more

**Comment by sormuras** [comment]
Can you please share your Gradle-based project? Seems like the IDEA runner puts part of the JUnit modules on the module path (e.g. `org.junit.platform.launcher@1.8.0`), and some others on the class path (e.g. `org.junit.jupiter.engine`).

**Comment by monkey1993** [comment]
Not every time, the same project will not have a problem on the Mac, but it will have a problem on windows. I don't know why the error is `does not export org.junit.platform.commons.logging to unnamed module @ 0x101df177`. it should be `does not export org.junit.platform.commons.logging to org.junit.jupiter.engine.config`.

**Comment by monkey1993** [comment]
project     https://github.com/keimons/deepjson

**Comment by sormuras** [comment]
Interesting: Java `1.6`, `1.7`, `9`, and `11` is configured.

> What's the actual target of project deepjson? Why do you configure so many different versions in so many different places?

May be that is why IDEA gets confused...

**Comment by monkey1993** [comment]
Downward compatible with Java 1.6, MethodHandles is provided in Java 1.7, and module-info is provided in Java 9. Compile different java files using 1.6, 1.7 and 9 respectively.The operating environment for error reporting is java 11. Perhaps junit-jupiter-engine is recognized as an unnamed module. However, when I delete the module-info.java file under test and discard modularization, everything is normal.

**Comment by monkey1993** [comment]
Not command-line. IDEA debug.

**Comment by sormuras** [comment]
Perhaps, this IDEA bug was already fixed and will ship with their upcoming `2021.3 EAP` builds, soon: https://youtrack.jetbrains.com/issue/IDEA-277330

**Comment by monkey1993** [comment]
`exports org.junit.platform.commons.logging to org.junit.jupiter.engine`

> 也许，这个 IDEA 错误已经修复`2021.3 EAP`，很快就会随他们即将发布的版本一起发布：[https](https://youtrack.jetbrains.com/issue/IDEA-277330) : [//youtrack.jetbrains.com/issue/IDEA-277330](https://youtrack.jetbrains.com/issue/IDEA-277330)

I see, it's the same problem. I also recently upgraded 2021.2, thanks.
