### ISSUE TITLE
PreconditionViolationException: Launcher session has already been closed

### ISSUE THREAD

**Issue by j1cs** [junit-team/junit5#2795]
## Steps to reproduce
I created a project with the cucumber archetype which has the junit5 suite.
```
mvn archetype:generate                      \
   "-DarchetypeGroupId=io.cucumber"           \
   "-DarchetypeArtifactId=cucumber-archetype" \
   "-DarchetypeVersion=7.0.0"               \
   "-DgroupId=hellocucumber"                  \
   "-DartifactId=hellocucumber"               \
   "-Dpackage=hellocucumber"                  \
   "-Dversion=1.0.0-SNAPSHOT"                 \
   "-DinteractiveMode=false"
```
then I added the following profile:
```
<profile>
    <id>dd-civisibility</id>
    <activation>
        <activeByDefault>false</activeByDefault>
    </activation>
    <properties>
        <dd.java.agent.arg>
            -javaagent:${settings.localRepository}/com/datadoghq/dd-java-agent/0.90.0/dd-java-agent-0.90.0.jar
            -Ddd.service=hellocucumber
            -Ddd.prioritization.type=ENSURE_TRACE
            -Ddd.jmxfetch.enabled=false
            -Ddd.integrations.enabled=false
            -Ddd.integration.junit.enabled=true
        </dd.java.agent.arg>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.datadoghq</groupId>
            <artifactId>dd-java-agent</artifactId>
            <version>0.90.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>${dd.java.agent.arg}</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</profile>
```

When adding a profile to send data to datadog the command `mvn test -Pdd-civisibility` shows the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project hellocucumber: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/jcuzmar/Development/tests/hellocucumber/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:733)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
...
```
And the report says:
``` 
# Created at 2021-12-14T11:24:13.474
java.lang.ExceptionInInitializerError
	at org.junit.platform.launcher.core.DefaultLauncherSession.close(DefaultLauncherSession.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:47)
	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)
	at org.apache.maven.surefire.api.util.DefaultScanResult.applyFilter(DefaultScanResult.java:102)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:147)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: org.junit.platform.commons.PreconditionViolationException: Launcher session has already been closed
	at org.junit.platform.launcher.core.DefaultLauncherSession$ClosedLauncher.registerTestExecutionListeners(DefaultLauncherSession.java:109)
	at org.junit.platform.launcher.core.DefaultLauncherSession$ClosedLauncher.<init>(DefaultLauncherSession.java:100)
	at org.junit.platform.launcher.core.DefaultLauncherSession$ClosedLauncher.<clinit>(DefaultLauncherSession.java:97)
	... 10 more
```

Sample project:   
https://github.com/j1cs/cucumber-junit5-datadog-error

Just clone it and run `mvn clean test -Pdd-civisibility`

thanks in advance.

**Comment by mpkorstanje** [comment]
You may want to raise this issue with DataDog. It would appear that their instrumentation is misbehaving.

Looking at their agent, it is written and tested against version 1.3 of the JUnit Platform. To make the Suite Engine possible some of the internals were changed and I wouldn't be surprised if that broke some of their implicit assumptions.

https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/junit-5.3/junit-5.3.gradle#L12

**Comment by mpkorstanje** [comment]
Ah. No. It wasn't the introduction of the  suite engine but rather the launcher session. After the init of any class implementing the `Launcher` interface the `registerTestExecutionListeners` method is called on that instance. This doesn't work for the `ClosedLauncher` for obvious reasons. 

https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Instrumentation.java#L58

**Comment by j1cs** [comment]
Perfect. Thank for your clarification. We should close the issue then, right?

**Comment by mpkorstanje** [comment]
I'm not part of the JUnit team. But feel free to do so.

**Comment by sormuras** [comment]
> We should close the issue then, right?

Right. (-:
