### ISSUE TITLE
JUnit Platform standalone ConsoleLauncher does not support `@Suite` classes

### ISSUE THREAD

**Issue by apathan123** [junit-team/junit5#2813]
I am trying to run Test Suite using JUnit 5.

Individual file runs fine. But the Test Suite is not running when executed from command line.

I am using `junit-platform-console-standalone-1.6.0.jar` to run tests.

My Test class:

```java
package demo;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;

public class TestDemoClass1 {

    @Test
    public void test1() throws Exception {
        System.out.println("Test 1 from DemoClass 1");
    }

    @Test
    public void test2() throws Exception {
        System.out.println("Test2 from DemoClass 1");
    }
```

My Suite class:

```java
package demo;

import org.junit.platform.suite.api.SelectClasses;
import org.junit.platform.suite.api.Suite;

@Suite
@SelectClasses({ TestDemoClass1.class })
public class TestSuite {

}
```

The command I am using to run from command lines: 

```
java -jar target/junit-platform-console-standalone-1.6.0.jar -cp .;target/test-classes/ -c demo.TestSuite  
```

Output of this command is:

```
Thanks for using JUnit! Support its development at https://junit.org/sponsoring

←[36m.←[0m
←[36m+--←[0m ←[36mJUnit Jupiter←[0m ←[32m[OK]←[0m
←[36m'--←[0m ←[36mJUnit Vintage←[0m ←[32m[OK]←[0m

Test run finished after 72 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
```

It says no tests found. If same java command is use with the test class it runs fine

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
The `@Suite` test engine was introduced in JUnit 5.8, so you cannot expect it work out of the box with JUnit 5.6.

However, the [JUnit Platform Suite Engine](https://junit.org/junit5/docs/current/user-guide/#junit-platform-suite-engine) is not bundled with the standalone Console Launcher.

So you will need to download the appropriate suite engine artifacts and place them on the classpath in order for `@Suite` classes to be detected and supported.

Suite Engine Artifacts

- junit-platform-suite-api
- junit-platform-suite-commons
- junit-platform-suite-engine

Please try that out and let us know if it works for you.

**Comment by sbrannen** [comment]
> However, the [JUnit Platform Suite Engine](https://junit.org/junit5/docs/current/user-guide/#junit-platform-suite-engine) is not bundled with the standalone Console Launcher.

@junit-team/junit-lambda, what do you think about including the JUnit Platform Suite Engine in the standalone console launcher, alongside Jupiter and Vintage?

**Comment by apathan123** [comment]
> * junit-platform-suite-engine

@sbrannen Thanks for the pointer. I did change Juiter version to 5.8.1. and also added the below artefacts in teh classpath.
    junit-platform-suite-api
    junit-platform-suite-commons
    junit-platform-suite-engine
Executing this command now:
 `java -jar target/junit-platform-console-standalone-1.8.2.jar -cp .;target/lib/junit-platform-suite-engine-1.8.2.jar;target/test-classes/ -c demo.TestSuite`

but it is throwign new exception which I could not solve myself :

> org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-platform-suite' failed to discover tests
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:66)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:58)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.replaceThreadContextClassLoaderAndInvoke(CustomContextClassLoaderExecutor.java:41)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:31)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:58)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:95)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:73)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:50)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:43)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:37)
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'demo.TestSuite'] resolution failed
        at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
        at org.junit.platform.suite.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:41)
        at org.junit.platform.suite.engine.SuiteTestEngine.discover(SuiteTestEngine.java:58)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
        ... 17 more
Caused by: java.lang.NoClassDefFoundError: org/junit/platform/suite/api/Suite
        at org.junit.platform.suite.engine.IsSuiteClass.hasSuiteAnnotation(IsSuiteClass.java:31)
        at org.junit.platform.suite.engine.IsSuiteClass.test(IsSuiteClass.java:27)
        at org.junit.platform.suite.engine.ClassSelectorResolver.resolve(ClassSelectorResolver.java:49)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: org.junit.platform.suite.api.Suite
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:855)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 38 more

**Comment by sormuras** [comment]
Can't use `java -jar ...` like that. It only puts that one JAR file (and those listed within the JAR file's manifest) on the classpath.

Now, you need to resort to: `java -cp ... org.junit.platform.console.ConsoleLauncher [ARGS]`

**Comment by apathan123** [comment]
> Can't use `java -jar ...` like that. It only puts that one JAR file (and those listed within the JAR file's manifest) on the classpath.
> 
> Now, you need to resort to: `java -cp ... org.junit.platform.console.ConsoleLauncher [ARGS]`
> 
> For example:
> 
> ```
> java
>  --class-path target/junit-platform-console-standalone-1.8.2.jar;target/lib/junit-platform-suite-engine-1.8.2.jar;target/test-classes;.
>  org.junit.platform.console.ConsoleLauncher
>  --select-class demo.TestSuite
> ```

Changign to java --cp... gives same error. no chnage is stack trace.

**Comment by sbrannen** [comment]
The stack trace says...

>  Caused by: java.lang.ClassNotFoundException: org.junit.platform.suite.api.Suite

So that means you need to have `junit-platform-suite-api` on the classpath, as I mentioned in https://github.com/junit-team/junit5/issues/2813#issuecomment-1017545654.

**Comment by apathan123** [comment]
@sormuras @sbrannen Thanks for the detailed guidance! I added all the jars mentioned above in my command with their actual path. I dont have main classes to be compiled so nothign to add there. Final command looks like this. Error has changed though
`java  --class-path .;target/lib/junit-platform-suite-commons-1.8.2.jar;target/lib/junit-platform-suite-api-1.8.2.jar;target/lib/junit-platform-suite-engine-1.8.2.jar;target/test-classes/;target/junit-platform-console-standalone-1.8.2.jar org.junit.platform.console.ConsoleLauncher --select-class demo.TestSuite                            `

> org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-platform-suite' failed to discover tests
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:66)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:58)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:58)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:95)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:73)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:50)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:43)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:37)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-platform-suite' failed to discover tests
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:99)
        at org.junit.platform.suite.engine.SuiteLauncher.discover(SuiteLauncher.java:55)
        at org.junit.platform.suite.engine.SuiteTestDescriptor.discover(SuiteTestDescriptor.java:105)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.junit.platform.suite.engine.DiscoverySelectorResolver.discoverSuites(DiscoverySelectorResolver.java:36)
        at org.junit.platform.suite.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:42)
        at org.junit.platform.suite.engine.SuiteTestEngine.discover(SuiteTestEngine.java:58)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
        ... 16 more
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'demo.TestSuite'] resolution failed
        at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
        at org.junit.platform.suite.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:41)
        at org.junit.platform.suite.engine.SuiteTestEngine.discover(SuiteTestEngine.java:58)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
        ... 35 more
Caused by: org.junit.platform.commons.PreconditionViolationException: Configuration error: The suite configuration may not contain a cycle [[engine:junit-platform-suite]/[suite:demo.TestSuite]/[engine:junit-platform-suite]/[suite:demo.TestSuite]]
        at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:296)
        at org.junit.platform.suite.engine.SuiteTestDescriptor.requireNoCycles(SuiteTestDescriptor.java:74)
        at org.junit.platform.suite.engine.SuiteTestDescriptor.<init>(SuiteTestDescriptor.java:58)
        at org.junit.platform.suite.engine.ClassSelectorResolver.newSuiteDescriptor(ClassSelectorResolver.java:97)
        at org.junit.platform.suite.engine.ClassSelectorResolver.lambda$resolve$0(ClassSelectorResolver.java:53)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.createAndAdd(EngineDiscoveryRequestResolution.java:246)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:209)
        at org.junit.platform.suite.engine.ClassSelectorResolver.resolve(ClassSelectorResolver.java:53)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
        ... 40 more

**Comment by sbrannen** [comment]
You have a cycle in your suite configuration that you need to sort out.

> Caused by: org.junit.platform.commons.PreconditionViolationException: Configuration error: The suite configuration may not contain a cycle [[engine:junit-platform-suite]/[suite:demo.TestSuite]/[engine:junit-platform-suite]/[suite:demo.TestSuite]]

**Comment by apathan123** [comment]
Awesome! This is resolved after removing @Tag annotations from Suite.  Sample success output below. Thanks a ton for swift reponses! Adding all those jars in classpath wasnt mentioned anywhere so took me some time to get to the solution!
Thanks again!!!

> Test 1 from DemoClass 1
Test2 from DemoClass 1
After All from DemoClass 1
Test 1 from DemoClass 2
Test2 from DemoClass 2
After All from DemoClass 2

Thanks for using JUnit! Support its development at https://junit.org/sponsoring

←[36m.←[0m
←[36m+--←[0m ←[36mJUnit Platform Suite←[0m ←[32m[OK]←[0m
←[36m| '--←[0m ←[36mTestSuite←[0m ←[32m[OK]←[0m
←[36m|   '--←[0m ←[36mJUnit Jupiter←[0m ←[32m[OK]←[0m
←[36m|     +--←[0m ←[36mTestDemoClass1←[0m ←[32m[OK]←[0m
←[36m|     | +--←[0m ←[34mtest1()←[0m ←[32m[OK]←[0m
←[36m|     | '--←[0m ←[34mtest2()←[0m ←[32m[OK]←[0m
←[36m|     '--←[0m ←[36mTestDemoClass2←[0m ←[32m[OK]←[0m
←[36m|       +--←[0m ←[34mtest1()←[0m ←[32m[OK]←[0m
←[36m|       '--←[0m ←[34mtest2()←[0m ←[32m[OK]←[0m
←[36m+--←[0m ←[36mJUnit Jupiter←[0m ←[32m[OK]←[0m
←[36m'--←[0m ←[36mJUnit Vintage←[0m ←[32m[OK]←[0m

Test run finished after 234 ms
[         7 containers found      ]
[         0 containers skipped    ]
[         7 containers started    ]
[         0 containers aborted    ]
[         7 containers successful ]
[         0 containers failed     ]
[         4 tests found           ]
[         0 tests skipped         ]
[         4 tests started         ]
[         0 tests aborted         ]
[         4 tests successful      ]
[         0 tests failed          ]

**Comment by sbrannen** [comment]
Glad to hear you got it working, @apathan123, and thanks for letting us know.

**Comment by sbrannen** [comment]
Reopening since this might be addressed by #2814.
