### ISSUE TITLE
CI builds time out on Mac OS

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2859]
In recent weeks, the CI builds were hit by timeouts when trying to download artifacts from external sources, for example from https://archive.apache.org/dist/maven/maven-3/

A stacktrace reads like:
```
    java.io.UncheckedIOException: download failed
        at app//de.sormuras.bartholdy.Bartholdy.download(Bartholdy.java:61)
        at app//de.sormuras.bartholdy.Bartholdy.install(Bartholdy.java:72)
        at app//de.sormuras.bartholdy.Bartholdy.install(Bartholdy.java:66)
        at app//de.sormuras.bartholdy.tool.Maven.install(Maven.java:17)
        at app//platform.tooling.support.Request.maven(Request.java:47)
        at app//platform.tooling.support.tests.MultiReleaseJarTests.mvn(MultiReleaseJarTests.java:84)
        at app//platform.tooling.support.tests.MultiReleaseJarTests.checkDefault(MultiReleaseJarTests.java:68)

        Caused by:
        java.net.ConnectException: Operation timed out
            at java.base@17.0.2/sun.nio.ch.Net.connect0(Native Method)
            at java.base@17.0.2/sun.nio.ch.Net.connect(Net.java:579)
            at java.base@17.0.2/sun.nio.ch.Net.connect(Net.java:568)
            at java.base@17.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
            at java.base@17.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
            at java.base@17.0.2/java.net.Socket.connect(Socket.java:633)
            at java.base@17.0.2/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
            at java.base@17.0.2/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
            at java.base@17.0.2/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
            at java.base@17.0.2/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
            at java.base@17.0.2/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
            at java.base@17.0.2/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
            at java.base@17.0.2/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
            at java.base@17.0.2/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
            at java.base@17.0.2/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
            at java.base@17.0.2/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
            at java.base@17.0.2/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
            at java.base@17.0.2/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
            at java.base@17.0.2/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
            at java.base@17.0.2/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
            at java.base@17.0.2/java.net.URL.openStream(URL.java:1161)
            at app//de.sormuras.bartholdy.Bartholdy.download(Bartholdy.java:55)
            ... 6 more
```

❌ Timed out with:
https://github.com/junit-team/junit5/runs/5626012955?check_suite_focus=true
```
 + Eclipse Temurin JDK 17.0.2+8
     | Location:           /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.2-8/x64/Contents/Home
     | Language Version:   17
     | Vendor:             Eclipse Temurin
     | Architecture:       x86_64
     | Is JDK:             true
     | Detected by:        Current JVM
```

✅ Worked with Oracle JDK:
https://github.com/junit-team/junit5/runs/5630294877?check_suite_focus=true
```
 + Oracle JDK 17.0.2+8-LTS-86
     | Location:           /Users/runner/hostedtoolcache/Java_jdkfile_jdk/17/x64/Contents/Home
     | Language Version:   17
     | Vendor:             Oracle
     | Architecture:       x86_64
     | Is JDK:             true
     | Detected by:        Current JVM
```

**Comment by sormuras** [comment]
Related? https://stackoverflow.com/questions/71174668/nginx-sometimes-fails-tls-passthrough-to-java-17-application

**Comment by AQS-DTheuke** [comment]
I don't think that it's related (but I'm not sure). The linked SO question is for incoming requests, this issue is about outgoing requests.

**Comment by marcphilipp** [comment]
This PR should fix it: https://github.com/junit-team/junit5/pull/2867 🤞
