### ISSUE TITLE
Surefire Plugin Fails

### ISSUE THREAD

**Issue by brcolow** [junit-team/junit5#288]
I am attempting to run my test suite with JUnit 5 via the maven-surefire-plugin as done in the sample Maven consumer. However, I am currently running up against the following exception:

````

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.297 s
[INFO] Finished at: 2016-05-28T23:37:02-07:00
[INFO] Final Memory: 42M/655M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] org.junit.gen5.commons.util.PreconditionViolationException: Class must not be null
[ERROR] at org.junit.gen5.commons.util.Preconditions.condition(Preconditions.java:153)
[ERROR] at org.junit.gen5.commons.util.Preconditions.notNull(Preconditions.java:84)
[ERROR] at org.junit.gen5.commons.util.Preconditions.notNull(Preconditions.java:55)
[ERROR] at org.junit.gen5.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:437)
[ERROR] at org.junit.gen5.commons.util.ReflectionUtils.getSuperclassMethods(ReflectionUtils.java:524)
[ERROR] at org.junit.gen5.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:445)
[ERROR] at org.junit.gen5.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:427)
[ERROR] at org.junit.gen5.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:418)
[ERROR] at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.toJavaMethodSource(JUnit4TestDescriptor.java:128)
[ERROR] at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.toJavaSource(JUnit4TestDescriptor.java:112)
[ERROR] at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.<init>(JUnit4TestDescriptor.java:53)
[ERROR] at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.addChildrenRecursively(TestClassRequestResolver.java:110)
[ERROR] at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.createCompleteRunnerTestDescriptor(TestClassRequestResolver.java:94)
[ERROR] at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.determineRunnerTestDescriptor(TestClassRequestResolver.java:70)
[ERROR] at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.addRunnerTestDescriptor(TestClassRequestResolver.java:63)
[ERROR] at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.populateEngineDescriptorFrom(TestClassRequestResolver.java:57)
[ERROR] at org.junit.gen5.engine.junit4.discovery.JUnit4DiscoveryRequestResolver.populateEngineDescriptor(JUnit4DiscoveryRequestResolver.java:83)
[ERROR] at org.junit.gen5.engine.junit4.discovery.JUnit4DiscoveryRequestResolver.resolve(JUnit4DiscoveryRequestResolver.java:46)
[ERROR] at org.junit.gen5.engine.junit4.JUnit4TestEngine.discover(JUnit4TestEngine.java:47)
[ERROR] at org.junit.gen5.launcher.main.DefaultLauncher.discoverRoot(DefaultLauncher.java:101)
[ERROR] at org.junit.gen5.launcher.main.DefaultLauncher.discover(DefaultLauncher.java:76)
[ERROR] at org.junit.gen5.surefire.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:37)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:98)
[ERROR] at org.junit.gen5.surefire.JUnitGen5Provider.scanClasspath(JUnitGen5Provider.java:65)
[ERROR] at org.junit.gen5.surefire.JUnitGen5Provider.invoke(JUnitGen5Provider.java:60)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
org.junit.gen5.commons.util.PreconditionViolationException: Class must not be null
        at org.junit.gen5.commons.util.Preconditions.condition(Preconditions.java:153)
        at org.junit.gen5.commons.util.Preconditions.notNull(Preconditions.java:84)
        at org.junit.gen5.commons.util.Preconditions.notNull(Preconditions.java:55)
        at org.junit.gen5.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:437)
        at org.junit.gen5.commons.util.ReflectionUtils.getSuperclassMethods(ReflectionUtils.java:524)
        at org.junit.gen5.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:445)
        at org.junit.gen5.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:427)
        at org.junit.gen5.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:418)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.toJavaMethodSource(JUnit4TestDescriptor.java:128)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.toJavaSource(JUnit4TestDescriptor.java:112)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.<init>(JUnit4TestDescriptor.java:53)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.addChildrenRecursively(TestClassRequestResolver.java:110)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.createCompleteRunnerTestDescriptor(TestClassRequestResolver.java:94)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.determineRunnerTestDescriptor(TestClassRequestResolver.java:70)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.addRunnerTestDescriptor(TestClassRequestResolver.java:63)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.populateEngineDescriptorFrom(TestClassRequestResolver.java:57)
        at org.junit.gen5.engine.junit4.discovery.JUnit4DiscoveryRequestResolver.populateEngineDescriptor(JUnit4DiscoveryRequestResolver.java:83)
        at org.junit.gen5.engine.junit4.discovery.JUnit4DiscoveryRequestResolver.resolve(JUnit4DiscoveryRequestResolver.java:46)
        at org.junit.gen5.engine.junit4.JUnit4TestEngine.discover(JUnit4TestEngine.java:47)
        at org.junit.gen5.launcher.main.DefaultLauncher.discoverRoot(DefaultLauncher.java:101)
        at org.junit.gen5.launcher.main.DefaultLauncher.discover(DefaultLauncher.java:76)
        at org.junit.gen5.surefire.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:37)
        at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:98)
        at org.junit.gen5.surefire.JUnitGen5Provider.scanClasspath(JUnitGen5Provider.java:65)
        at org.junit.gen5.surefire.JUnitGen5Provider.invoke(JUnitGen5Provider.java:60)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
org.junit.gen5.commons.util.PreconditionViolationException: Class must not be null
        at org.junit.gen5.commons.util.Preconditions.condition(Preconditions.java:153)
        at org.junit.gen5.commons.util.Preconditions.notNull(Preconditions.java:84)
        at org.junit.gen5.commons.util.Preconditions.notNull(Preconditions.java:55)
        at org.junit.gen5.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:437)
        at org.junit.gen5.commons.util.ReflectionUtils.getSuperclassMethods(ReflectionUtils.java:524)
        at org.junit.gen5.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:445)
        at org.junit.gen5.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:427)
        at org.junit.gen5.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:418)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.toJavaMethodSource(JUnit4TestDescriptor.java:128)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.toJavaSource(JUnit4TestDescriptor.java:112)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.<init>(JUnit4TestDescriptor.java:53)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.addChildrenRecursively(TestClassRequestResolver.java:110)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.createCompleteRunnerTestDescriptor(TestClassRequestResolver.java:94)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.determineRunnerTestDescriptor(TestClassRequestResolver.java:70)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.addRunnerTestDescriptor(TestClassRequestResolver.java:63)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.populateEngineDescriptorFrom(TestClassRequestResolver.java:57)
        at org.junit.gen5.engine.junit4.discovery.JUnit4DiscoveryRequestResolver.populateEngineDescriptor(JUnit4DiscoveryRequestResolver.java:83)
        at org.junit.gen5.engine.junit4.discovery.JUnit4DiscoveryRequestResolver.resolve(JUnit4DiscoveryRequestResolver.java:46)
        at org.junit.gen5.engine.junit4.JUnit4TestEngine.discover(JUnit4TestEngine.java:47)
        at org.junit.gen5.launcher.main.DefaultLauncher.discoverRoot(DefaultLauncher.java:101)
        at org.junit.gen5.launcher.main.DefaultLauncher.discover(DefaultLauncher.java:76)
        at org.junit.gen5.surefire.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:37)
        at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:98)
        at org.junit.gen5.surefire.JUnitGen5Provider.scanClasspath(JUnitGen5Provider.java:65)
        at org.junit.gen5.surefire.JUnitGen5Provider.invoke(JUnitGen5Provider.java:60)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.RuntimeException: There was an error in the forked process
org.junit.gen5.commons.util.PreconditionViolationException: Class must not be null
        at org.junit.gen5.commons.util.Preconditions.condition(Preconditions.java:153)
        at org.junit.gen5.commons.util.Preconditions.notNull(Preconditions.java:84)
        at org.junit.gen5.commons.util.Preconditions.notNull(Preconditions.java:55)
        at org.junit.gen5.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:437)
        at org.junit.gen5.commons.util.ReflectionUtils.getSuperclassMethods(ReflectionUtils.java:524)
        at org.junit.gen5.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:445)
        at org.junit.gen5.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:427)
        at org.junit.gen5.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:418)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.toJavaMethodSource(JUnit4TestDescriptor.java:128)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.toJavaSource(JUnit4TestDescriptor.java:112)
        at org.junit.gen5.engine.junit4.descriptor.JUnit4TestDescriptor.<init>(JUnit4TestDescriptor.java:53)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.addChildrenRecursively(TestClassRequestResolver.java:110)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.createCompleteRunnerTestDescriptor(TestClassRequestResolver.java:94)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.determineRunnerTestDescriptor(TestClassRequestResolver.java:70)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.addRunnerTestDescriptor(TestClassRequestResolver.java:63)
        at org.junit.gen5.engine.junit4.discovery.TestClassRequestResolver.populateEngineDescriptorFrom(TestClassRequestResolver.java:57)
        at org.junit.gen5.engine.junit4.discovery.JUnit4DiscoveryRequestResolver.populateEngineDescriptor(JUnit4DiscoveryRequestResolver.java:83)
        at org.junit.gen5.engine.junit4.discovery.JUnit4DiscoveryRequestResolver.resolve(JUnit4DiscoveryRequestResolver.java:46)
        at org.junit.gen5.engine.junit4.JUnit4TestEngine.discover(JUnit4TestEngine.java:47)
        at org.junit.gen5.launcher.main.DefaultLauncher.discoverRoot(DefaultLauncher.java:101)
        at org.junit.gen5.launcher.main.DefaultLauncher.discover(DefaultLauncher.java:76)
        at org.junit.gen5.surefire.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:37)
        at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:98)
        at org.junit.gen5.surefire.JUnitGen5Provider.scanClasspath(JUnitGen5Provider.java:65)
        at org.junit.gen5.surefire.JUnitGen5Provider.invoke(JUnitGen5Provider.java:60)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:584)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:460)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:229)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:201)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
````

The configuration for maven-surefire-plugin in my `pom.xml` is:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit</groupId>
                        <artifactId>surefire-junit5</artifactId>
                        <version>5.0.0-SNAPSHOT</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <!-- Needed for jacoco -->
                    <argLine>${surefireArgLine}</argLine>
                    <skipTests>${skip.unit.tests}</skipTests>
                    <excludedGroups>${surefire.excluded.groups}</excludedGroups>
                    <additionalClasspathElements>
                        <additionalClasspathElement>${project.basedir}/src/main/config</additionalClasspathElement>
                        <additionalClasspathElement>${java.home}/lib/ext/jfxrt.jar</additionalClasspathElement>
                    </additionalClasspathElements>
                    <properties>
                        <property>
                            <name>listener</name>
                            <value>net.blah.TestRunListener</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>
```

Let me know if you need any more information. Thanks very much.

**Comment by marcphilipp** [comment]
This is not an open source project, is it? If not, this happens when processing a JUnit 4 test. Maybe you can strip down your project to a single JUnit 4 test and still reproduce the issue?

I suspect this might be a ClassLoader-related issue. Can you try to omit the `additionalClasspathEntries` from the POM and see if that changes something?

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
@brcolow,

We believe that the problem has been resolved in 83c5e98d849e4f51bc28f13e2b85060dd46edfa8.

Can you please try out the next snapshot build and let us know if your problem has in fact been resolved?

Thanks in advance!

**Comment by brcolow** [comment]
@sbrannen This fixed my issue completely. Thank you so much for the prompt response and fix! I am looking forward to testing out the new features of JUnit 5. Thanks for all the devs hard work.

**Comment by sbrannen** [comment]
Awesome!

Thanks for letting us know that the _fix_ worked for you.

And have fun with JUnit 5! 😄
