### ISSUE TITLE
TempDir deletion throws StackOverflowError

### ISSUE THREAD

**Issue by andrewparmet** [junit-team/junit5#2883]
I have a unit test that creates some files in a temporary directory. Notably it's a Docker container that is creating the files. The test passes locally on my machine (running on a Mac) but fails in GitHub actions: https://github.com/andrewparmet/buf-gradle-plugin/runs/5959677186?check_suite_focus=true with a StackOverflowError as it's trying to clean up:

```
java.lang.StackOverflowError
	at java.base/sun.nio.fs.UnixNativeDispatcher.unlink0(Native Method)
	at java.base/sun.nio.fs.UnixNativeDispatcher.unlink(UnixNativeDispatcher.java:156)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:236)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1142)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.resetPermissionsAndTryToDeleteAgain(TempDirectory.java:250)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:238)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.visitFile(TempDirectory.java:218)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.visitFile(TempDirectory.java:199)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2725)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.resetPermissionsAndTryToDeleteAgain(TempDirectory.java:247)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:238)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:223)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:199)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2743)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)

// etc.
```

I'm also wondering what kind of IOException is triggering the recursive code, as it's [completely swallowed](https://github.com/junit-team/junit5/blob/main/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L291).

What's also interesting is that I have other tests in this project that have files generated by a Docker container and none of them fail.

## Steps to reproduce

This is pretty esoteric and I don't have a smaller example, but running the CI on the PR always reproduces the error.

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.8.2
 - Build Tool/IDE: Gradle 7.4.1

## Deliverables

- [ ] The PR should succeed!

Thanks!

**Comment by andrewparmet** [comment]
I can probably use https://github.com/junit-team/junit5/issues/2159 to get away with this without fixing the problem. Is there a snapshot repository I can use?

**Comment by sormuras** [comment]
> Is there a snapshot repository I can use?

There used to be a description in the README of the repository -- which seems to be gone for good. 🤔 

Here are "code-as-documentation" variants using snapshot builds from JUnit's sample projects:

- [junit5-jupiter-starter-gradle](https://github.com/junit-team/junit5-samples/blob/main/junit5-jupiter-starter-gradle/build-SNAPSHOT.gradle)
- [junit5-jupiter-starter-maven](https://github.com/junit-team/junit5-samples/blob/main/junit5-jupiter-starter-maven/pom-SNAPSHOT.xml)

**Comment by andrewparmet** [comment]
@sormuras I found a reference in the docs: https://junit.org/junit5/docs/current/user-guide/#dependency-metadata

**Comment by marcphilipp** [comment]
The current code should stop retrying for directories already being retried:
https://github.com/junit-team/junit5/blob/8d8609a8005b40d51b2364983f9d5ef12f888173/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L302

I'll take a stab at this.

**Comment by marcphilipp** [comment]
@andrewparmet I've just merged a fix. Could you please try out the latest snapshot?

**Comment by andrewparmet** [comment]
I tried the snapshot and the build no longer fails with a StackOverflowError - now I see the actual failure.

Here's the build: https://github.com/andrewparmet/buf-gradle-plugin/runs/5962954761?check_suite_focus=true

And here's the failure:
```
java.io.IOException: Failed to delete temp directory /tmp/junit15838421272742090151. The following paths could not be deleted (see suppressed exceptions for details): , build, build/bufbuild, build/bufbuild/generated, build/bufbuild/generated/java, build/bufbuild/generated/java/com, build/bufbuild/generated/java/com/parmet, build/bufbuild/generated/java/com/parmet/buf, build/bufbuild/generated/java/com/parmet/buf/test, build/bufbuild/generated/java/com/parmet/buf/test/v1, build/bufbuild/generated/java/com/parmet/buf/test/v1/Test.java

...

        Suppressed: java.nio.file.DirectoryNotEmptyException: /tmp/junit15838421272742090151
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:246)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:293)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:288)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:264)
		at java.base/java.nio.file.Files.walkFileTree(Files.java:2828)
		at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:264)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:249)
		... 77 more
	Suppressed: java.nio.file.DirectoryNotEmptyException: /tmp/junit15838421272742090151/build
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:246)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:293)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:288)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:264)
		at java.base/java.nio.file.Files.walkFileTree(Files.java:2828)
		at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:264)
		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:249)
		... 77 more

... all the way down to:

        Suppressed: java.nio.file.AccessDeniedException: /tmp/junit15838421272742090151/build/bufbuild/generated/java/com/parmet/buf/test/v1/Test.java

```

Looks like TempDir tries to give itself permission. Is this potentially a bug or am I doing something unsupported that's a known limitation?

**Comment by marcphilipp** [comment]
Yes, it does try to give itself permissions. Could you please check the file's owner and create a new issue with your findings?
