### ISSUE TITLE
OpenTestReportGeneratingListener: Trying to output second root, <e:started>

### ISSUE THREAD

**Issue by kelunik** [junit-team/junit5#3008]
Version: 5.9.0

## Steps to reproduce

Launch a test execution inside another test with reporting enabled via Maven Surefire:

```java
   @Test
   public void testFoobar() {
      System.setProperty("junit.platform.reporting.open.xml.enabled", "true");

      LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder
         .request()
         .selectors(DiscoverySelectors.selectPackage("foo.bar"))
         .build();

      Launcher launcher = LauncherFactory.create();
      launcher.discover(request);

      launcher.execute(request);
   }
 ```

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.9.0
 - Build Tool/IDE: Maven Surefire

## Stacktrace
```
  javax.xml.stream.XMLStreamException: Trying to output second root, <e:started>
```

```
java.lang.RuntimeException: Failed to write event: Element{domElement=[e:started: null]}
	at org.junit.platform.reporting.shadow.org.opentest4j.reporting.events.api.DefaultDocumentWriter.append(DefaultDocumentWriter.java:118)
	at org.junit.platform.reporting.shadow.org.opentest4j.reporting.events.api.DefaultDocumentWriter.append(DefaultDocumentWriter.java:42)
	at org.junit.platform.reporting.open.xml.OpenTestReportGeneratingListener.reportStarted(OpenTestReportGeneratingListener.java:177)
	at org.junit.platform.reporting.open.xml.OpenTestReportGeneratingListener.executionStarted(OpenTestReportGeneratingListener.java:173)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$executionStarted$6(CompositeTestExecutionListener.java:60)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$notifyEach$19(CompositeTestExecutionListener.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.notifyEach(CompositeTestExecutionListener.java:93)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.executionStarted(CompositeTestExecutionListener.java:60)
	at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionStarted(ExecutionListenerAdapter.java:46)
	at org.junit.platform.launcher.core.CompositeEngineExecutionListener.lambda$executionStarted$4(CompositeEngineExecutionListener.java:50)
	at org.junit.platform.launcher.core.CompositeEngineExecutionListener.lambda$notifyEach$11(CompositeEngineExecutionListener.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.launcher.core.CompositeEngineExecutionListener.notifyEach(CompositeEngineExecutionListener.java:69)
	at org.junit.platform.launcher.core.CompositeEngineExecutionListener.executionStarted(CompositeEngineExecutionListener.java:50)
	at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionStarted(DelegatingEngineExecutionListener.java:41)
	at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.executionStarted(OutcomeDelayingEngineExecutionListener.java:53)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: net.sf.saxon.trans.XPathException: javax.xml.stream.XMLStreamException: Trying to output second root, <e:started>
	at net.sf.saxon.stax.ReceiverToXMLStreamWriter.startElement(ReceiverToXMLStreamWriter.java:91)
	at net.sf.saxon.event.NamespaceReducer.startElement(NamespaceReducer.java:74)
	at net.sf.saxon.event.ComplexContentOutputter.startContent(ComplexContentOutputter.java:641)
	at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:216)
	at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:284)
	at net.sf.saxon.dom.DOMSender.sendElement(DOMSender.java:154)
	at net.sf.saxon.dom.DOMSender.send(DOMSender.java:99)
	at net.sf.saxon.dom.DOMObjectModel.sendSource(DOMObjectModel.java:273)
	at net.sf.saxon.event.Sender.send(Sender.java:226)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:366)
	at org.junit.platform.reporting.shadow.org.opentest4j.reporting.events.api.DefaultDocumentWriter.append(DefaultDocumentWriter.java:115)
	... 25 more
```

**Comment by marcphilipp** [comment]
I tried reproducing the issue based on the junit5-jupiter-starter-maven sample project on the [`marc/junit5-3008-reproducer`](https://github.com/junit-team/junit5-samples/compare/marc/junit5-3008-reproducer) branch. Unfortunately, I did not manage to run into this error.

@kelunik Could you please take a look and check what's different in your and the sample project's setup?

**Comment by sbrannen** [comment]
I also spent some time trying to reproduce the error using Marc's branch above, but I have not been able to reproduce the error with Java 8 or Java 17.

As a side note, I would suggest you not set the property as a system property in the test.

If you want to enable Open reporting for a single `Launcher` within a test, it is best to use `.configurationParameter("junit.platform.reporting.open.xml.enabled", "true")` with the request builder.

**Comment by kelunik** [comment]
@sbrannen @marcphilipp Thank you both for giving this a try! I'll need to have a look at my case and see what's the difference / try to reduce that to something I can share. I'll also try skipping the system property and using the configuration parameter instead.

**Comment by hidraulicChicken** [comment]
Hello folks, I too encountered this error, looked for solution far and wide, but finally found the problem with the help of the sample project. What I found is that the spotbugs dependencies Saxon dependency caused the problem. Defining it like this:
`<dependency>
	<groupId>com.github.spotbugs</groupId>
	<artifactId>spotbugs</artifactId>
	<version>${maven.spotbugs.version}</version>
	<exclusions>
		<exclusion>
			<groupId>net.sf.saxon</groupId>
			<artifactId>Saxon-HE</artifactId>
		</exclusion>
	</exclusions>
</dependency>`
solved the issue. So whoever finds this, check your dependencies with mvn dependency:tree and check for saxon.
