### ISSUE TITLE
`@EnabledIf` fails for non-static local condition method with `@ParameterizedTest`

### ISSUE THREAD

**Issue by iNikem** [junit-team/junit5#3068]
I have a simple test:

```java
  @ValueSource(ints = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12})
  @ParameterizedTest
  @EnabledIf("test")
  public void param(int p) {
    Assertions.assertTrue(p > 0);
  }

  private boolean test() {
    return true;
  }
```

which fails:

```
Failed to evaluate condition [org.junit.jupiter.api.condition.EnabledIfCondition]: Cannot invoke non-static method [private boolean com.signalfx.qe.systemtests.tests.RepeatitionTest.test()] on a null target.
org.junit.jupiter.engine.execution.ConditionEvaluationException: Failed to evaluate condition [org.junit.jupiter.api.condition.EnabledIfCondition]: Cannot invoke non-static method [private boolean com.signalfx.qe.systemtests.tests.RepeatitionTest.test()] on a null target.
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluationException(ConditionEvaluator.java:81)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:69)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.lambda$evaluate$0(ConditionEvaluator.java:55)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:303)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:57)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:202)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$checkWhetherSkipped$3(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.checkWhetherSkipped(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:92)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: org.junit.platform.commons.PreconditionViolationException: Cannot invoke non-static method [private boolean com.signalfx.qe.systemtests.tests.RepeatitionTest.test()] on a null target.
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:314)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:723)
	at org.junit.jupiter.api.condition.MethodBasedCondition.invokeConditionMethod(MethodBasedCondition.java:84)
	at org.junit.jupiter.api.condition.MethodBasedCondition.lambda$evaluateExecutionCondition$1(MethodBasedCondition.java:54)
	at java.util.Optional.map(Optional.java:215)
	at org.junit.jupiter.api.condition.MethodBasedCondition.evaluateExecutionCondition(MethodBasedCondition.java:54)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:64)
	... 45 more
```

Test works fine if I remove `@EnabledIf`.

**Comment by sormuras** [comment]
> Test works fine if I remove `@EnabledIf`

Without any argument provider like `ValueSource(ints = 1)`?

> `...Cannot invoke non-static method...`

What happens if you also make `test()`:
- _package-private visible_ (i.e. remove the `private` modifier)
- `static`

**Comment by marcphilipp** [comment]
`test` needs to be `static`

**Comment by iNikem** [comment]
> `test()` needs to be `static`

Is this documented somewhere? https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-custom does not require for a method in the same class to be `static`.

**Comment by iNikem** [comment]
> > Test works fine if I remove `@EnabledIf`
> 
> Without any argument provider like `ValueSource(ints = 1)`?
> 

Duh, formatting ate that. Fixed.

> > `...Cannot invoke non-static method...`
> 
> What happens if you also make `test()`:
> 
> * _package-private visible_ (i.e. remove the `private` modifier)

Same error

> * `static`

This works

**Comment by sbrannen** [comment]
@iNikem, thanks for raising the issue.

> Is this documented somewhere? https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-custom does not require for a method in the same class to be `static`.

It's true that the condition method does not need to be `static` for a `@Test` method, but apparently it does need to be `static` for a `@ParamterizedTest` method.

The code in question is `org.junit.jupiter.api.condition.MethodBasedCondition.invokeConditionMethod(Method, ExtensionContext)`.

For the following line of code, the test instance is `null` for a `@ParameterizedTest`.

```java
Object testInstance = context.getTestInstance().orElse(null);
```

If I recall correctly, that's because a `@ParameterizedTest` is technically a _container_ instead of a _test_, and there is no test instance associated with the _container_.

So we'll either have to update the documentation to reflect this shortcoming or come up with some way to access the test instance (though that may not be possible).

**Comment by marcphilipp** [comment]
**Team decision:** Document requirement for condition methods to be `static` for `@ParameterizedTest` and other `@TestTemplate` methods.
