### ISSUE TITLE
Stop further suite discovery when encountering a cycle

### ISSUE THREAD

**Issue by killlowkey** [junit-team/junit5#3115]
# Problem
Two test classes have the annotation @Tag. To run those hoped-for tests, I wish to employ a suite approach. It worked well, if using @SelectClasses in the TestSuite class to choose the included test classes performed nicely. The following issue occurred when test classes were scanned under a specified package using @SelectPackages.
```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-platform-suite' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-platform-suite' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:97)
	at org.junit.platform.suite.engine.SuiteLauncher.discover(SuiteLauncher.java:57)
	at org.junit.platform.suite.engine.SuiteTestDescriptor.discover(SuiteTestDescriptor.java:120)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.platform.suite.engine.DiscoverySelectorResolver.discoverSuites(DiscoverySelectorResolver.java:36)
	at org.junit.platform.suite.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:42)
	at org.junit.platform.suite.engine.SuiteTestEngine.discover(SuiteTestEngine.java:58)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 13 more
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'org.example.tag.TestSuite'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:103)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.platform.suite.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:41)
	at org.junit.platform.suite.engine.SuiteTestEngine.discover(SuiteTestEngine.java:58)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 32 more
Caused by: org.junit.platform.commons.PreconditionViolationException: Configuration error: The suite configuration may not contain a cycle [[engine:junit-platform-suite]/[suite:org.example.tag.TestSuite]/[engine:junit-platform-suite]/[suite:org.example.tag.TestSuite]]
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:314)
	at org.junit.platform.suite.engine.SuiteTestDescriptor.requireNoCycles(SuiteTestDescriptor.java:81)
	at org.junit.platform.suite.engine.SuiteTestDescriptor.<init>(SuiteTestDescriptor.java:63)
	at org.junit.platform.suite.engine.ClassSelectorResolver.newSuiteDescriptor(ClassSelectorResolver.java:97)
	at org.junit.platform.suite.engine.ClassSelectorResolver.lambda$resolve$0(ClassSelectorResolver.java:53)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.createAndAdd(EngineDiscoveryRequestResolution.java:250)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:213)
	at org.junit.platform.suite.engine.ClassSelectorResolver.resolve(ClassSelectorResolver.java:53)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:135)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:189)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:126)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:92)
	... 37 more

```

Why did  that exception happen?

# Java code

```java

package org.example.tag;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("fast")
public class FastTest {
    @Test
    public void test() {
        System.out.println("I am fast test");
    }
}
```
```java
package org.example.tag;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("slow")
public class SlowTest {
    @Test
    public void test() {
        System.out.println("I am slow test");
    }
}
```
```java
package org.example.tag;

import org.junit.platform.suite.api.IncludeTags;
import org.junit.platform.suite.api.SelectPackages;
import org.junit.platform.suite.api.Suite;

@SelectPackages("org.example.tag")
//@SelectClasses({
//        FastTest.class,
//        SlowTest.class,
//})
@IncludeTags("fast")
@Suite
public class TestSuite {
}
```

# Maven dependencies
```xml
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <version>5.9.0</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-suite-engine</artifactId>
    <version>1.9.0</version>
    <scope>test</scope>
</dependency>
```

# JDK version
```
java version "11.0.4" 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)
```

**Comment by mpkorstanje** [comment]
The suite engine maps the annotations to the [Platform Launcher API](https://junit.org/junit5/docs/current/user-guide/#launcher-api). In this API there are two distinct operations, test selection and filtering. 

The `@IncludeTags` annotation is a filter. Filtering happens after all tests are discovered - which in this case woud result in an infinite recursion.

As a work around you could add `@ExcludeEngine("junit-platform-suite")` to keep the suite from discovering itself.

@marcphilipp I do suppose that when a cycle is detected we could also quitely stop the recursion and not discover any tests.

**Comment by killlowkey** [comment]
> The suite engine maps the annotations to the [Platform Launcher API](https://junit.org/junit5/docs/current/user-guide/#launcher-api). In this API there are two distinct operations, test selection and filtering.
> 
> The `@IncludeTags` annotation is a filter. Filtering happens after all tests are discovered - which in this case woud result in an infinite recursion.
> 
> As a work around you could add `@ExcludeEngine("junit-platform-suite")` to keep the suite from discovering itself.
> 
> @marcphilipp I do suppose that when a cycle is detected we could also ignore the suite and quitely prevent the recursion.

I appreciate your response. When `@ExcludeEngines("junit-platform-suite")` is included, it works properly. I should maybe close the issue.

**Comment by mpkorstanje** [comment]
> I should maybe close the issue.

No, that's fine. I think you found something that can be improved.
