### ISSUE TITLE
@TempDir fails from command-line maven and succeeds from Eclipse

### ISSUE THREAD

**Issue by maisonobe** [junit-team/junit5#3133]
I tried to use @TempDir in a project.
It runs perfectly fine when the tests are run from within Eclipse, but fails when run from maven using the command-line.

The following two files reproduce the issue. The first file is the `pom.xml` configuration, the second file is the single test it contains:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org</groupId>
  <artifactId>tmpdir</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>bug</name>
  <properties>
    <tmpdir.maven-compiler-plugin.version>3.10.1</tmpdir.maven-compiler-plugin.version>
    <tmpdir.compiler.source>1.8</tmpdir.compiler.source>
    <tmpdir.compiler.target>1.8</tmpdir.compiler.target>
    <tmpdir.junit.version>5.9.2</tmpdir.junit.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>${tmpdir.junit.version}</version>
      <optional>false</optional>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>${tmpdir.junit.version}</version>
      <optional>false</optional>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <version>${tmpdir.junit.version}</version>
      <optional>false</optional>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${tmpdir.maven-compiler-plugin.version}</version>
        <configuration>
          <source>${tmpdir.compiler.source}</source>
          <target>${tmpdir.compiler.target}</target>
          <compilerArgument>-Xlint:deprecation</compilerArgument>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

```java
package org;

import java.nio.file.Path;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

public class NonNullTest {

    @TempDir
    public Path temporaryFolderPath;

    @Test
    public void testNonNull() {
        Assertions.assertNotNull(temporaryFolderPath);
    }
   
}
```

If I run the tests from within Eclipse (version 2022.12, on a Linux computer running Debian with Java 13 as the default JDK), everyting runs fine.

If I run the tests from the command line, I get this:
```
(lehrin) luc% mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------------< org:tmpdir >-----------------------------
[INFO] Building bug 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tmpdir ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /tmp/tempdir-bug/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ tmpdir ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tmpdir ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /tmp/tempdir-bug/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ tmpdir ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tmpdir ---
[INFO] Surefire report directory: /tmp/tempdir-bug/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.NonNullTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE!
org.NonNullTest.testNonNull()  Time elapsed: 0.007 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:301)
	at org.NonNullTest.testNonNull(NonNullTest.java:15)


Results :

Failed tests:   org.NonNullTest.testNonNull(): expected: not <null>

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.534 s
[INFO] Finished at: 2023-01-26T15:53:40+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project tmpdir: There are test failures.
[ERROR] 
[ERROR] Please refer to /tmp/tempdir-bug/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
(lehrin) luc% 
```

What happens is that the `temporaryFolderPath` path that should be non-null and set up for each tests (here a single test), is not initialized at all when run from the command line.

I tried different java versions (Java 8 and Java 17) and always got the same result.

**Comment by maisonobe** [comment]
That worked, thanks!
