### ISSUE TITLE
JUnit 5.9.3 MethodSource fails inside OSGi framework

### ISSUE THREAD

**Issue by chrisr3** [junit-team/junit5#3279]
```java
# Execution Started: testMethodSource(String) - [engine:bnd-bundle-engine]/[bundle:test-junit5-tests;1.0.0.SNAPSHOT]/[sub-engine:junit-jupiter]/[class:org.testing.junit.TestJUnit]/[test-template:testMethodSource(java.lang.String)]
# Execution Finished: testMethodSource(String) - [engine:bnd-bundle-engine]/[bundle:test-junit5-tests;1.0.0.SNAPSHOT]/[sub-engine:junit-jupiter]/[class:org.testing.junit.TestJUnit]/[test-template:testMethodSource(java.lang.String)] - TestExecutionResult [status = FAILED, throwable = org.junit.platform.commons.JUnitException: Could not load class [org.testing.junit.TestJUnit]]
org.junit.platform.commons.JUnitException: Could not load class [org.testing.junit.TestJUnit]
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$loadRequiredClass$8(MethodArgumentsProvider.java:181)
        at org.junit.platform.commons.function.Try$Failure.getOrThrow(Try.java:335)
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.loadRequiredClass(MethodArgumentsProvider.java:180)
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.findFactoryMethodByFullyQualifiedName(MethodArgumentsProvider.java:117)
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.findFactoryMethod(MethodArgumentsProvider.java:82)
        ...
Caused by: java.lang.ClassNotFoundException: org.testing.junit.TestJUnit
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:831)
        at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
        at org.junit.platform.commons.function.Try.of(Try.java:93)
        ...
```
## Steps to reproduce

Run [attached Gradle project](https://github.com/junit-team/junit5/files/11366531/test-junit.tar.gz):
```shell
$ ./gradlew clean build
```

## Context

 - Used versions (Jupiter/Vintage/Platform):
     Jupiter 5.9.3
     Platform 1.9.3
 - Build Tool/IDE:
     Gradle 8.1.1
     Java 11

**Comment by marcphilipp** [comment]
Could be a red herring but there's also a suppressed exception that could be related to #3131 or #3266:
```
org.junit.platform.commons.JUnitException: Could not load class [org.testing.junit.TestJUnit]
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$loadRequiredClass$8(MethodArgumentsProvider.java:181)
        at org.junit.platform.commons.function.Try$Failure.getOrThrow(Try.java:335)
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.loadRequiredClass(MethodArgumentsProvider.java:180)
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.findFactoryMethodByFullyQualifiedName(MethodArgumentsProvider.java:117)
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.findFactoryMethod(MethodArgumentsProvider.java:82)
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$provideArguments$1(MethodArgumentsProvider.java:59)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:110)
        at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:44)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at aQute.tester.bundle.engine.BundleDescriptor.executeChild(BundleDescriptor.java:49)
        at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$7(BundleEngine.java:120)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:120)
        at aQute.tester.bundle.engine.BundleEngine.lambda$execute$5(BundleEngine.java:100)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at aQute.tester.bundle.engine.BundleEngine.execute(BundleEngine.java:100)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at aQute.tester.junit.platform.Activator.test(Activator.java:441)
        at aQute.tester.junit.platform.Activator.automatic(Activator.java:345)
        at aQute.tester.junit.platform.Activator.run(Activator.java:217)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at aQute.launcher.Launcher.handleMainCallable(Launcher.java:465)
        at aQute.launcher.Launcher.launch(Launcher.java:438)
        at aQute.launcher.Launcher.run(Launcher.java:186)
        at aQute.launcher.Launcher.main(Launcher.java:162)
        at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
        at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
        at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
        Suppressed: org.junit.platform.commons.PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest
                at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:299)
                at org.junit.jupiter.params.ParameterizedTestExtension.lambda$provideTestTemplateInvocationContexts$5(ParameterizedTestExtension.java:98)
                at java.base/java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
                at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
                ... 87 more
Caused by: java.lang.ClassNotFoundException: org.testing.junit.TestJUnit
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:831)
        at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
        at org.junit.platform.commons.function.Try.of(Try.java:93)
        at org.junit.platform.commons.function.Try.call(Try.java:57)
        at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:794)
        at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:750)
        ... 111 more
```

**Comment by marcphilipp** [comment]
There were definitely some changes to `MethodArgumentsProvider` in 5.9.3 but I suspect the root cause for the class-loading issue is in `bnd-bundle-engine`.

@chrisr3 Could you please raise an issue with the BND folks and cross-reference it here?

**Comment by chrisr3** [comment]
Done.

My first impression after examining the exception stack trace was that JUnit was (suddenly?) expecting the test class to be found in the Application classloader:
```java
Caused by: java.lang.ClassNotFoundException: org.testing.junit.TestJUnit
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:831)
        ...
````
I would consider this to be unlikely when executed within an OSGi framework.

**Comment by marcphilipp** [comment]
With 5.9.2, putting the `getArgs()` method as a static method into another class and referencing it via `@MethodSource("com.acme.OtherClass#getArgs")` also fails with a `ClassNotFoundException`. I think following your proposal makes sense but should be applied to all call sites of `ReflectionUtils.tryToLoadClass` in Jupiter where a test class is already available. A quick search yielded `MethodBasedCondition` and `StringToCommonJavaTypesConverter`.

@chrisr3 Would you have time to submit a PR for that against `main`?

**Comment by chrisr3** [comment]
Sorry, I am unable to build JUnit because I do not have "Java Flight Recorder".

**Comment by sormuras** [comment]
> Sorry, I am unable to build JUnit because I do not have "Java Flight Recorder", and have no idea where to get it from.

Curious, which distribution of JDK 17 do you use?

**Comment by chrisr3** [comment]
> Curious, which distribution of JDK 17 do you use?
```shell
$ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed mode, sharing)
```

**Comment by kriegfrj** [comment]
> With 5.9.2, putting the `getArgs()` method as a static method into another class and referencing it via `@MethodSource("com.acme.OtherClass#getArgs")` also fails with a `ClassNotFoundException`. I think following your proposal makes sense but should be applied to all call sites of `ReflectionUtils.tryToLoadClass` in Jupiter where a test class is already available. A quick search yielded `MethodBasedCondition` and `StringToCommonJavaTypesConverter`.
> 
> @chrisr3 Would you have time to submit a PR for that against `main`?

For reference: #1987, #2104, #2106. Both of these issues were resolved without actually being completed, because they were going to be addressed in #806, but unfortunately #806 is still pending.

My proposed solution in #2106 is essentially the same as those that @chrisr3 is suggesting here.

In general, I think that using the test class' class loader would be the best solution for these types of problems. In the OSGi context, this puts the power back in the hands of the test developer because they can control which classes/packages are visible to the test class (and hence to the test class' classloader). In the case of (eg) a `@MethodSource("com.acme.OtherClass#getArgs")` reference, you simply need to make sure that your test class' bundle imports the package `com.acme` and (if we're using the test class' classloader) it then it will load.

If I have a look at this in Bnd I might be able to find a workaround, as I have for the other issues (like #2104). But my workarounds essentially involve the Bnd tester doing more and more of the class loading on JUnit's behalf in order to overcome these issues, and I think I've probably picked all the low-hanging fruit - the issues are becoming increasingly difficult to work around as they are being found increasingly deeper inside JUnit. It would be nicer and cleaner if these issues were resolved in JUnit.

**Comment by chrisr3** [comment]
> Curious, which distribution of JDK 17 do you use?

_Aha!_ I have found Java Flight Recorder in this package:
```
java-17-openjdk-jmods-17.0.6.0.10-1.fc37.x86_64
```
I had assumed that installing the package containing the pre-compiled shared objects was enough:
```
java-17-openjdk-headless-17.0.6.0.10-1.fc37.x86_64
```
As indeed it appears to be, for everything _except_ Java Flight Recorder.

**Comment by kriegfrj** [comment]
> My proposed solution in https://github.com/junit-team/junit5/pull/2106 is essentially the same as those that @chrisr3 is suggesting here.

I realise that I should have been a bit more specific.

I think that this:

> ```diff
> -               Class<?> clazz = loadRequiredClass(className);
> +               Class<?> clazz = testMethod.getDeclaringClass();
> ```

...is the best solution. There's no point loading the class when it's already been loaded.

**Comment by chrisr3** [comment]
> There's no point loading the class when it's already been loaded.

Heh, I _did_ wonder about that :wink:. But it also occurred to me that the method might exist on a parent class.

**Comment by marcphilipp** [comment]
That solution would break using a static method in another class, though. So I think using the test class' class loader to load the class would work in both cases and would be a no-op (since class loaders cache classes that have already been loaded) when `className` equals the test class.

**Comment by kriegfrj** [comment]
> But it also occurred to me that the method might exist on a parent class.

I don't think that will matter. The parent class will be visible to the subclass.

> That solution would break using a static method in another class, though. So I think using the test class' class loader to load the class would work in both cases and would be a no-op (since class loaders cache classes that have already been loaded) when `className` equals the test class.

Yes, you're right. So @chrisr3 's second implementation would work for both cases. The overhead in "reloading" the already-loaded test class for unqualified method names is small and is justified by the simplification it makes to the code.

Perhaps then we might need a usage note for OSGi users somewhere, to make sure that if you're using a fully-qualified reference to a static method in another class, your test bundle must import the package that the class lives in.

**Comment by sbrannen** [comment]
**Update**:

Work on this issue is complete; however, I cannot push to `main` due to a `protected branch hook` blocking me.

We will investigate the cause for that. In the interim, the completed work can be viewed here:

https://github.com/junit-team/junit5/compare/main...sbrannen:junit5:issues/3279_and_3292_custom_ClassLoader_arrangements

**Comment by sbrannen** [comment]
This has been merged into `main` in ebe7a02075e88c0d53e8ab7cc439e45c05a5d461 and revised in cd1b3b05a63457e3ffefb8994f2e72025363152a, 8bfe25a7f6dd89626739a442468fa208ab0e0bde, and b3f6c99e9568816268ec21917c5f5064325c013a.

Thanks again for your contributions! 👍
