### ISSUE TITLE
Support UTF-16 in generated XML test reports

### ISSUE THREAD

**Issue by sta-szek** [junit-team/junit5#350]
JUnit 5 cannot produce correct .xml report file.

While executing task `junitPlatformTest`:

```
:junitPlatformTest                                                           
cze 23, 2016 7:31:03 PM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [junit-jupiter]
Could not write XML report: D:\project\build\test-results\junit-platform\TEST-junit-jupiter.xml
javax.xml.stream.XMLStreamException: java.nio.charset.MalformedInputException: Input length = 1
        at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeAttribute(XMLStreamWriterImpl.java:553)
        at org.junit.platform.console.tasks.XmlReportWriter.writeTestcase(XmlReportWriter.java:122)
        at org.junit.platform.console.tasks.XmlReportWriter.writeTestsuite(XmlReportWriter.java:83)
        at org.junit.platform.console.tasks.XmlReportWriter.writeXmlReport(XmlReportWriter.java:66)
        at org.junit.platform.console.tasks.XmlReportWriter.writeXmlReport(XmlReportWriter.java:58)
        at org.junit.platform.console.tasks.XmlReportsWritingListener.writeXmlReportSafely(XmlReportsWritingListener.java:100)
        at org.junit.platform.console.tasks.XmlReportsWritingListener.writeXmlReportInCaseOfRoot(XmlReportsWritingListener.java:93)
        at org.junit.platform.console.tasks.XmlReportsWritingListener.executionFinished(XmlReportsWritingListener.java:87)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionFinished$23(TestExecutionListenerRegistry.java:63)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:37)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:26)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.executionFinished(TestExecutionListenerRegistry.java:63)
        at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:93)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
     rg.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:124)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
        at org.junit.platform.console.tasks.ExecuteTestsTask.executeTests(ExecuteTestsTask.java:60)
        at org.junit.platform.console.tasks.ExecuteTestsTask.lambda$execute$6(ExecuteTestsTask.java:52)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ExecuteTestsTask.execute(ExecuteTestsTask.java:52)
        at org.junit.platform.console.tasks.ConsoleTaskExecutor.executeTask(ConsoleTaskExecutor.java:38)
        at org.junit.platform.console.ConsoleRunner.execute(ConsoleRunner.java:51)
        at org.junit.platform.console.ConsoleRunner.main(ConsoleRunner.java:36)
        Suppressed: java.nio.charset.MalformedInputException: Input length = 1
                at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
                at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
                at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
                at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
                at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
                at java.io.BufferedWriter.close(BufferedWriter.java:265)
                at org.junit.platform.console.tasks.XmlReportsWritingListener.writeXmlReportSafely(XmlReportsWritingListener.java:101)
                ... 20 more        
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.BufferedWriter.write(BufferedWriter.java:230)
        at com.sun.xml.internal.stream.writers.XMLStrerImpl.writeXMLContent(XMLStreamWriterImpl.java:1486)
        at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeAttribute(XMLStreamWriterImpl.java:547)
        ... 25 more                

Test run finished after 744 ms     
[       666 tests found     ]
[         0 tests skipped   ]
[       666 tests started   ]
[         0 tests aborted   ]
[       666 tests successful]
[         0 tests failed    ]
```

The XML looks like 2 line file (which has 116 368 chars):
![image](https://cloud.githubusercontent.com/assets/6240704/16313657/78ea03d0-397a-11e6-8e2e-7c247fa78ba6.png)

and finishes in unexpected way:
![image](https://cloud.githubusercontent.com/assets/6240704/16313687/a7b2c562-397a-11e6-8a0a-9936b287fa0f.png)

**Comment by marcphilipp** [comment]
Is this a private project or can we take a look at the sources? What's the full name of this test? Does it use non-UTF-8 (UTF-16) characters?

**Comment by sbrannen** [comment]
What happens if you run the exact same tests in the IDE -- for example, via `@RunWith(JUnitPlatform.class)`?

**Comment by sta-szek** [comment]
Sorry for my absence.
1. This is private repo. At the moment I don't want to publish it.
2. My tests have english names like Should_XXX_YYY
3. I use IntelliJ and can't run tests from IDE -- only gradle. Configuration of build.gradle is here #351 

```
gradle --version

------------------------------------------------------------
Gradle 2.6
------------------------------------------------------------

Build time:   2015-08-10 13:15:06 UTC
Build number: none
Revision:     233bbf8e47c82f72cb898b3e0a96b85d0aad166e

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Windows 8.1 6.3 amd64
```

**Comment by sta-szek** [comment]
I updated gradle to 2.14. Still the same

**Comment by sbrannen** [comment]
> I use IntelliJ and can't run tests from IDE -- only gradle.

Actually, it shouldn't be a problem to run the tests from within IntelliJ using `@RunWith(JUnitPlatform.class)`.

You can find details in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/#running-tests-junit-platform-runner).

**Comment by sbrannen** [comment]
> This is private repo. At the moment I don't want to publish it.

Would you be able to create a scaled down demo project that reproduces the error and then share that project with us?

**Comment by sta-szek** [comment]
Ok, `@RunWith(JunitPlatform.class)` is working but it is IMHO not a good solution - I have to change the code to be able to run tests against IDE, so IDE Driven Development does not satisfy me. But it seems to be the only solution at the moment and now I can merge JUnit5 branch to master :satisfied: thanks for help in #351 and here.

When I started using `gradlew` I managed to run jacoco (I don't now why it works :) ) and it successfully generated coverage report. (it was working with junit 4.12)

So despite of unfinished XML report there is no problems with running tests and getting coverage.

Sorry but i don't have time for sample repo - but the problem is with too big xml file - when I deleted 630 tests (only 36 left) there is no such an error (MalformedInputException) and the xml file is ok
BUT still **12 529** lines for **26 tests**? :scream: :scream: :scream:

There is a lot of redundant informations e.g.

```xml
<testcase 
name="------&gt; 127 -128 &lt;------" 
classname="Should_XXX_YYY()" time="0">
<!--Unique ID: [engine:junit-jupiter]/[class:org.xxx.xxx.ClassName]/[test-factory:Should_XXX_YYY()]/[dynamic-test:#9]-->
</testcase>
```

The first `classname` is not a _test class_ name or _tested class_ name but simple **test name**,
so `ID` could use that. 
Second, if `time` is 0 then do not include it.
Third, if there is a dynamic test you could group them e.q. 
```xml
<testcase classname="_RealClassName_"> 
<dynamic ID="..."> 
<#1..> 
<#2....>
</dynamic>
</testcase>
```

Fifth, maby split info more files?

And last but not least is I hate XML :)
maybe you could use json/yaml for that? or it needs to be in XML to be supported by...?

So instead of

```xml
<testcase name="------&gt; null null &lt;------"
          classname="Should_XXX_YYY()"
          time="0">
    <!--Unique ID: [engine:junit-jupiter]/[class:org.xxx.xxx.ClassName]/[test-factory:Should_XXX_YYY()]/[dynamic-test:#1]-->
</testcase>
<testcase name="------&gt; 0 0 &lt;------"
          classname="Should_XXX_YYY()"
          time="0">
<!--Unique ID: [engine:junit-jupiter]/[class:org.xxx.xxx.ClassName]/[test-factory:Should_XXX_YYY()]/[dynamic-test:#2]-->
</testcase>
<testcase name="------&gt; -128 -128 &lt;------"
          classname="Should_XXX_YYY()"
          time="0">
<!--Unique ID: [engine:junit-jupiter]/[class:org.xxx.xxx.ClassName]/[test-factory:Should_XXX_YYY()]/[dynamic-test:#3]-->
</testcase>
<testcase name="------&gt; 127 127 &lt;------"
          classname="Should_XXX_YYY()"
          time="0">
<!--Unique ID: [engine:junit-jupiter]/[class:org.xxx.xxx.ClassName]/[test-factory:Should_XXX_YYY()]/[dynamic-test:#4]-->
</testcase>
```

it could be

```xml
<testcase classname="Should_XXX_YYY()" idTemplate="[engine:junit-jupiter]/[class:org.xxx.xxx.ClassName]/[test-factory:classname()]/[dynamic-test::#$id]">
<dynamic>
    <name="------&gt; null null &lt;------" id="1"></name>
    <name="------&gt; 0 0 &lt;------" id="2"></name>
    <name="------&gt; -128 -128 &lt;------" id="3"></name>
    <name="------&gt; 127 127 &lt;------" id="4"></name>
</dynamic>
</testcase>
```

still same informations but
:sunglasses::sunglasses::sunglasses::sunglasses::sunglasses::sunglasses::sunglasses: :sunglasses:
:sunglasses:`20   ---------     8 lines     `:sunglasses: 
:sunglasses:`959 --------- 414 chars`:sunglasses: 
:sunglasses: :sunglasses::sunglasses::sunglasses::sunglasses::sunglasses::sunglasses::sunglasses: :sunglasses:
And finally, If you really want to look at the code I can add you to my repo

**Comment by sta-szek** [comment]
Sorry for mistake - **I still have the same number of tests** - my mistake

**Comment by sbrannen** [comment]
> or it needs to be in XML to be supported by...?

Yes, exactly. The XML format is required in order to build tools to know how to parse the results.

We did not invent the format, and it therefore does not support all of the features of the JUnit Platform. So that's why we cannot simply change the XML format as you have proposed. That's also why JUnit Platform specific features are in comment blocks (`<!-- ... -->`).

**Comment by sbrannen** [comment]
See #86 for further details on the XML format, etc.

**Comment by sbrannen** [comment]
I've successfully executed 10,000 dynamic tests, and I don't run into any issues with XML report generation.

So I'm assuming it must have something to do with the character set you are using or how you are generating display names for the dynamic tests.

Can you please share with us exactly what characters and/or symbols you are supplying as the `displayName` for your dynamic tests?

Thanks in advance!

**Comment by sta-szek** [comment]
my `displayNames` are like this `------> " + String.valueOf(value) + " <------` and values are e.g.
classes (Pojo.class)
primitve classes (int.class)
fields (Field.class and instances)
class names (string)

and other "normal" types :)

BTW
If XML is not good anymore (I'm pretty sure of that) why we can't do something better. Something that brakes the rules like json / yaml results. Write plugins for jacoco, teamcity etc...
Let's start smth that everyone is looking forward :)

**Comment by sbrannen** [comment]
@sta-szek,

Since #372 has been resolved, it would be great if you could try out the next snapshot to see if it has any positive effect on the problem you were facing.

In addition, regarding the format of the XML vs. JSON, etc., perhaps you would be interested in #373.

**Comment by sta-szek** [comment]
This fixed the problem of one line files - nice!

And I investigated problem a litte bit more and the answer for this is:

When you try to name your test with characters containig one of the following:

- [java.lang.Character.MAX_HIGH_SURROGATE](http://docs.oracle.com/javase/6/docs/api/java/lang/Character.html#MAX_HIGH_SURROGATE)
- [java.lang.Character.MAX_LOW_SURROGATE](http://docs.oracle.com/javase/6/docs/api/java/lang/Character.html#MAX_LOW_SURROGATE)
- [java.lang.Character.MAX_SURROGATE](http://docs.oracle.com/javase/6/docs/api/java/lang/Character.html#MAX_SURROGATE)
- [java.lang.Character.MIN_HIGH_SURROGATE](http://docs.oracle.com/javase/6/docs/api/java/lang/Character.html#MIN_HIGH_SURROGATE)
- [java.lang.Character.MIN_LOW_SURROGATE](http://docs.oracle.com/javase/6/docs/api/java/lang/Character.html#MIN_LOW_SURROGATE)
- [java.lang.Character.MIN_SURROGATE](http://docs.oracle.com/javase/6/docs/api/java/lang/Character.html#MIN_SURROGATE)

the xml fails to write.

So, who's problem / bug it is?

Do you know a little bit more about that (surrogates)? Why it fails?

**Comment by sbrannen** [comment]
@sta-szek, interesting. Thanks for doing the additional research.

As @marcphilipp originally suspected, you are using UTF-16 characters in your test names; however, JUnit generates the XML report using UTF-8.

Can you please provide an example of one of the names you are using that contains UTF-16 characters?

Then we'll see what we can do...

**Comment by sbrannen** [comment]
By the way, if you just stick to UTF-8, you should be fine!

**Comment by sta-szek** [comment]
Yes, I've already removed those tests as they were extra addition - other tests test my functionality.

And the names were like this
`"------> " + Character.MAX_HIGH_SURROGATE + " <------"` etc.

**Comment by sta-szek** [comment]
BTW
what happens if test names are:
`<xml> ... </xml>` 
` <!-- ... -->` 
`<![CDATA[]]>` ??

**Comment by sbrannen** [comment]
Display names are already wrapped in `CDATA` since ab2013767195e70c1d00d62d0d4335405436a7a5.

But that does not allow one to use UTF-16. UTF-8 is still required.

**Comment by marcphilipp** [comment]
I guess using UTF-16 to write the XML file should resolve the issue, right?

**Comment by marcphilipp** [comment]
If we decide to support UTF-16 we should make it an opt-in feature (by having a switch in ConsoleLauncher and the Gradle plugin).
