### ISSUE TITLE
Upgrade to `junit-platform-launcher` 1.10.1 produces error with `getAncestors`

### ISSUE THREAD

**Issue by svboettger** [junit-team/junit5#3548]
## Steps to reproduce

Upgrade an application with existing running tests from junit-platform-launcher 1.9.3 to 1.10.1.

Tests fail on Jenkins, IntelliJ and Maven with the error:

```
There was an error in the forked process
'java.util.Set org.junit.platform.engine.TestDescriptor.getAncestors()'
```

Maven Stacktrace:

```
[ERROR] There was an error in the forked process
[ERROR] 'java.util.Set org.junit.platform.engine.TestDescriptor.getAncestors()'
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] 'java.util.Set org.junit.platform.engine.TestDescriptor.getAncestors()'
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:628)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1203)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1055)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:871)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
[ERROR] 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

## Context

 - Used versions (Jupiter/Vintage/Platform): junit-platform-launcher 1.10.1
 - Build Tool/IDE: Maven 3.9.4 / IntelliJ Ultimate 2023.2.4 (Windows) / Spring Boot 3.1

## Deliverables

- [ ] ...

**Comment by sbrannen** [comment]
> Upgrade an application with existing running tests from junit-platform-launcher 1.9.3 to 1.10.1.

How did you perform the "upgrade"?

Is the JUnit version you're using managed by Spring Boot? If so, did you [upgrade properly](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-spring-boot)?

**Comment by marcphilipp** [comment]
IIRC Surefire produces dump files for such errors that may contain more information. Does the build output contain any mention of them?

**Comment by svboettger** [comment]
> > Upgrade an application with existing running tests from junit-platform-launcher 1.9.3 to 1.10.1.
> 
> How did you perform the "upgrade"?
> 
> Is the JUnit version you're using managed by Spring Boot? If so, did you [upgrade properly](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-spring-boot)?

Ah, I see my failure. Our config is conflicting with Spring Boot. I resolve this. I) close this issue.

**Comment by hantsy** [comment]
I encountered the issue in my project: https://github.com/hantsy/arquillian-container-glassfish-jakarta

I am using JUnit 5.10.1, managed by a BOM import.

The `jboss-parent` upgrade the surefire version to the newest version, it throw the following exceptions.

https://github.com/hantsy/arquillian-container-glassfish-jakarta/actions/runs/6918305067/job/18820424749?pr=21

I tried to show the dependencies tree, and got the following.

```bash 
[INFO] \- org.junit.jupiter:junit-jupiter:jar:5.10.1:test
[INFO]    +- org.junit.jupiter:junit-jupiter-api:jar:5.9.3:test
[INFO]    |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO]    |  +- org.junit.platform:junit-platform-commons:jar:1.10.1:test
[INFO]    |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO]    +- org.junit.jupiter:junit-jupiter-params:jar:5.9.3:test
[INFO]    \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.3:test
[INFO]       \- org.junit.platform:junit-platform-engine:jar:1.9.3:test
```

I do not know why the versions are different in the transitive deps.

**Comment by hantsy** [comment]
Maybe a little different from the original post, I created an new issue.
