### ISSUE TITLE
Introduce `ReflectionSupport.makeAccessible(Field)` for third-party use

### ISSUE THREAD

**Issue by shihabuddin** [junit-team/junit5#3925]
## Steps to reproduce

The commit abb5ed16be3a9ce552f4a45c11264ded608ae9da removes the method `ReflectionUtils.makeAccessible(AccessibleObject)`, but it is being used by `DropwizardExtensionsSupport`.

In `pom.xml`:

```xml
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.11.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-testing</artifactId>
      <version>4.0.7</version>
      <scope>test</scope>
    </dependency>
```

In the test class:

```java
@ExtendWith(DropwizardExtensionsSupport.class)
class SampleTest {
  @Path("/test-resource")
  static class TestResource {
    @GET
    public String get() {
      throw new RuntimeException("No object found");
    }
  }

  private static final ResourceExtension sResources = ResourceExtension.builder()
      .addResource(new TestResource())
      .build();

  @Test
  void testException() {
    Response response = sResources.target("/test-resource").request().get();
    assertEquals(500, response.getStatus(), "Status code does not match");
  }
}
```

Run `mvn test`.

Full stacktrace:

```
java.lang.Exception: java.lang.NoSuchMethodError: 'java.lang.reflect.AccessibleObject org.junit.platform.commons.util.ReflectionUtils.makeAccessible(java.lang.reflect.AccessibleObject)'
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:87)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.Exception: java.lang.NoSuchMethodError: 'java.lang.reflect.AccessibleObject org.junit.platform.commons.util.ReflectionUtils.makeAccessible(java.lang.reflect.AccessibleObject)'
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.afterAll(DropwizardExtensionsSupport.java:40)
		... 1 more
	Caused by: java.lang.NoSuchMethodError: 'java.lang.reflect.AccessibleObject org.junit.platform.commons.util.ReflectionUtils.makeAccessible(java.lang.reflect.AccessibleObject)'
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.getDropwizardExtension(DropwizardExtensionsSupport.java:149)
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.afterAll(DropwizardExtensionsSupport.java:50)
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.afterAll(DropwizardExtensionsSupport.java:36)
		... 1 more
Caused by: java.lang.NoSuchMethodError: 'java.lang.reflect.AccessibleObject org.junit.platform.commons.util.ReflectionUtils.makeAccessible(java.lang.reflect.AccessibleObject)'
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.getDropwizardExtension(DropwizardExtensionsSupport.java:149)
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:97)
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:83)
	... 1 more
```

## Context

 - Used versions (Jupiter/Vintage/Platform): junit-jupiter 5.11.0
 - Build Tool/IDE: Apache Maven 3.6.3

## Deliverables

- [ ] Introduce a supported, public alternative to `ReflectionUtils.makeAccessible`

**Comment by marcphilipp** [comment]
`ReflectionUtils` is annotated with `@API(status = INTERNAL)`. Thus, it's an internal class and shouldn't be used by third-party projects like Dropwizard. That being said, I see @joschi has already updated Dropwizard's JUnit dependency to 5.11.0 which caused it to be recompiled now using the `ReflectionUtils.makeAccessible(Field)` method rather than the no longer existing `ReflectionUtils.makeAccessible(AccessibleObject)` one. I think the quickest way to resolve the issue is to release a patch version of Dropwizard.

@joschi Do you think that would be feasible?

To avoid this in the future, we should introduce a `makeAccessible(Field)` method in `ReflectionSupport` which is intended to be used by third parties.

**Comment by marcphilipp** [comment]
I submitted a PR to Dropwizard to switch to an existing public API: https://github.com/dropwizard/dropwizard/pull/9157

**Comment by sbrannen** [comment]
Reopening to move release notes entry from `5.11.1` to `5.12 M1`.
