### ISSUE TITLE
Should IDE check if api jar is present in the classpath before adding corresponding engine jar?

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#405]
If I don't have `junit4.jar` in the classpath but add (as IDE) the vintage engine jar, then I get `ClassNotFoundException` as:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.junit.vintage.engine.discovery.JUnit4DiscoveryRequestResolver.getAllDiscoverySelectorResolvers(JUnit4DiscoveryRequestResolver.java:58)
```

IDE can include vintage engine only if `TestCase` is found on the classpath. Is that a desired check, or should JUnit not throw exception on 'inconsistent' classpath?

**Comment by sbrannen** [comment]
Hi @akozlova,

> Should IDE check if api jar is present in the classpath before adding corresponding engine jar?

Yes. If the IDE is automatically adding engine JARs to the classpath, it only makes sense if the required API JARs are present as well.

I would actually expect the IDE to honor the Maven dependency data when adding anything like an engine to the classpath.

For example, the `junit-vintage-engine` module has a required dependency on `junit:junit:4.12`. So if the `junit-4.12.jar` is not in the project's classpath, the Vintage engine should not be automatically added.

Similarly, the `junit-jupiter-engine` module has a required dependency on `org.junit.jupiter:junit-jupiter-api:5.0.0-M1` (for the M1 milestone release). So if the `jupiter-api-5.0.0-M1.jar` is not in the project's classpath, the Jupiter engine should not be automatically added.

Does that answer your question?

**Comment by akozlova** [comment]
ok, I'll add corresponding checks. Thanks

**Comment by sbrannen** [comment]
You're welcome, and thanks for the feedback.

I'll close this issue now.

**Comment by sbrannen** [comment]
p.s. everybody is really glad to see that IntelliJ IDEA is the first IDE with official support for JUnit 5.

So.... kudos! 👍

**Comment by akozlova** [comment]
Please treat it as 'prototype', the support is really basic and not really tested :/

**Comment by raniejade** [comment]
Hopefully the run configuration is generic enough that other `TestEngine`s can use it :)

**Comment by sbrannen** [comment]
> Please treat it as 'prototype', the support is really basic and not really tested :/

Understood.

We're just happy you're making progress!
