### ISSUE TITLE
Exception in thread "main" joptsimple.UnrecognizedOptionException: all is not a recognized option

### ISSUE THREAD

**Issue by sta-szek** [junit-team/junit5#479]
Don't know if this exception is my fault but I don't have any clue what's wrog.
After month I started developing my project again and it does't want to build with gradle.

```
gradle --version

------------------------------------------------------------
Gradle 2.14
------------------------------------------------------------

Build time:   2016-06-14 07:16:37 UTC
Revision:     cba5fea19f1e0c6a00cc904828a6ec4e11739abc

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Windows 8.1 6.3 amd64
```

```
java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

and the exception
```
18:50:24.626 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
18:50:24.626 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'.
18:50:24.641 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
18:50:24.641 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
18:50:24.641 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe''
18:50:24.780 [ERROR] [system.err] Exception in thread "main" joptsimple.UnrecognizedOptionException: all is not a recognized option
18:50:24.795 [ERROR] [system.err]       at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
18:50:24.795 [ERROR] [system.err]       at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
18:50:24.795 [ERROR] [system.err]       at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
18:50:24.795 [ERROR] [system.err]       at joptsimple.OptionParser.parse(OptionParser.java:396)
18:50:24.795 [ERROR] [system.err]       at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:38)
18:50:24.795 [ERROR] [system.err]       at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:52)
18:50:24.795 [ERROR] [system.err]       at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
18:50:24.795 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
18:50:24.795 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'' finished with exit value 1 (state: FAILED)
18:50:24.795 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':junitPlatformTest'
18:50:24.795 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :junitPlatformTest FAILED
18:50:24.795 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :junitPlatformTest (Thread[Daemon worker,5,main]) completed. Took 0.31 secs.
18:50:24.795 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 6.06 secs, idle: 0.0 secs
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':junitPlatformTest'.
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'' finished with non-zero exit value 1
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':junitPlatformTest'.
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
18:50:24.795 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.Swapper.swap(Swapper.java:38)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'' finished with non-zero exit value 1
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:74)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]        ... 68 more
18:50:24.811 [ERROR] [org.gradle.BuildExceptionReporter]
18:50:24.811 [LIFECYCLE] [org.gradle.BuildResultLogger]
18:50:24.811 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
```

tested with gradle, gradlew, junit SNAPTSHOT and M2

**Comment by sbrannen** [comment]
I removed the `--all` option for the `ConsoleLauncher` in a recent commit for the upcoming M3.

So, since the JUnit Platform Gradle Plugin uses the `ConsoleLauncher` behind the scenes, that means you must have an outdated version of the plugin running against the latest snapshots.

Try executing Gradle with `--refresh-dependencies` to download the latest SNAPSHOT for the plugin.

Or, if you don't want to use the snapshot for the plugin, make sure you set the version of the plugin **and** your other JUnit Platform dependencies to `5.0.0-M2`.

Please let us know if this solves your issue.

Cheers,

Sam

**Comment by sta-szek** [comment]
Hmmm
M2, M1, SNAPSHOT
`gradle clean build --refresh-dependencies`
`gradlw clean build --refresh-dependencies`

and not working.
I removed .gradle/caches dir content and still the same.

Am I doing something wrong?

**Comment by sta-szek** [comment]
Yes, my mistake

I forgot about the
```
buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
    dependencies {
        classpath "info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.1.9"
        classpath "org.junit.platform:junit-platform-gradle-plugin:1.0.0-SNAPSHOT"
    }
}
```
section.

Problem solved.
Thanks ;)

**Comment by sbrannen** [comment]
Glad you sorted it out, and thanks for letting us know!

**Comment by Alxandr** [comment]
I have `-M2` specified everywhere wrt junit packages, and I still just started to get this error.

**Comment by sbrannen** [comment]
@Alxandr, what happens if you add an explicit dependency on `org.junit.platform:junit-platform-console:1.0.0-M2`?

**Comment by sbrannen** [comment]
@Alxandr, as an alternative, what happens if you set `platformVersion = 1.0.0-M2` within the `junitPlatform` configuration block in your Gradle build?

**Comment by Alxandr** [comment]
Well, I saw that M3 was released, so I rather went through the process of upgrading to that. I'm guessing the gradle plugin downloaded the latest something from maven central which broke it when a new release was uploaded.

**Comment by goerge** [comment]
Although I set all JUnit related versions to -M2,  I had this issue, too.

Setting either
```
junitPlatform {
    platformVersion = "1.0.0-M2"
}
```
or 
```
testRuntime "org.junit.platform:junit-platform-console:1.0.0-M2"
```
fixed the issue.
Is this really intended?

**Comment by marcphilipp** [comment]
> Is this really intended?

Definitely not! Let's continue the discussion in #576.
