### ISSUE TITLE
Error while running junitPlatformTest Gradle task

### ISSUE THREAD

**Issue by vw-reisepass** [junit-team/junit5#578]
We're using Junit platform Runner for `Spek` tests in Kotlin.
Since yesterday, our gradle junitPlatformTest task has been failing with the following error.

```
09:54:57.888 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':vw-profile-api:junitPlatformTest'.
09:54:57.889 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java''. Working directory: /Users/dilabuser/workspace/reisepass/vw-profile-api Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/dilabuser/workspace/reisepass/vw-profile-api/build/classes/test:/Users/dilabuser/workspace/reisepass/vw-profile-api/build/resources/test:/Users/dilabuser/workspace/reisepass/vw-profile-api/build/classes/main:/Users/dilabuser/workspace/reisepass/vw-profile-api/build/resources/main:/Users/dilabuser/workspace/reisepass/json-store/build/libs/json-store.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.0.5-2/9a397ba5477bf49ae0418cc3e392b3c0e5a112d1/kotlin-stdlib-1.0.5-2.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-kotlin/2.8.4/4b2441ff3a2a1cf59c655df6100d5e57fe9925f1/jackson-module-kotlin-2.8.4.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-web/1.4.2.RELEASE/7145c258f8fba4067f9e3880fad23586c9b8ff10/spring-boot-starter-web-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-test/1.4.2.RELEASE/564b798522d811461ce6c8792c063ae2308898f8/spring-boot-starter-test-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.jetbrains.spek/spek-api/1.0.89/d95845968a41202319071525b87b023a42e8a685/spek-api-1.0.89.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-runner/1.0.0-M2/cd83cbb3172350ff02cd3c62a29b131c53d765b/junit-platform-runner-1.0.0-M2.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.skyscreamer/jsonassert/1.4.0/9cdbb373a06f6513e51e8c545ee6a5e981463edb/jsonassert-1.4.0.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.jetbrains.spek/spek-junit-platform-engine/1.0.89/95cf7b84f44354b761c1776fa0867cdb1da348c/spek-junit-platform-engine-1.0.89.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.mariadb.jdbc/mariadb-java-client/1.5.5/48603aa9dca7eaac8073260e7f6c206f1c8dc09c/mariadb-java-client-1.5.5.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-jdbc/1.4.2.RELEASE/706b5cd5996bd8c03248c3236e90e9d2d7c948db/spring-boot-starter-jdbc-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.flywaydb/flyway-core/3.2.1/88347e9a484152e9b80fbad7648d1b552a8cff78/flyway-core-3.2.1.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-runtime/1.0.5-2/16ba409719189072db06433a3c381015c0877998/kotlin-runtime-1.0.5-2.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.8.4/1c36c81e79cacdf48116afba8495e3393d267ba1/jackson-databind-2.8.4.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.8.0/45b426f7796b741035581a176744d91090e2e6fb/jackson-annotations-2.8.0.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.0.3/ed9cbaeb8dccd2027348185044012aac145a5c61/kotlin-reflect-1.0.3.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter/1.4.2.RELEASE/c6068dc9688c12509bb1c36fcf6ff4817d46cce2/spring-boot-starter-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-tomcat/1.4.2.RELEASE/1ab1939bb566bbaf25cc1f50cdf955b6c927c4d3/spring-boot-starter-tomcat-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.hibernate/hibernate-validator/5.2.4.Final/fb18766b576aa6632bcfe9a20a023cbd52bf9769/hibernate-validator-5.2.4.Final.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-web/4.3.4.RELEASE/719f05404ba8a9de1516398d31d9622042584f0d/spring-web-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/4.3.4.RELEASE/79529d7ea72045e92e3dbeb0f4f6919093f47137/spring-webmvc-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-test/1.4.2.RELEASE/c94582bccb1dbc5599bd8d59a703e3650f9adcf3/spring-boot-test-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-test-autoconfigure/1.4.2.RELEASE/12733afdfae9edcb0a1a2e98c3b07815986d1ee4/spring-boot-test-autoconfigure-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/com.jayway.jsonpath/json-path/2.2.0/22290d17944bd239fabf5ac69005a60a7ecbbbcb/json-path-2.2.0.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.assertj/assertj-core/2.5.0/fcd21db4c5f33e5dcac69bf1816415fe0647582f/assertj-core-2.5.0.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/1.10.19/e8546f5bef4e061d8dd73895b4e8f40e3fe6effe/mockito-core-1.10.19.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-library/1.3/4785a3c21320980282f9f33d0d1264a69040538f/hamcrest-library-1.3.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/4.3.4.RELEASE/da373e491d3863477568896089ee9457bc316783/spring-core-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-test/4.3.4.RELEASE/a4e28d4eaaa6174928c3edf784faba78bfc046ec/spring-test-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-launcher/1.0.0-M2/2c7f203cd470023891184a6e52d9562c9cc729bc/junit-platform-launcher-1.0.0-M2.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.apache.tomcat/tomcat-jdbc/8.5.6/feb10a9e22f70565c7556f327b0481dba8587bbc/tomcat-jdbc-8.5.6.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-jdbc/4.3.4.RELEASE/42175d194cf6aa7c716c0887f30255e5c0a5262c/spring-jdbc-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.8.4/ca365c0817cc345ea831cae7c4e9b42a72b32281/jackson-core-2.8.4.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/1.4.2.RELEASE/19ecf2582f58722c08147918982227885f6e31b1/spring-boot-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/1.4.2.RELEASE/368e464f9ce4622722ce0944cc4ba6fa71332b68/spring-boot-autoconfigure-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-logging/1.4.2.RELEASE/2799c67340d6a27af5f17a7ecdfa1f50cb1d152d/spring-boot-starter-logging-1.4.2.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.17/7a27ea250c5130b2922b86dea63cbb1cc10a660c/snakeyaml-1.17.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-core/8.5.6/960834b5abc6b2135250487abf6c060a0fa5a22e/tomcat-embed-core-8.5.6.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-el/8.5.6/a102298d8dc72f4065533d5962953d753b172602/tomcat-embed-el-8.5.6.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-websocket/8.5.6/6f6940a216b380ea8506530c374fcfeef820ba54/tomcat-embed-websocket-8.5.6.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/8613ae82954779d518631e05daa73a6a954817d5/validation-api-1.1.0.Final.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.jboss.logging/jboss-logging/3.2.1.Final/fedf11b3d4665a434b554a5891fe7f208f029f45/jboss-logging-3.2.1.Final.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/com.fasterxml/classmate/1.1.0/dbbd699a1486ad0f2ed6f5af6cfed66acacb9056/classmate-1.1.0.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-aop/4.3.4.RELEASE/43f3d4a43a8dcc91137e092b981101332a645e4b/spring-aop-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-beans/4.3.4.RELEASE/4fbf4327d6c7f81c821f2d56e8695d394c7b930a/spring-beans-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-context/4.3.4.RELEASE/c8086505715fba4927fed3d7e3314692817413b6/spring-context-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-expression/4.3.4.RELEASE/5573955b5373669be0e352a1eb5dc9c87b069cb6/spring-expression-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/net.minidev/json-smart/2.2.1/5b9e5df7a62d1279b70dc882b041d249c4f0b002/json-smart-2.2.1.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/2.1/87c0ea803b69252868d09308b4618f766f135a96/objenesis-2.1.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.2/4bfc12adfe4842bf07b657f0369c4cb522955686/commons-logging-1.2.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.0.0-M2/fe36ee348295ec740b068b3dd46ec5c733134eb5/junit-platform-engine-1.0.0-M2.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.apache.tomcat/tomcat-juli/8.5.6/83d2d1e3362ecca504f3bf8ed1bc4cc451754d24/tomcat-juli-8.5.6.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.springframework/spring-tx/4.3.4.RELEASE/303d00338193c04312426325121572d2fc1d4ec5/spring-tx-4.3.4.RELEASE.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.7/9865cf6994f9ff13fce0bf93f2054ef6c65bb462/logback-classic-1.1.7.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.slf4j/jcl-over-slf4j/1.7.21/331b564a3a42f002a0004b039c1c430da89062cd/jcl-over-slf4j-1.7.21.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.slf4j/jul-to-slf4j/1.7.21/2f22c882ffa479d1e9ff4eb0e8e2c29f2a0871ed/jul-to-slf4j-1.7.21.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.slf4j/log4j-over-slf4j/1.7.21/b3700d97464d99bdcd42c0177d6e7951c94d75ff/log4j-over-slf4j-1.7.21.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/net.minidev/accessors-smart/1.1/a527213f2fea112a04c9bdf0ec0264e34104cd08/accessors-smart-1.1.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.0.0-M2/a6f1f88b10512623ed14e8b93be10b7590f74c11/junit-platform-commons-1.0.0-M2.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.0.0-M1/b091255eafd515995a5c5fa042cd8db6f4860bf6/opentest4j-1.0.0-M1.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.1.7/7873092d39ef741575ca91378a6a21c388363ac8/logback-core-1.1.7.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/5.0.3/dcc2193db20e19e1feca8b1240dbbc4e190824fa/asm-5.0.3.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/com.vaadin.external.google/android-json/0.0.20131108.vaadin1/fa26d351fe62a6a17f5cda1287c1c6110dec413f/android-json-0.0.20131108.vaadin1.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.21/139535a69a4239db087de9bab0bee568bf8e0b70/slf4j-api-1.7.21.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-launcher/1.0.0-M3/86525f5274dee56f533f938f9aeae9a3716f8c4/junit-platform-launcher-1.0.0-M3.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-console/1.0.0-M3/fec4071130bcec4081b868a59fa6cad47f11733/junit-platform-console-1.0.0-M3.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.0.0-M3/39a1db55680c9f32985c84ba2951912138b18ac3/junit-platform-engine-1.0.0-M3.jar:/Users/dilabuser/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.0.0-M3/d5c77e2df6a820ae30fc17f21a3f8cfc03183980/junit-platform-commons-1.0.0-M3.jar org.junit.platform.console.ConsoleLauncher --hide-details --all -e spek -r /Users/dilabuser/workspace/reisepass/vw-profile-api/build/test-results/junit-platform /Users/dilabuser/workspace/reisepass/vw-profile-api/build/classes/main /Users/dilabuser/workspace/reisepass/vw-profile-api/build/resources/main /Users/dilabuser/workspace/reisepass/vw-profile-api/build/classes/test /Users/dilabuser/workspace/reisepass/vw-profile-api/build/resources/test
09:54:57.890 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'': {PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin, HISTCONTROL=ignorespace:erasedups, JAVA_ARCH=x86_64, GREP_COLOR=1;33, HISTSIZE=5000, TERM=xterm-256color, BASH_IT=/Users/dilabuser/.bash_it, COMMAND_MODE=unix2003, BASH_IT_THEME=bobby, AUTOFEATURE=true autotest, ITERM_SESSION_ID=w0t0p0:38D51205-34BA-4542-B13F-A7A542C0F2D0, LOGNAME=dilabuser, TERM_PROGRAM_VERSION=3.0.12, PWD=/Users/dilabuser/workspace/reisepass, XPC_SERVICE_NAME=0, SHELL=/bin/bash, APP_NAME_87385=Gradle, TERM_PROGRAM=iTerm.app, APP_ICON_87385=/Users/dilabuser/workspace/reisepass/media/gradle.icns, LSCOLORS=Gxfxcxdxdxegedabagacad, JAVA_MAIN_CLASS_87385=org.gradle.wrapper.GradleWrapperMain, OLDPWD=/Users/dilabuser/workspace/reisepass, SECURITYSESSIONID=186a7, USER=dilabuser, TMPDIR=/var/folders/z9/6hbzfm7s5jv4k6cl6k06zmbm0000gn/T/, ITERM_PROFILE=Default, SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.SgWMTdecDi/Listeners, XPC_FLAGS=0x0, TERM_SESSION_ID=w0t0p0:38D51205-34BA-4542-B13F-A7A542C0F2D0, DESTINATION=/var/folders/z9/6hbzfm7s5jv4k6cl6k06zmbm0000gn/T/iTerm 2.1.4 Update, __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0, Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.I2R2TvhBi0/Render, com.apple.java.jvmTask=CommandLine, COLORFGBG=7;0, LC_CTYPE=UTF-8, HOME=/Users/dilabuser, SHLVL=1}
09:54:57.890 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
09:54:57.890 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'.
09:54:57.898 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
09:54:57.898 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
09:54:57.898 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java''
09:54:58.155 [ERROR] [system.err] Exception in thread "main" org.junit.platform.commons.JUnitException: Error parsing command-line arguments
09:54:58.155 [ERROR] [system.err]       at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:44)
09:54:58.155 [ERROR] [system.err]       at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:52)
09:54:58.155 [ERROR] [system.err]       at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
09:54:58.172 [ERROR] [system.err] Caused by: org.junit.platform.joptsimple.UnrecognizedOptionException: all is not a recognized option
09:54:58.173 [ERROR] [system.err]       at org.junit.platform.joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
09:54:58.173 [ERROR] [system.err]       at org.junit.platform.joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
09:54:58.173 [ERROR] [system.err]       at org.junit.platform.joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
09:54:58.173 [ERROR] [system.err]       at org.junit.platform.joptsimple.OptionParser.parse(OptionParser.java:396)
09:54:58.173 [ERROR] [system.err]       at org.junit.platform.console.options.JOptSimpleCommandLineOptionsParser.parse(JOptSimpleCommandLineOptionsParser.java:40)
09:54:58.173 [ERROR] [system.err]       ... 2 more
09:54:58.184 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
09:54:58.184 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'' finished with exit value 1 (state: FAILED)
```

Our  build.gradle  file looks like below:

```groovy
buildscript {
    ext {
        kotlinVersion = '1.0.5-2'
        springBootVersion = '1.4.2.RELEASE'
    }

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}"
        classpath "org.junit.platform:junit-platform-gradle-plugin:1.0.0-M2"
    }
}

apply plugin: 'kotlin'
apply plugin: 'org.junit.platform.gradle.plugin'

repositories {
    mavenCentral()
}

junitPlatform {
    engines {
        include 'spek'
    }
}

dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}")
    compile("org.springframework.boot:spring-boot-starter-web:${springBootVersion}")

    testCompile("org.springframework.boot:spring-boot-starter-test:${springBootVersion}")
    testCompile("junit:junit:4.11")

    testCompile("org.jetbrains.spek:spek-api:1.0.89")
    testCompile("org.junit.platform:junit-platform-runner:1.0.0-M2")
    testCompile("org.jetbrains.spek:spek-junit-platform-engine:1.0.89")
}
```

Seems like, even though we specify the version of junit-platform-runner to be `1.0.0-M2`, it uses latest `1.0.0-M3`. And it runs with `ConsoleLauncher` with a `--all` option which is not supported.

If we do not apply the junit-platform plugin and add it as a compile time dependency for our tests instead, everything seems to be working fine.

Thanks!

**Comment by marcphilipp** [comment]
Please try to set `platformVersion` to 1.0.0-M2 as mentioned here: https://github.com/junit-team/junit5/issues/479#issuecomment-264068538 and let us know if that helps.

**Comment by arturbosch** [comment]
Adding an explicit dependency on org.junit.platform:junit-platform-console:1.0.0-M2 in all sub modules solved this issue for me.

**Comment by sbrannen** [comment]
> Adding an explicit dependency on `org.junit.platform:junit-platform-console:1.0.0-M2` in all sub modules solved this issue for me.

@arturbosch, thanks for confirming that that worked for you.

**Comment by goerge** [comment]
As mentioned in #479 :

Although I set all JUnit related versions to -M2, I had this issue, too.
Setting either
```
junitPlatform {
    platformVersion = "1.0.0-M2"
}
```
or
```
testRuntime "org.junit.platform:junit-platform-console:1.0.0-M2"
```
fixed the issue.
Is this really intended?

**Comment by marcphilipp** [comment]
> Is this really intended?

Definitely not! I'm closing this issue as there's already a proposed solution in #576.
