### ISSUE TITLE
Problems with 5.0.0-M3 when using snapshot repositories

### ISSUE THREAD

**Issue by janschaefer** [junit-team/junit5#617]
Apparently the artifacts `junit-jupiter-api` and `junit-jupiter-engine` are published in version `5.0.0-M3` on Maven central as well as the Sonatype snapshot repository `https://oss.sonatype.org/content/groups/public/`. This seem to cause problems when both repositories are used at the same time. When I add the Sonatype snapshot repository (because I need it for a different library) and try to execute `junitPlatformTest` using Gradle, I get the following exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.junit.platform.engine.TestEngine.getGroupId()Ljava/util/Optional;
        at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.computeAttributes(ServiceLoaderTestEngineRegistry.java:48)
        at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.createDiscoveredTestEnginesMessage(ServiceLoaderTestEngineRegistry.java:38)
        at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.lambda$loadTestEngines$0(ServiceLoaderTestEngineRegistry.java:31)
        at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry$$Lambda$7/1685538367.get(Unknown Source)
        at java.util.logging.Logger.log(Logger.java:808)
        at java.util.logging.Logger.info(Logger.java:1597)
        at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.loadTestEngines(ServiceLoaderTestEngineRegistry.java:31)
        at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:53)
        at org.junit.platform.console.tasks.ExecuteTestsTask$$Lambda$2/815033865.get(Unknown Source)
        at org.junit.platform.console.tasks.ExecuteTestsTask.executeTests(ExecuteTestsTask.java:58)
        at org.junit.platform.console.tasks.ExecuteTestsTask.lambda$execute$0(ExecuteTestsTask.java:54)
        at org.junit.platform.console.tasks.ExecuteTestsTask$$Lambda$4/1146743572.call(Unknown Source)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ExecuteTestsTask.execute(ExecuteTestsTask.java:54)
        at org.junit.platform.console.tasks.ConsoleTaskExecutor.executeTask(ConsoleTaskExecutor.java:38)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:54)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
```

Is there any special reason, why the artifacts are published at the Sonatype snapshot repository?

**Comment by sbrannen** [comment]
Milestones in fact are _not_ published in the snapshots repository:

https://oss.sonatype.org/content/repositories/snapshots/org/junit/jupiter/junit-jupiter-api/

Milestones are only published here:

http://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/

**Comment by sbrannen** [comment]
This is likely related to #576 and #578.

**Comment by janschaefer** [comment]
Yes you are right. My fault. I had the wrong URL in my configuration:

    repositories {
        mavenCentral()
        maven {
            url "https://oss.sonatype.org/content/groups/public/"
        } 
     }

However, the problem is still there after changing the configuration to 

    repositories {
        mavenCentral()
        maven {
             url "https://oss.sonatype.org/content/repositories/snapshots/"
        } 
    }

**Comment by sbrannen** [comment]
It sounds like the JUnit Platform Gradle Plugin is automatically pulling in snapshot dependencies.

As I mentioned in #459:

If you don't want to use snapshots with the plugin, make sure you set the version of the plugin **and** your other JUnit Platform dependencies to `1.0.0-M3`.

FYI: to configure the platform version used by the plugin you can do the following.

```groovy
junitPlatform {
    platformVersion = "1.0.0-M3"
}
```

Please let us know if this helps.

**Comment by janschaefer** [comment]
Yes. This helped. It works now. Thank you!

**Comment by sbrannen** [comment]
Great!

Thanks for letting us know.

I'm closing this issue.

**Comment by janschaefer** [comment]
I think the ticket #459 is not the one you meant, right?

**Comment by sbrannen** [comment]
> I think the ticket #459 is not the one you meant, right?

Right. I changed it to #479.
