### ISSUE TITLE
Remove duplicate entries from Standalone Distro

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#761]
## Overview

With #714 solved, current root entries of `junit-platform-console-standalone-1.0.0-SNAPSHOT.jar/META-INF` are:
```
services/
MANIFEST.MF
LICENSE-jopt-simple.md
LICENSE.md
LICENSE.md
LICENSE-notice.md
LICENSE-notice.md
```

After #760 is merged, even more duplicates will appear.

## Deliverables

- [ ] Configure shadow jar task of `junit-platform-console-standalone` to filter duplicate entries

**Comment by sormuras** [comment]
Is the M4 window still open? I could need the duplication-free JAR over at pro:
```
[pro] registered plugins compiler, convention, linker, modulefixer, packager, resolver, runner, uberpackager
[modulefixer] fix junit.platform.console.standalone
java.util.zip.ZipException: duplicate entry: META-INF/LICENSE.md
        at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:231)
        at java.base/java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
        at jdk.jartool/sun.tools.jar.Main.update(Main.java:952)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:354)
        at jdk.jartool/sun.tools.jar.JarToolProvider.run(JarToolProvider.java:37)
        at java.base/java.util.spi.ToolProvider.run(ToolProvider.java:137)
        at com.github.forax.pro.plugin.modulefixer/com.github.forax.pro.plugin.modulefixer.ModuleFixerPlugin.patchModularJar(ModuleFixerPlugin.java:193)
        at com.github.forax.pro.plugin.modulefixer/com.github.forax.pro.plugin.modulefixer.ModuleFixerPlugin.execute(ModuleFixerPlugin.java:185)
        at com.github.forax.pro/com.github.forax.pro.Pro.execute(Pro.java:267)
        at com.github.forax.pro/com.github.forax.pro.Pro.runAll(Pro.java:247)
        at com.github.forax.pro/com.github.forax.pro.Pro.run(Pro.java:237)
        at com.github.forax.pro.bootstrap/com.github.forax.pro.bootstrap.Bootstrap.main(Bootstrap.java:79)
```
