### ISSUE TITLE
Details.TREE does not gracefully handle failure exceptions that don't have a message

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#786]
## Overview

When setting the details level to `Details.TREE` and a single test throws an exception without a message leads to stopping any more tests from executing.

```groovy
import org.junit.platform.console.options.Details

junitPlatform {
    // other settings...
    details = Details.TREE
}
```

```java
    @Test
    void failingTestWithNoMessage() {
          throw new IllegalArgumentException();
    }
```

```
:junitPlatformTest
java.lang.NullPointerException
        at org.junit.platform.console.tasks.TreePrinter.printMessage(TreePrinter.java:146)
        at org.junit.platform.console.tasks.TreePrinter.printThrowable(TreePrinter.java:119)
        at org.junit.platform.console.tasks.TreePrinter.lambda$printVisible$0(TreePrinter.java:93)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.junit.platform.console.tasks.TreePrinter.printVisible(TreePrinter.java:93)
        at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:58)
        at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:68)
        at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:68)
        at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:68)
        at org.junit.platform.console.tasks.TreePrinter.print(TreePrinter.java:52)
        at org.junit.platform.console.tasks.TreePrintingListener.testPlanExecutionFinished(TreePrintingListener.java:44)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionFinished$5(TestExecutionListenerRegistry.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:51)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:27)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionFinished(TestExecutionListenerRegistry.java:87)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:139)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:79)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:69)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:41)

╷
├─ JUnit Jupiter ✔
│  ├─ FirstTest ✔
│  │  ├─ My 1st JUnit 5 test! 😎 ✔
│  │  └─ failingTestWithNoMessage() ✘Option                                        Description
------                                        -----------
-h, --help                                    Display help information.
--disable-ansi-colors                         Disable ANSI colors in output (not
                                                supported by all terminals).
--hide-details                                @Deprecated. Use '--details none' instead.
--details <[none,flat,tree,verbose]>          Select an output details mode for when
                                                tests are executed. Use one of: [none,
...
...
```

## Deliverables

- [ ] `TreePrinter` should handle failing tests with throwables that do not have a failure message

**Comment by mkobit** [comment]
The most common problem I've seen with this is when a test throws an unintentional `NullPointerException` that bubbles out and stops other tests from running.

**Comment by sormuras** [comment]
Will look into it "in detail" tomorrow.

**Comment by sormuras** [comment]
Thanks @mkobit for reporting.

Fixed on master with https://github.com/junit-team/junit5/commit/29c092ad370c794fab497f3aebfdb11be1144796.
