### ISSUE TITLE
Unable to run a single test method from idea: java.lang.Exception: No tests found matching Method ... from org.junit.vintage.engine.descriptor.RunnerRequest

### ISSUE THREAD

**Issue by Vazzilena** [junit-team/junit5#789]
Using IDEA version that provides support for junit 5 M3

IntelliJ IDEA 2017.1
Build #IC-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

When attempting to run a single java test method (right click on method name and select run) I get the exception below. If I run the entire test class everything passes successfully. Attaching the full console output (full.txt)

 WARNING: Method 'public void com.pcbsys.nirvana.client.nChannelToChannelJoinTests.subscribeAndPublishTest() throws java.lang.Exception' could not be resolved

java.lang.Exception: No tests found matching Method subscribeAndPublishTest(com.pcbsys.nirvana.client.nChannelToChannelJoinTests) from org.junit.vintage.engine.descriptor.RunnerRequest@3911c2a7

	
 at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
 at org.junit.vintage.engine.discovery.TestClassRequestResolver.determineRunnerTestDescriptor(TestClassRequestResolver.java:74)
 at org.junit.vintage.engine.discovery.TestClassRequestResolver.addRunnerTestDescriptor(TestClassRequestResolver.java:63)
 at org.junit.vintage.engine.discovery.TestClassRequestResolver.populateEngineDescriptorFrom(TestClassRequestResolver.java:57)
 at org.junit.vintage.engine.discovery.JUnit4DiscoveryRequestResolver.populateEngineDescriptor(JUnit4DiscoveryRequestResolver.java:88)
 at org.junit.vintage.engine.discovery.JUnit4DiscoveryRequestResolver.resolve(JUnit4DiscoveryRequestResolver.java:49)
 at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:47)
 at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:109)
 at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
 at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:61)
 at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
 at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
 at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Original issue logged under IDEA project but looks like it belongs to JUNIT: https://youtrack.jetbrains.com/issue/IDEA-170573

**Comment by sormuras** [comment]
Related issue: #549 -- duplicate?

**Comment by Vazzilena** [comment]
Looks like a duplicate indeed ...although my setup is simplified. Is there a resolution?

**Comment by marcphilipp** [comment]
I've discussed possible solutions with @akozlova: We currently use `Filter.matchMethodDescription(Description.createTestDescription(testClass, testMethod.getName()))` which does not work for method with parameters. 

We'll need to look into building a custom filter like IntelliJ does:
https://github.com/JetBrains/intellij-community/blob/master/plugins/junit_rt/src/com/intellij/junit4/JUnit4TestRunnerUtil.java#L169

**Comment by Koziolek** [comment]
Hi!

There is bug in Idea https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-170817 it is fixed, but waiting for 2017.1.2

**Comment by marcphilipp** [comment]
IDEA-170817 is a different bug. This one is about executing a single JUnit _Vintage_ test method that has parameters.

**Comment by nicolaiparlog** [comment]
As  @Vazzilena confirmed that this is a duplicate of #549, should this issue be closed?
