### ISSUE TITLE
Platform 1.0.0-M3 throws exception NoSuchMethodError

### ISSUE THREAD

**Issue by MichalMichalak** [junit-team/junit5#803]
Hello. I tried to run a tests `./gradlew clean test` but it failed with an exception. I need to stick to M3 because of JMockit support, but when I remove it from the class path result is the same. Am I doing anything wrong? How should I set it up properly? Thanks.

Exception:
```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: org.junit.platform.engine.TestDescriptor.prune()V
        at org.junit.platform.launcher.core.Root.prune(Root.java:71)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:123)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:79)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:69)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:41)
Caused by: java.lang.NoSuchMethodError: org.junit.platform.engine.TestDescriptor.prune()V
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
        at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
        at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
        ... 10 more
```

I am using Gradle 4.3.1, with below script.
```groovy
buildscript {
    ext.junitJupiterVersion = '5.0.0-M3'
    ext.junitPlatformVersion = '1.0.0-M3'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.junit.platform:junit-platform-gradle-plugin:${junitPlatformVersion}"
    }
}

apply plugin: 'java'
apply plugin: 'jacoco'
apply plugin: 'org.junit.platform.gradle.plugin'

tasks.withType(JavaCompile) {
    testCompile 'org.jmockit:jmockit:1.31'
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    testCompile "org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}"
    testRuntime "org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}"
}
```

It happens for any test. Example below.
```java
public class AppTest {
    @Test
    public void t() {
        App a = new App(new Calc());
        int result = a.calculate();
        Assertions.assertEquals(999, result);
    }
}
```

**Comment by mkobit** [comment]
This comes from the `M3` Gradle plugin using a dynamic version for resolution (`1.*`), which causes it to select the "highest" version. You could verify this by running `./gradlew dependencies` as well.

If you aren't going to upgrade to `M4` yet, you should explicitly set the version in the extension, like this:

```groovy
junitPlatform {
    platformVersion '1.0.0-M3'
}
```

This was resolved in `M4` in https://github.com/junit-team/junit5/issues/576

**Comment by MichalMichalak** [comment]
Solved. Thank you.
