### ISSUE TITLE
ConsoleLauncher --scan-classpath option fails on Java 9

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#807]
## Overview

Classpath scanning fails for some implicit roots (only on Java 9):

```
[...]
Apr. 26, 2017 4:16:06 NACHM. org.junit.platform.commons.util.ClasspathScanner logWarning
WARNUNG: Failed to load java.lang.Class for path [...\application-junit5-jdk9-demo\.\target\main\exploded\integration\integration\LegacyTest.class] during classpath scanning.
java.lang.NoClassDefFoundError: integration/LegacyTest (wrong name: target/main/exploded/integration/integration/LegacyTest)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:983)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:173)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:771)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:669)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:592)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:550)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:473)
        at java.base/jdk.internal.loader.Loader.loadClass(Loader.java:492)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:473)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ReflectionUtils.loadClass(ReflectionUtils.java:344)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ClasspathScanner.processClassFileSafely(ClasspathScanner.java:156)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ClasspathScanner.lambda$findClassesForPath$3(ClasspathScanner.java:141)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ClassFileVisitor.visitFile(ClassFileVisitor.java:41)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ClassFileVisitor.visitFile(ClassFileVisitor.java:24)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2695)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2767)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ClasspathScanner.findClassesForPath(ClasspathScanner.java:141)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ClasspathScanner.findClassesForUri(ClasspathScanner.java:125)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ClasspathScanner.scanForClassesInClasspathRoot(ClasspathScanner.java:103)
        at junit.platform.console.standalone/org.junit.platform.commons.util.ReflectionUtils.findAllClassesInClasspathRoot(ReflectionUtils.java:501)
        at junit.platform.console.standalone/org.junit.vintage.engine.discovery.ClasspathRootSelectorResolver.resolve(ClasspathRootSelectorResolver.java:33)
        at junit.platform.console.standalone/org.junit.vintage.engine.discovery.ClasspathRootSelectorResolver.resolve(ClasspathRootSelectorResolver.java:22)
        at junit.platform.console.standalone/org.junit.vintage.engine.discovery.JUnit4DiscoveryRequestResolver.lambda$resolveSelectorsOfSingleType$0(JUnit4DiscoveryRequestResolver.java:75)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
        at junit.platform.console.standalone/org.junit.vintage.engine.discovery.JUnit4DiscoveryRequestResolver.resolveSelectorsOfSingleType(JUnit4DiscoveryRequestResolver.java:74)
        at junit.platform.console.standalone/org.junit.vintage.engine.discovery.JUnit4DiscoveryRequestResolver.collectTestClasses(JUnit4DiscoveryRequestResolver.java:56)
        at junit.platform.console.standalone/org.junit.vintage.engine.discovery.JUnit4DiscoveryRequestResolver.resolve(JUnit4DiscoveryRequestResolver.java:48)
        at junit.platform.console.standalone/org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:64)
        at junit.platform.console.standalone/org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
        at junit.platform.console.standalone/org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
        at junit.platform.console.standalone/org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at junit.platform.console.standalone/org.junit.platform.launcher.Launcher.execute(Launcher.java:96)
        at junit.platform.console.standalone/org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
        at junit.platform.console.standalone/org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
        at junit.platform.console.standalone/org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.replaceThreadContextClassLoaderAndInvoke(CustomContextClassLoaderExecutor.java:41)
        at junit.platform.console.standalone/org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:31)
        at junit.platform.console.standalone/org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
        at junit.platform.console.standalone/org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:85)
        at junit.platform.console.standalone/org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:75)
        at junit.platform.console.standalone/org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:48)
        at com.github.forax.pro.plugin.tester@0.9/com.github.forax.pro.plugin.tester.TesterPlugin.executeConsoleLauncher(TesterPlugin.java:62)
        at com.github.forax.pro.plugin.tester@0.9/com.github.forax.pro.plugin.tester.TesterPlugin.execute(TesterPlugin.java:53)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.execute(Pro.java:325)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.runAll(Pro.java:305)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.run(Pro.java:295)
        at REPL.$JShell$17.do_it$($JShell$17.java:4)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:563)
        at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:198)
        at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:107)
        at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:108)
        at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:134)
        at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:225)
        at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76)
        at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137)
        at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70)

?[36m.?[0m
?[36m+--?[0m ?[36mJUnit Jupiter?[0m ?[32m[OK]?[0m
?[36m| +--?[0m ?[36mApplicationPluginTests?[0m ?[32m[OK]?[0m
?[36m| | '--?[0m ?[34mloadedPluginListIsNotEmpty()?[0m ?[32m[OK]?[0m
?[36m| +--?[0m ?[36mApplicationVersionTests?[0m ?[32m[OK]?[0m
?[36m| | +--?[0m ?[34mmajorIsNine()?[0m ?[32m[OK]?[0m
?[36m| | '--?[0m ?[34mversion()?[0m ?[32m[OK]?[0m
?[36m| '--?[0m ?[36mReverseTests?[0m ?[32m[OK]?[0m
?[36m|   '--?[0m ?[34mreverse()?[0m ?[32m[OK]?[0m
?[36m'--?[0m ?[36mJUnit Vintage?[0m ?[32m[OK]?[0m

Test run finished after 40 ms
[         5 containers found      ]
[         0 containers skipped    ]
[         5 containers started    ]
[         0 containers aborted    ]
[         5 containers successful ]
[         0 containers failed     ]
[         4 tests found           ]
[         0 tests skipped         ]
[         4 tests started         ]
[         0 tests aborted         ]
[         4 tests successful      ]
[         0 tests failed          ]

[pro] DONE !          elapsed time 415 ms

```

## Deliverables

- [ ] Investigate and fix reason

**Comment by sormuras** [comment]
`java.class.path` included `.` and `--scan-classpath` without a parameter tried to scan for test classes starting at `.` directory. All discovered `.class` files had a _wrong_ package name.

Solution: explicitely pass classpath roots via `--scan-classpath path1:path2:...` (and don't forget to pass path1:path2... via `--classpath` as well)
