### ISSUE TITLE
UniqueId.parse fails for methods with array type parameters

### ISSUE THREAD

**Issue by jlink** [junit-team/junit5#810]
## Bug description
```
String idString = uniqueIdFromMethodDescriptorWithArrayParameter.toString();
UniqueId id = UniqueId.parse(idString);
```
will fail with `PreconditionViolation` since array types are described with an `[` in front but `[` chars are currently forbidden as segment values.

## Suggested Solution

Change representation of array types in `ReflectionUtils.findMethod(clazz, methodName, parameterTypeNames)` and `StringUtils.nullSafeToString(classes)`. 

Alternative: Don't use `[` as separator char in unique IDs. But some 3rd party tools might already have committed to the current format.

## Deliverables

- [ ] Encode `segmentType` and `value` in constructor and decode in `parse`.

**Comment by jlink** [comment]
Just thought of a 3rd alternative: Escape/unescape forbidden characters. Seems like a valid approach.

**Comment by sormuras** [comment]
> Alternative: Don't use `[` as separator char in unique IDs.

+1

It is still time for breaking changes. Introducing mangling of IDs is something we can do after GA.

**Comment by jlink** [comment]
Using a different separator might break another engine's values. Escaping does not have any of those disadvantages.

**Comment by sbrannen** [comment]
Good catch! 👍 

We've been generating unique IDs such as `[engine:junit-jupiter]/[class:org.junit.jupiter.engine.extension.ArrayTests$PrimitiveArrayMethodInjectionTestCase]/[method:primitiveArray([I)]` for quite some time, but we obviously never attempted to parse the string representation back into a `UniqueId` object.

**Comment by sbrannen** [comment]
FYI: I reproduced this error with a test case run by JUnit Jupiter on `master`.

```java
@ExtendWith(PrimitiveArrayParameterResolver.class)
private static class PrimitiveArrayMethodInjectionTestCase {

	@Test
	void primitiveArray(int... ints) {
		assertArrayEquals(new int[] { 1, 2, 3 }, ints);
	}
}
```

The resulting exception is:

<details>

```
org.junit.platform.commons.util.PreconditionViolationException: type or value 'primitiveArray([I)' must not contain '['
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:285)
	at org.junit.platform.engine.UniqueIdFormat.checkDoesNotContain(UniqueIdFormat.java:88)
	at org.junit.platform.engine.UniqueIdFormat.checkAllowed(UniqueIdFormat.java:82)
	at org.junit.platform.engine.UniqueIdFormat.createSegment(UniqueIdFormat.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.junit.platform.engine.UniqueIdFormat.parse(UniqueIdFormat.java:65)
	at org.junit.platform.engine.UniqueId.parse(UniqueId.java:51)
	at org.junit.jupiter.engine.extension.ArrayTests.lambda$0(ArrayTests.java:41)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.jupiter.engine.extension.ArrayTests.executeTestsForPrimitiveArrayMethodInjectionCases(ArrayTests.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:303)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:114)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.lambda$3(MethodTestDescriptor.java:171)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.invokeTestMethod(MethodTestDescriptor.java:168)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:115)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:1)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$0(HierarchicalTestExecutor.java:81)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$0(HierarchicalTestExecutor.java:91)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$0(HierarchicalTestExecutor.java:91)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.launcher.Launcher.execute(Launcher.java:96)
```

</details>

**Comment by sbrannen** [comment]
The most robust solution would be to use a format similar to JSON, where the `segmentType` and `value` are wrapped in quotes (or some other character), and any occurrence of the wrapping character within a supplied `segmentType` and `value` is escaped.

That should solve all problems, future and present.

**Comment by marcphilipp** [comment]
We could also URI encode/decode `/`, `[`, `]`, `:` etc. in each segment.

**Comment by marcphilipp** [comment]
**Team decision:** Use URI encoding for `segmentType` and `value`.

**Comment by sbrannen** [comment]
_in progress_ by @sormuras
