### ISSUE TITLE
Android plugin: PreconditionViolationException: Cannot create Launcher without at least one TestEngine;

### ISSUE THREAD

**Issue by yogurtearl** [junit-team/junit5#827]
With Junit 5.0.0-M3 and Android Gradle Plugin 2.4.0-alpha7 I get this error when running tests from gradle CLI.

It works fine with Android Gradle Plugin 2.3.1

```
org.junit.platform.commons.util.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
        at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:207)
        at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:52)
        at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:42)
        at org.junit.platform.console.tasks.ExecuteTestsTask.executeTests(ExecuteTestsTask.java:58)
        at org.junit.platform.console.tasks.ExecuteTestsTask.lambda$execute$0(ExecuteTestsTask.java:54)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ExecuteTestsTask.execute(ExecuteTestsTask.java:54)
        at org.junit.platform.console.tasks.ConsoleTaskExecutor.executeTask(ConsoleTaskExecutor.java:38)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:54)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
```

**Comment by sbrannen** [comment]
@yogurtearl, can you please provide more context -- for example, in the form of a minimalistic project that reproduces the error?

**Comment by marcphilipp** [comment]
Closing due to lack of activity. Please reopen if the issue persists.
