### ISSUE TITLE
Unable to setup dev environment

### ISSUE THREAD

**Issue by deen13** [junit-team/junit5#881]
## Extending the gradle plugin

I would be very grateful if someone could help me in setting up my development environment.

Setup: 
- Groovy 2.4.9
- IntelliJ IDEA 2017.1 - Build #IU-171.3780.107, built on March 22, 2017
- JRE: 1.8.0_112-release-736-b13 x86_64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Mac OS X 10.12.5
- Gradle 3.4.1

### What ive tried 

- Resolving the dependencies by `gradle :junit-platform-gradle-plugin:--refresh-dependencies --stacktrace`

This fails with `
A problem occurred evaluating root project 'junit5'.
> No signature of method: java.text.SimpleDateFormat.format() is applicable for argument types: (java.util.Date) values: [Sat Jun 10 21:53:18 CEST 2017]
  Possible solutions: print(java.io.PrintWriter), print(java.lang.Object)
`

- Running the tests

This fails with 
```
/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java -Dtools.jar=/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/tools.jar -Dgroovy.home=/Users/deen/.sdkman/candidates/groovy/2.4.9 -Dgroovy.starter.conf=/Users/deen/.sdkman/candidates/groovy/2.4.9/conf/groovy-starter.conf -Dhttp.proxyHost=10.1.1.30 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=10.1.1.30 -Dhttps.proxyPort=8080 -Dproxy.authentication.username=dennis.dierkes -Dproxy.authentication.password=schule -Dfile.encoding=UTF-8 -classpath /Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-2.4.9.jar org.codehaus.groovy.tools.GroovyStarter --conf /Users/deen/.sdkman/candidates/groovy/2.4.9/conf/groovy-starter.conf --main groovy.ui.GroovyMain --classpath .:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/ant-1.9.4.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/ant-antlr-1.9.4.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/ant-junit-1.9.4.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/ant-launcher-1.9.4.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/bsf-2.4.0.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/commons-cli-1.2.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/commons-logging-1.2.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/gpars-1.2.1.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-ant-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-bsf-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-console-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-docgenerator-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-groovydoc-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-groovysh-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-jmx-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-json-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-jsr223-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-nio-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-servlet-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-sql-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-swing-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-templates-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-test-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-testng-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/groovy-xml-2.4.9.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/hamcrest-core-1.3.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/ivy-2.4.0.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/jansi-1.11.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/jcommander-1.47.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/jline-2.12.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/jsp-api-2.0.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/jsr166y-1.7.0.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/junit-4.12.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/multiverse-core-0.7.0.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/qdox-1.12.1.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/servlet-api-2.4.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/testng-6.8.13.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/xmlpull-1.1.3.1.jar:/Users/deen/.sdkman/candidates/groovy/2.4.9/lib/xstream-1.4.7.jar --encoding=UTF-8 /Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 12: unable to resolve class org.gradle.api.Project
 @ line 12, column 1.
   import org.gradle.api.Project
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 13: unable to resolve class org.gradle.api.Task
 @ line 13, column 1.
   import org.gradle.api.Task
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 21: unable to resolve class spock.lang.Issue
 @ line 21, column 1.
   import spock.lang.Issue
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 14: unable to resolve class org.gradle.api.artifacts.Configuration
 @ line 14, column 1.
   import org.gradle.api.artifacts.Configuration
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 16: unable to resolve class org.gradle.api.tasks.JavaExec
 @ line 16, column 1.
   import org.gradle.api.tasks.JavaExec
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 18: unable to resolve class org.gradle.testfixtures.ProjectBuilder
 @ line 18, column 1.
   import org.gradle.testfixtures.ProjectBuilder
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 17: unable to resolve class org.gradle.api.tasks.testing.Test
 @ line 17, column 1.
   import org.gradle.api.tasks.testing.Test
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 20: unable to resolve class org.junit.platform.engine.discovery.ClassNameFilter
 @ line 20, column 1.
   import org.junit.platform.engine.discovery.ClassNameFilter
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 19: unable to resolve class org.junit.platform.console.ConsoleLauncher
 @ line 19, column 1.
   import org.junit.platform.console.ConsoleLauncher
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 15: unable to resolve class org.gradle.api.plugins.JavaPlugin
 @ line 15, column 1.
   import org.gradle.api.plugins.JavaPlugin
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 22: unable to resolve class spock.lang.Specification
 @ line 22, column 1.
   import spock.lang.Specification
   ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 50: unable to resolve class JUnitPlatformPlugin 
 @ line 50, column 61.
   nitPlatformPlugin) instanceof JUnitPlatf
                                 ^

/Users/deen/Documents/Development/Groovy/junit5/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy: 51: unable to resolve class JUnitPlatformExtension 
 @ line 51, column 61.
   e('junitPlatform') instanceof JUnitPlatf
                                 ^

13 errors


Process finished with exit code 1



```

**Comment by marcphilipp** [comment]
From your path it looks like you're running Java 9. can you try `./gradlew` instead of `gradle`, please?

**Comment by deen13** [comment]
The gradle wrapper ends up with the following exception

```
NOTE: Picked up JDK_JAVA_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED
Unzipping /Users/deen/.gradle/wrapper/dists/gradle-3.5-bin/daoimhu7k5rlo48ntmxw2ok3e/gradle-3.5-bin.zip to /Users/deen/.gradle/wrapper/dists/gradle-3.5-bin/daoimhu7k5rlo48ntmxw2ok3e
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1252)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1153)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1160)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:997)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:960)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:216)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:162)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by marcphilipp** [comment]
Can you switch to Java 8 and try again?

**Comment by deen13** [comment]
Thank you Marc! I solved it by adding `org.gradle.java.home = /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home` to the project specific gradle.properties file
